"""Section data for Sections 9-12: Customer Engagement, Billing, Outage Mgmt, Asset Mgmt."""
from collections import OrderedDict

# Sections 9-12: Customer Engagement, Billing, Outage Mgmt, Asset Mgmt
SECTION_DATA = OrderedDict()

SECTION_DATA["CustomerEngagement"] = {
    "title": "Customer Engagement & Demand Response  - `UT-CRM` `UT-DRP` `UT-OAD` `UT-DCE`",
    "description": "Manages customer interactions, demand response programs, OpenADR communication, and DER customer enrollment. Includes customer portal, IVR, DR event management, and energy efficiency programs.",
    "capabilities": ["UT-CRM", "UT-DRP", "UT-OAD", "UT-DCE"],
    "subflows": OrderedDict([
        ("9.1", {
            "title": "Customer Portal & Self-Service",
            "description": "Customers access the web portal and mobile app to view usage data, pay bills, report outages, manage account preferences, and enroll in programs. Portal integrates with CIS, MDM, and OMS.",
            "actors": ["Customer", "Customer Service Rep", "Portal Admin"],
            "systems": ["Customer Portal", "CIS (Oracle Utilities)", "MDM", "OMS", "Payment Gateway (CyberSource)"],
            "mermaid": [
                "Customer->>Portal: Login\nuser=CUST001, MFA=authenticated, session=SES-042",
                "Portal->>CIS: Fetch customer data\naccount=ACCT-001, premise=PREM-001, service=Electric",
                "CIS->>Portal: Account summary\nbalance=$125.40, due_date=2026-07-15, status=Active",
                "Portal->>MDM: Request usage data\nmeter=MTR-001, period=last 30 days, interval=Hourly",
                "MDM->>Portal: Usage data\n3,450 kWh, 12.4 kW peak, load factor=0.62",
                "Portal->>Portal: Calculate comparison\nvs last month +5%, vs prior year -2%, target -3%",
                "Portal->>OMS: Check outage status\npremise=PREM-001, service=Electric, region=NW",
                "OMS->>Portal: No outages\nservice area normal, 0 active outages nearby",
                "Customer->>Portal: Pay bill\namount=$125.40, payment_method=Credit Card, auto_pay=No",
                "Portal->>PaymentGW: Process payment\ncard=xxxx-4242, amount=$125.40, cvv=validated",
                "PaymentGW->>Portal: Payment success\ntransaction=TXN-2026-042, auth=APPROVED, ref=REF-001",
                "Portal->>CIS: Update balance\npayment posted, new_balance=$0.00, receipt=REC-042",
                "Customer->>Portal: Report outage\nstreet_light=POLE-047, issue=No power, 2 customers",
                "Portal->>OMS: Create trouble ticket\nTT-2026-042, priority=High, source=Portal",
                "Portal->>Customer: CSAT survey\nrating=5/5, feedback=Good, comment=Resolved quickly",
            ],
            "integrations": [
                ("Customer Portal", "Login", "AuthenticateCustomer", "Customer Portal", "CIS (Oracle Utilities)", "Portal API (OAuth2)", "CIS API (REST)", "API-led (Real-time)", "Medium"),
                ("Customer Portal", "Usage", "FetchUsageData", "Customer Portal", "MDM", "Portal API (OAuth2)", "MDM API (REST)", "API-led (Real-time)", "Medium"),
                ("Customer Portal", "Outage", "CheckOutageStatus", "Customer Portal", "OMS", "Portal API (OAuth2)", "OMS API (REST)", "API-led (Real-time)", "Medium"),
                ("Customer Portal", "Payment", "ProcessBillPayment", "Customer Portal", "Payment Gateway (CyberSource)", "Portal API (OAuth2)", "Payment GW API (REST/SOAP)", "API-led (Real-time)", "High"),
                ("Customer Portal", "Balance", "UpdateCustomerBalance", "Customer Portal", "CIS (Oracle Utilities)", "Portal API (OAuth2)", "CIS API (REST)", "API-led (Real-time)", "High"),
                ("Customer Portal", "Ticket", "CreateTroubleTicket", "Customer Portal", "OMS", "Portal API (OAuth2)", "OMS API (REST)", "Event-driven", "Medium"),
                ("Customer Portal", "Survey", "SubmitCSATSurvey", "Customer Portal", "Analytics Platform", "Portal API (OAuth2)", "Analytics API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-CP-01", "Validate portal page load response time under 3 seconds for 95th percentile", "AuthenticateCustomer", "Portal dashboard loads within 3s for 95% of requests", "High"),
                ("AC-CP-02", "Confirm payment processing completes with end-to-end encryption (PCI-DSS)", "ProcessBillPayment", "Payment data encrypted in transit and at rest, PCI compliant", "High"),
                ("AC-CP-03", "Verify outage reporting accuracy within 100 meters of actual location", "CreateTroubleTicket", "Outage location mapped within 100m of customer premise", "Medium"),
                ("AC-CP-04", "Ensure self-service adoption rate exceeds 60% of total customer interactions", "SubmitCSATSurvey", "Monthly self-service interactions >60% of all service contacts", "Medium"),
            ],
        }),
        ("9.2", {
            "title": "OpenADR VEN/VTN Operations",
            "description": "Utility VTN communicates with customer VENs (smart thermostats, BMS, DER) using OpenADR 2.0b. DR events are created, published, and tracked with opt-in/opt-out and reporting.",
            "actors": ["DR Operator", "Aggregator", "Customer VEN"],
            "systems": ["OpenADR VTN (EPRI OpenADR)", "DRMS", "VEN (Customer)", "MDM", "ISO Market System"],
            "mermaid": [
                "Operator->>VTN: Create DR event\nEVENT-2026-042, Peak Rewards, 2026-07-08T14:00-17:00",
                "VTN->>VTN: Validate event\nsignal_type=x-EI-Simple, units=kW, duration=3hr",
                "VTN->>VEN: Publish event\nEiEvent, eventID=EVENT-2026-042, interval=14:00-17:00",
                "VEN->>VTN: Acknowledge receipt\nvenID=VEN-THERMOSTAT-001, oadrCreatedEvent",
                "VEN->>VEN: Evaluate event\nbaseline=5 kW, opt_status=OptIn, reduction=1.5 kW",
                "VEN->>VTN: Report opt status\nvenID=VEN-THERMOSTAT-001, optType=optIn, reason=Program",
                "VTN->>VTN: Track opt-ins\n150 VENs opted in, 15 opted out, 35 no response",
                "Operator->>VTN: Monitor participation\n200 sites, 85% opted in, target=80%",
                "VEN->>VTN: Telemetry report\ninterval=14:00, load=3.2 kW, baseline=5.0 kW, reduction=1.8 kW",
                "VEN->>VTN: Telemetry report\ninterval=15:00, load=3.5 kW, baseline=5.0 kW, reduction=1.5 kW",
                "VEN->>VTN: Telemetry report\ninterval=16:00, load=3.0 kW, baseline=5.0 kW, reduction=2.0 kW",
                "VTN->>MDM: Request interval data\nmeter=MTR-001, 2026-07-08 14:00-17:00, 15-min intervals",
                "MDM->>VTN: Interval data\n12 intervals, actual_kWh vs baseline_kWh",
                "VTN->>VTN: Calculate performance\navg reduction=1.77 kW, total=265 kWh, target met=Yes",
                "VTN->>ISO: Submit settlement\naggregator=AGG-001, 200 VENs, 265 kWh reduction",
                "VTN->>Operator: Post-event report\nEVENT-2026-042, participation=85%, reduction=265 kWh",
            ],
            "integrations": [
                ("OpenADR", "Event", "CreateDREvent", "DR Operator HMI", "OpenADR VTN (EPRI OpenADR)", "Operator UI (REST)", "VTN API (REST)", "API-led (Real-time)", "Medium"),
                ("OpenADR", "Publish", "PublishDREvent", "OpenADR VTN (EPRI OpenADR)", "VEN (Customer)", "VTN OpenADR 2.0b", "VEN OpenADR 2.0b", "Event-driven", "High"),
                ("OpenADR", "Opt", "ProcessOptInOut", "VEN (Customer)", "OpenADR VTN (EPRI OpenADR)", "VEN OpenADR 2.0b", "VTN OpenADR 2.0b", "Event-driven", "Medium"),
                ("OpenADR", "Telemetry", "ReportVENLoad", "VEN (Customer)", "OpenADR VTN (EPRI OpenADR)", "VEN OpenADR 2.0b", "VTN OpenADR 2.0b", "API-led (Real-time)", "Medium"),
                ("OpenADR", "Meter", "FetchIntervalData", "OpenADR VTN (EPRI OpenADR)", "MDM", "VTN API (REST)", "MDM API (REST)", "Batch (Scheduled)", "Medium"),
                ("OpenADR", "Settlement", "SubmitSettlementData", "OpenADR VTN (EPRI OpenADR)", "ISO Market System", "VTN API (REST)", "ISO API (REST)", "Batch (Scheduled)", "High"),
                ("OpenADR", "Report", "GeneratePostEventReport", "OpenADR VTN (EPRI OpenADR)", "DRMS", "VTN API (REST)", "DRMS API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-OADR-01", "Validate VTN-to-VEN event publication reaches 95% of VENs within 5 minutes", "PublishDREvent", "At least 95% of VENs acknowledge event within 5 min of publish", "High"),
                ("AC-OADR-02", "Confirm opt-in/opt-out processing completes within 60 seconds of VEN response", "ProcessOptInOut", "VEN opt status reflected in VTN within 60s", "Medium"),
                ("AC-OADR-03", "Verify telemetry report data accuracy within \u00b12% of meter interval data", "ReportVENLoad", "VEN-reported load matches MDM interval data within 2%", "Medium"),
                ("AC-OADR-04", "Ensure settlement data submission completes within 24 hours of event end", "SubmitSettlementData", "Settlement data submitted to ISO within 24 hr window", "High"),
            ],
        }),
        ("9.3", {
            "title": "Demand Response Program Management",
            "description": "Utility designs and manages DR programs (Peak Rewards, Critical Peak Pricing, Emergency). Customers are recruited, enrolled, and their performance tracked for settlement and incentive payments.",
            "actors": ["DR Program Manager", "Customer", "DRMS Administrator"],
            "systems": ["DRMS", "CRM (Salesforce)", "CIS (Oracle Utilities)", "MDM", "Billing System"],
            "mermaid": [
                "Mgr->>DRMS: Design DR program\nPeak Rewards, season=Summer 2026, target=5 MW, budget=$500K",
                "DRMS->>CRM: Identify eligible customers\ncriteria=Residential, AC load>3 kW, solar=No",
                "CRM->>DRMS: Customer list\n12,500 eligible customers, 2,500 enrolled last year",
                "Mgr->>DRMS: Launch enrollment campaign\nemail+sms, target=500 new enrollments, deadline=June 15",
                "CRM->>Customer: Recruitment message\nprogram=Peak Rewards, incentive=$50/yr, 15 events max",
                "Customer->>DRMS: Enroll online\ncustomer=CUST-001, premise=PREM-001, device=Thermostat",
                "DRMS->>CIS: Validate account\npremise=PREM-001, status=Active, service_class=Residential",
                "CIS->>DRMS: Account valid\ncredit_score=Good, avg_bill=$185/mo, deposit=None",
                "DRMS->>CRM: Update enrollment\nCUST-001, program=Peak Rewards, enrolled=2026-06-01",
                "Operator->>DRMS: Trigger DR event\nPeak Rewards, 2026-07-08T14:00-17:00, forecast=95\u00b0F",
                "DRMS->>VTN: Create OpenADR event\n3 hr, 1.5 kW reduction target per site",
                "DRMS->>MDM: Verify load drop\ninterval 14:00-17:00, 2,500 enrolled vs baseline",
                "MDM->>DRMS: Load drop confirmed\navg 1.2 kW/site, total=3.0 MW, target=3.5 MW",
                "DRMS->>CIS: Calculate incentives\n$8/event x 2,500 participants x 1 event = $20,000",
                "CIS->>Billing: Apply credit\nCUST-001 to CUST-2500: $8 credit, billing cycle=August",
                "DRMS->>Mgr: Program evaluation\n3.0 MW reduction, 85% target, $20K incentives, ROI=18:1",
            ],
            "integrations": [
                ("DRMS", "Design", "DesignDRProgram", "DR Program Manager", "DRMS", "Manager UI (REST)", "DRMS API (REST)", "API-led (Real-time)", "Simple"),
                ("DRMS", "Eligibility", "IdentifyEligibleCustomers", "DRMS", "CRM (Salesforce)", "DRMS API (REST)", "CRM API (REST)", "Batch (Scheduled)", "Medium"),
                ("DRMS", "Enroll", "EnrollCustomerProgram", "Customer Portal", "DRMS", "Portal API (OAuth2)", "DRMS API (REST)", "API-led (Real-time)", "Simple"),
                ("DRMS", "Validate", "ValidateCustomerAccount", "DRMS", "CIS (Oracle Utilities)", "DRMS API (REST)", "CIS API (REST)", "API-led (Real-time)", "Medium"),
                ("DRMS", "Event", "TriggerDREvent", "DR Program Manager", "DRMS", "Manager UI (REST)", "DRMS API (REST)", "API-led (Real-time)", "Medium"),
                ("DRMS", "Measurement", "VerifyLoadReduction", "DRMS", "MDM", "DRMS API (REST)", "MDM API (REST)", "Batch (Scheduled)", "High"),
                ("DRMS", "Incentive", "ApplyIncentiveCredit", "DRMS", "CIS (Oracle Utilities)", "DRMS API (REST)", "CIS API (REST)", "Batch (Scheduled)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-DRP-01", "Validate enrollment completion within 2 business days of customer application", "EnrollCustomerProgram", "Customer confirmed enrolled within 48 hrs of application", "High"),
                ("AC-DRP-02", "Confirm load drop measurement accuracy within \u00b15% of CBL methodology", "VerifyLoadReduction", "MDM baseline comparison matches CBL within 5%", "High"),
                ("AC-DRP-03", "Verify incentive credits appear on customer bill within next billing cycle", "ApplyIncentiveCredit", "Incentive credit line item present on August bill", "Medium"),
                ("AC-DRP-04", "Ensure program performance reports include participation, load drop, and incentive totals", "DesignDRProgram", "Monthly report contains all KPIs with trend analysis", "Medium"),
            ],
        }),
        ("9.4", {
            "title": "DER Customer Enrollment",
            "description": "Customers with solar PV, battery storage, and EV chargers apply for interconnection. The utility processes the application, inspects installation, installs net meter, and enrolls in DER programs.",
            "actors": ["Customer", "DER Engineer", "Inspector", "Metering Tech"],
            "systems": ["DER Portal", "DERMS", "CIS", "MDM", "GIS", "CRM"],
            "mermaid": [
                "Customer->>DER_Portal: Submit application\nsolar=10 kW PV, battery=13.5 kWh, address=123 Main St",
                "DER_Portal->>CIS: Validate premise\naccount=ACCT-001, premise=PREM-001, service=Electric",
                "CIS->>DER_Portal: Premise valid\nservice_class=Residential, transformer_capacity=50 kVA",
                "DER_Portal->>CRM: Create lead\nCUST-001, solar+storage, lead_source=Online Portal",
                "DER_Engineer->>DER_Portal: Review application\nsolar=10 kW, inverter=SE10000H, panel=Q.PEAK",
                "DER_Engineer->>GIS: Check transformer\nTX-001: 50 kVA, existing load=25 kVA, headroom=25 kVA",
                "GIS->>DER_Engineer: Transformer OK\nheadroom=25 kVA, sufficient for 10 kW solar",
                "DER_Engineer->>DER_Portal: Approve application\ncondition=Net meter install, inspection required",
                "DER_Portal->>Inspector: Schedule inspection\nPREM-001, solar+storage, date=2026-07-10",
                "Inspector->>DER_Portal: Inspection pass\nwiring=Code, inverter=UL1741, disconnect=Installed",
                "DER_Portal->>Meter_tech: Exchange meter\nMTR-001: remove, net meter MTR-NET-001: install",
                "Meter_tech->>MDM: Register net meter\nMTR-NET-001: bidirectional, multiplier=1.0",
                "MDM->>Meter_tech: Meter activated\nMTR-NET-001: 15-min interval, net consumption/generation",
                "DER_Portal->>DERMS: Enroll customer\nDER-2026-001: 10 kW PV, 13.5 kWh battery, export=Yes",
                "DERMS->>DER_Portal: Enrollment complete\nnet_metering=True, program=Net Energy Metering, effective=2026-07-15",
                "DER_Portal->>Customer: Welcome notification\nsystem=10 kW solar, enrollment=NEM, portal=MyDER",
            ],
            "integrations": [
                ("DER Enrollment", "Apply", "SubmitDERApplication", "DER Portal", "CIS (Oracle Utilities)", "Portal API (OAuth2)", "CIS API (REST)", "API-led (Real-time)", "Medium"),
                ("DER Enrollment", "Lead", "CreateCRMLead", "DER Portal", "CRM (Salesforce)", "Portal API (OAuth2)", "CRM API (REST)", "API-led (Real-time)", "Simple"),
                ("DER Enrollment", "Review", "CheckTransformerCapacity", "GIS (ArcGIS)", "DER Portal", "GIS API (REST)", "Portal API (REST)", "API-led (Real-time)", "Medium"),
                ("DER Enrollment", "Inspect", "ScheduleSiteInspection", "DER Portal", "Inspector Mobile App", "Portal API (REST)", "Field App API (OAuth2)", "API-led (Real-time)", "Medium"),
                ("DER Enrollment", "Meter", "ExchangeNetMeter", "DER Portal", "MDM", "Portal API (REST)", "MDM API (REST)", "API-led (Real-time)", "High"),
                ("DER Enrollment", "DerMs", "EnrollCustomerDERMS", "DER Portal", "DERMS", "Portal API (REST)", "DERMS API (REST)", "API-led (Real-time)", "Medium"),
                ("DER Enrollment", "Notify", "SendWelcomeNotification", "DER Portal", "Notification Service", "Portal API (REST)", "Notification API (Email/SMS)", "Event-driven", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-DER-EN-01", "Validate application processing within 5 business days of submission", "SubmitDERApplication", "Engineering review complete within 5 business days", "High"),
                ("AC-DER-EN-02", "Confirm inspection scheduled within 3 business days of application approval", "ScheduleSiteInspection", "Inspection date offered within 72 hrs of approval", "Medium"),
                ("AC-DER-EN-03", "Verify net meter installation and activation within 5 business days of inspection pass", "ExchangeNetMeter", "Net meter activated in MDM within 5 days of inspection", "High"),
                ("AC-DER-EN-04", "Ensure DERMS enrollment completed before net meter activation date", "EnrollCustomerDERMS", "DERMS enrollment effective date aligns with meter activation", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["Billing"] = {
    "title": "Billing, CIS & Revenue Management  - `UT-CIM` `UT-RTM` `UT-BIL` `UT-PAY` `UT-REV`",
    "description": "Manages customer information, rate/tariff definitions, billing calculation and presentment, payment processing, and revenue assurance for multi-service (electric + water) utility billing.",
    "capabilities": ["UT-CIM", "UT-RTM", "UT-BIL", "UT-PAY", "UT-REV"],
    "subflows": OrderedDict([
        ("10.1", {
            "title": "Customer Information Management",
            "description": "Customer service representatives manage account creation, service orders, move-in/move-out, name changes, and account updates across electric and water services.",
            "actors": ["CSR", "Customer", "Field Service Tech"],
            "systems": ["CIS (Oracle Utilities Customer Care & Billing)", "CRM (Salesforce)", "MDM", "IVR", "Field Service Management"],
            "mermaid": [
                "Customer->>IVR: Call to start service\nmove_in=2026-07-15, address=456 Oak Ave, Electric+Water",
                "IVR->>CIS: Validate premise\naddress=456 Oak Ave, premise=PREM-002, service_class=Residential",
                "CIS->>IVR: Premise ready\nprevious occupant=Cleared, meter=MTR-002, deposit=$200",
                "CSR->>CIS: Create account\nACCT-002: name=Jane Doe, SSN=***-****-1234, deposit=$200",
                "CIS->>CRM: Create contact\ncontact=JD-001, account=ACCT-002, preference=Paperless",
                "CSR->>CIS: Set service dates\nElectric=2026-07-15, Water=2026-07-15, prorated_start=True",
                "CIS->>FSM: Create service order\nSO-2026-042, connect electric+water at PREM-002",
                "FSM->>Tech: Dispatch\nPREM-002, connect meter, read=00000, verify seal",
                "Tech->>FSM: Service connected\nMTR-002: electric=12345, water=WTR-002: 00000, both on",
                "FSM->>CIS: Order complete\nSO-2026-042: completed 2026-07-15T09:30, tech=TECH-042",
                "CIS->>MDM: Activate meter\nMTR-002: 15-min interval, MDM_effective=2026-07-15T09:30",
                "MDM->>CIS: Meter active\nMTR-002: reading=12345, service=Electric, interval=15-min",
                "Customer->>CIS: Change name\nmarriage, ACCT-002: Jane Doe to Jane Smith",
                "CSR->>CIS: Update account\nACCT-002: last_name=Doe\u2192Smith, effective=2026-07-07",
                "CIS->>Customer: Confirmation email\nname change confirmed, account=ACCT-002, ref=CHG-042",
            ],
            "integrations": [
                ("CIM", "Validation", "ValidatePremiseAddress", "IVR", "CIS (Oracle Utilities)", "IVR API (SOAP)", "CIS API (REST)", "API-led (Real-time)", "Medium"),
                ("CIM", "Account", "CreateCustomerAccount", "CSR HMI", "CIS (Oracle Utilities)", "CSR UI", "CIS API (REST)", "API-led (Real-time)", "High"),
                ("CIM", "Contact", "CreateCRMContact", "CIS (Oracle Utilities)", "CRM (Salesforce)", "CIS API (REST)", "CRM API (REST)", "API-led (Real-time)", "Simple"),
                ("CIM", "Service", "CreateServiceOrder", "CIS (Oracle Utilities)", "Field Service Management", "CIS API (REST)", "FSM API (REST)", "API-led (Real-time)", "Medium"),
                ("CIM", "Dispatch", "DispatchFieldTech", "Field Service Management", "Tech Mobile App", "FSM API (REST)", "Mobile App API (OAuth2)", "API-led (Real-time)", "Medium"),
                ("CIM", "Meter", "ActivateMeterMDM", "CIS (Oracle Utilities)", "MDM", "CIS API (REST)", "MDM API (REST)", "API-led (Real-time)", "High"),
                ("CIM", "Update", "ProcessNameChange", "CSR HMI", "CIS (Oracle Utilities)", "CSR UI", "CIS API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-CIM-01", "Validate account creation completes in under 10 minutes for walk-in/phone requests", "CreateCustomerAccount", "Account fully created and active within 10 min of request", "High"),
                ("AC-CIM-02", "Confirm service order dispatched to field within 30 minutes of creation", "CreateServiceOrder", "Service order assigned and dispatched within 30 min", "Medium"),
                ("AC-CIM-03", "Verify meter activation synchronizes between CIS and MDM within 5 minutes", "ActivateMeterMDM", "MDM reflects CIS effective date within 5 min tolerance", "High"),
                ("AC-CIM-04", "Ensure customer data updates are audited with before/after values and user identity", "ProcessNameChange", "Audit trail shows previous and new values for all changes", "Medium"),
            ],
        }),
        ("10.2", {
            "title": "Billing Calculation & Presentment",
            "description": "Billing engine calculates charges based on rate tariffs, meter data (MDM), and customer class. Bills are generated, rendered (paper/paperless), and delivered via Bill Print or e-Bill.",
            "actors": ["Billing Analyst", "Customer", "CSR"],
            "systems": ["CIS Billing Engine", "MDM", "Rate/Tariff System", "Bill Print Vendor", "Customer Portal", "ERP (SAP)"],
            "mermaid": [
                "Billing_Engine->>MDM: Pull interval data\nbilling_cycle=July 2026, meters=125K, 15-min intervals",
                "MDM->>Billing_Engine: Consumption data\nMTR-001: 850 kWh, MTR-002: 1,200 kWh, valid=99.8%",
                "Billing_Engine->>Rate_System: Get rate tariff\ncustomer_class=Residential, season=Summer, tier=Tier-2",
                "Rate_System->>Billing_Engine: Rate table\nbase=$0.12/kWh, Tier-2=$0.15/kWh, customer_charge=$8.00",
                "Billing_Engine->>Billing_Engine: Calculate charges\n850 kWh: 500@$0.12 + 350@$0.15 = $60+$52.50+$8=$120.50",
                "Billing_Engine->>Billing_Engine: Apply taxes/distribution\ntaxes=$4.50, dist_charge=$18.00, franchise=$2.00",
                "Billing_Engine->>Billing_Engine: Total calculation\nusage=$120.50 + taxes=$4.50 + dist=$18.00 + franchise=$2.00 = $145.00",
                "Billing_Engine->>ERP: Post GL entries\nrevenue=$145.00, GL=6010, cost_center=CC-NW-01",
                "ERP->>Billing_Engine: GL posted\nJE-2026-042, period=July 2026, posted=2026-07-25",
                "Billing_Engine->>Bill_Print: Generate bill PDF\nACCT-001, $145.00, due=2026-08-15, paperless=No",
                "Bill_Print->>Customer: Mail bill\nACCT-001: 123 Main St, $145.00, due=Aug 15",
                "Billing_Engine->>Portal: Post e-Bill\nACCT-001: PDF+HTML, due=2026-08-15, available=Portal",
                "Portal->>Customer: Email notification\nbill_ready, amount=$145.00, due=Aug 15, auto_pay=None",
                "Analyst->>Billing_Engine: Review exceptions\n12 accounts failed rate calc, investigate E-042 to E-053",
                "Billing_Engine->>Analyst: Exception report\n12 errors: 8 rate mismatches, 4 missing interval data",
                "CSR->>CIS: Adjust bill\nACCT-042: billing_error, correction=-$12.50, ref=ADJ-042",
            ],
            "integrations": [
                ("Billing", "Data", "PullIntervalData", "CIS Billing Engine", "MDM", "Billing API (REST)", "MDM API (REST)", "Batch (Scheduled)", "High"),
                ("Billing", "Rate", "FetchRateTariff", "CIS Billing Engine", "Rate/Tariff System", "Billing API (REST)", "Rate API (REST)", "API-led (Real-time)", "High"),
                ("Billing", "Calc", "CalculateCharges", "CIS Billing Engine", "CIS Billing Engine", "Internal", "Internal", "Batch (Scheduled)", "High"),
                ("Billing", "GL", "PostGLEntries", "CIS Billing Engine", "ERP (SAP)", "CIS API (REST)", "ERP API (SOAP/IDoc)", "Batch (Scheduled)", "High"),
                ("Billing", "Present", "GenerateBillPDF", "CIS Billing Engine", "Bill Print Vendor", "CIS API (REST)", "Print Vendor API (SFTP)", "Batch (Scheduled)", "Medium"),
                ("Billing", "Ebill", "PostElectronicBill", "CIS Billing Engine", "Customer Portal", "CIS API (REST)", "Portal API (REST)", "Batch (Scheduled)", "Medium"),
                ("Billing", "Exception", "ReviewBillingExceptions", "CIS Billing Engine", "Billing Analyst UI", "CIS API (REST)", "Analyst UI", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-BIL-01", "Validate billing calculation accuracy within \u00b10.5% of independently computed values", "CalculateCharges", "Sample audit of 1% of bills shows accuracy within 0.5%", "High"),
                ("AC-BIL-02", "Confirm bill generation completes within 4 hours for full customer base", "GenerateBillPDF", "All 125K customer bills generated and rendered within 4 hrs", "High"),
                ("AC-BIL-03", "Verify GL posting matches billing totals with zero variance", "PostGLEntries", "GL control totals match billing system month-end totals", "High"),
                ("AC-BIL-04", "Ensure billing exception rate remains under 0.5% of total accounts billed", "ReviewBillingExceptions", "Exception report shows <625 accounts (0.5% of 125K)", "Medium"),
            ],
        }),
        ("10.3", {
            "title": "Payment & Collections",
            "description": "Customers pay bills via multiple channels (web, auto-pay, walk-in, phone). Collections team manages delinquent accounts, payment plans, and disconnection/reconnection processes.",
            "actors": ["Customer", "Cashier", "Collections Specialist"],
            "systems": ["CIS (Oracle Utilities)", "Payment Gateway (CyberSource)", "Lockbox", "Collections System", "IVR"],
            "mermaid": [
                "Customer->>Portal: Pay bill online\nACCT-001, $145.00, Visa xxxx-4242, one-time",
                "Portal->>PaymentGW: Authorize payment\namount=$145.00, card_token=TK-042, cvv=validated",
                "PaymentGW->>Portal: Authorized\nauth=ABC-123, fraud_check=Pass, avs=Match",
                "Portal->>CIS: Record payment\nACCT-001, $145.00, method=Visa, ref=PAY-2026-042",
                "CIS->>Portal: Payment posted\nnew_balance=$0.00, receipt=REC-042",
                "Lockbox->>CIS: Process check batch\n42 checks, $6,200.00, batch_id=BATCH-042",
                "CIS->>Lockbox: Checks posted\n42 items posted, 0 exceptions, 1 NSF check",
                "CIS->>Collections: Flag NSF\nACCT-055: check=$200.00, NSF, fee=$35.00, due=Immediate",
                "Collector->>CIS: Review delinquency\n81 accounts >60 days, total=$45,200, 12 accounts at risk",
                "Collector->>Customer: Send notice\nACCT-055: NSF, pay $235.00 by 2026-07-15, disconnect=7/20",
                "Customer->>IVR: Payment arrangement\nACCT-055: $235.00, plan=3 monthly installments of $78.33",
                "IVR->>CIS: Create payment plan\nACCT-055: 3 payments, start=2026-07-15, arrangement_id=ARR-042",
                "Collector->>CIS: Issue disconnect\nACCT-089: 90 days delinquent, $450.00, no payment plan",
                "CIS->>Field: Disconnect order\nDO-2026-042, PREM-089, electric, lockout_ring=True",
                "Field->>CIS: Disconnect complete\nPREM-089: meter locked out, service off, tag=TAG-042",
                "Customer->>CIS: Pay reinstatement\nACCT-089: $450+$75 reconnect, card, reinstated",
            ],
            "integrations": [
                ("Payment", "Online", "ProcessOnlinePayment", "Customer Portal", "Payment Gateway (CyberSource)", "Portal API (OAuth2)", "Payment GW API (REST/SOAP)", "API-led (Real-time)", "High"),
                ("Payment", "Posting", "RecordPaymentCIS", "Customer Portal", "CIS (Oracle Utilities)", "Portal API (OAuth2)", "CIS API (REST)", "API-led (Real-time)", "High"),
                ("Payment", "Lockbox", "ProcessCheckBatch", "Lockbox", "CIS (Oracle Utilities)", "Lockbox BAI2", "CIS API (REST)", "Batch (Scheduled)", "Medium"),
                ("Payment", "NSF", "ProcessNSFCheck", "CIS (Oracle Utilities)", "Collections System", "CIS API (REST)", "Collections API (REST)", "Event-driven", "Medium"),
                ("Payment", "Plan", "CreatePaymentPlan", "IVR", "CIS (Oracle Utilities)", "IVR API (SOAP)", "CIS API (REST)", "API-led (Real-time)", "Medium"),
                ("Payment", "Disconnect", "IssueDisconnectOrder", "CIS (Oracle Utilities)", "Field Service Management", "CIS API (REST)", "FSM API (REST)", "API-led (Real-time)", "High"),
                ("Payment", "Reconnect", "ProcessReconnection", "CIS (Oracle Utilities)", "Field Service Management", "CIS API (REST)", "FSM API (REST)", "API-led (Real-time)", "High"),
            ],
            "acceptance_criteria": [
                ("AC-PAY-01", "Validate payment processing completes within 5 seconds for online payments", "ProcessOnlinePayment", "Payment authorized and receipt generated within 5s", "High"),
                ("AC-PAY-02", "Confirm lockbox check batch posts within 4 hours of batch receipt", "ProcessCheckBatch", "All checks posted within 4 hrs of batch file receipt", "Medium"),
                ("AC-PAY-03", "Verify payment plan setup processes within 2 minutes of IVR confirmation", "CreatePaymentPlan", "Payment plan active in CIS within 2 min of IVR call end", "Medium"),
                ("AC-PAY-04", "Ensure disconnect order execution within 24 hours for final notice expiry", "IssueDisconnectOrder", "Disconnect completed within 24 hrs of notice deadline", "High"),
            ],
        }),
        ("10.4", {
            "title": "Rate & Revenue Assurance",
            "description": "Revenue assurance team audits billing accuracy, detects leakage, manages write-offs, and ensures rates are correctly applied. Green Button data is provided for customer and third-party access.",
            "actors": ["Revenue Analyst", "Rate Analyst", "Compliance Officer"],
            "systems": ["CIS", "Rate/Tariff System", "Revenue Assurance System", "Green Button Platform", "ERP (SAP)"],
            "mermaid": [
                "Analyst->>RA: Run revenue assurance audit\nbilling_cycle=July 2026, sample_size=1%, 1,250 accounts",
                "RA->>CIS: Extract billing data\n125K accounts, $18.2M total billed, 1,250 sample",
                "CIS->>RA: Billing records\nACCT-001: $145.00, rate=RS-1, consumption=850 kWh",
                "RA->>RA: Audit calculations\nrate_applied=RS-1 vs expected=RS-1, tier=Tier-2, correct=Yes",
                "RA->>RA: Detect leakage\n12 accounts: wrong rate class, $4,200 uncollected, 3 unbilled",
                "RA->>Analyst: Leakage report\n15 cases: 8 rate class errors, 4 unmetered, 3 data gaps, total=$8,450",
                "Analyst->>CIS: Adjust revenue\nJE-2026-043: +$8,450 revenue correction, GL=6010",
                "Rate_Analyst->>Rate_System: Update tariff\nRS-2: increase $0.01/kWh, effective=2026-08-01, filing=PUCO-042",
                "Rate_System->>CIS: Deploy rate change\nnew_rates=RS-1, RS-2, RS-3, effective=2026-08-01T00:00",
                "Analyst->>RA: Green Button export\ncustomer=CUST-001, interval=2026-07-01 to 2026-07-31",
                "RA->>GreenButton: Request usage XML\ncustomer=CUST-001, meter=MTR-001, format=GreenButton v1.0",
                "GreenButton->>Customer: Download link\nCUST-001: 30-day interval data, XML, Authorization=Token",
                "Compliance->>RA: Review write-offs\nQ2 2026: $45K bad debt, 12 accounts, write_off=Approved",
                "RA->>CIS: Process write-offs\n12 accounts, $45,000, GL=6950 bad_debt, effective=2026-07-31",
                "Compliance->>RA: Regulatory report\nJuly 2026: $18.2M billed, 99.5% accuracy, 0.02% leakage rate",
            ],
            "integrations": [
                ("Revenue", "Audit", "RunRevenueAssuranceAudit", "Revenue Assurance Analyst", "Revenue Assurance System", "Analyst UI", "RA API (REST)", "Batch (Scheduled)", "Medium"),
                ("Revenue", "Extract", "ExtractBillingData", "Revenue Assurance System", "CIS (Oracle Utilities)", "RA API (REST)", "CIS API (REST)", "Batch (Scheduled)", "Medium"),
                ("Revenue", "Leakage", "DetectRevenueLeakage", "Revenue Assurance System", "Revenue Assurance System", "Internal", "Internal", "Batch (Scheduled)", "High"),
                ("Revenue", "Tariff", "DeployRateChange", "Rate/Tariff System", "CIS (Oracle Utilities)", "Rate API (REST)", "CIS API (REST)", "API-led (Real-time)", "High"),
                ("Revenue", "GreenButton", "ExportGreenButtonXML", "Revenue Assurance System", "Green Button Platform", "RA API (REST)", "Green Button API (REST)", "API-led (Real-time)", "Medium"),
                ("Revenue", "WriteOff", "ProcessWriteOffs", "Revenue Assurance System", "CIS (Oracle Utilities)", "RA API (REST)", "CIS API (REST)", "Batch (Scheduled)", "Medium"),
                ("Revenue", "Report", "GenerateRegulatoryReport", "Revenue Assurance System", "Compliance Officer", "RA API (REST)", "Compliance UI", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-REV-01", "Validate revenue assurance audit covers minimum 1% of accounts or 100% of high-risk", "RunRevenueAssuranceAudit", "Audit sample size meets minimum threshold per utility policy", "High"),
                ("AC-REV-02", "Confirm revenue leakage detection identifies rate class errors, unmetered accounts, and data gaps", "DetectRevenueLeakage", "Leakage report includes all 3 categories with dollar impact", "High"),
                ("AC-REV-03", "Verify rate change deployment completes before effective date with zero billing interruption", "DeployRateChange", "All accounts billed using new rates effective 2026-08-01", "Medium"),
                ("AC-REV-04", "Ensure Green Button data export includes all interval data with proper XML schema validation", "ExportGreenButtonXML", "Green Button XML passes NAESB schema validation", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["OutageManagement"] = {
    "title": "Outage & Workforce Management  - `UT-ODI` `UT-DAS` `UT-CDR` `UT-OAR`",
    "description": "End-to-end outage management from detection (AMI, SCADA, IVR), damage assessment, crew dispatch, restoration tracking, and post-event analytics including SAIDI/SAIFI calculations.",
    "capabilities": ["UT-ODI", "UT-DAS", "UT-CDR", "UT-OAR"],
    "subflows": OrderedDict([
        ("11.1", {
            "title": "Outage Detection & IVR",
            "description": "Outages are detected via AMI last gasp, SCADA breaker status, and customer calls. IVR system handles high call volumes, correlates with known outages, and updates OMS.",
            "actors": ["Call Center Agent", "Customer", "Outage Analyst"],
            "systems": ["IVR", "OMS (Oracle Utilities)", "AMI Head-End", "SCADA", "Outage Notification System"],
            "mermaid": [
                "AMI->>OMS: Last gasp alert\nMTR-001 to MTR-050: 50 meters offline, timestamp=14:23:01",
                "SCADA->>OMS: Breaker alarm\nFDR-MAIN-001: overcurrent trip, 4.2 kA, phase=AG",
                "OMS->>OMS: Correlate events\nAMI last gasp + SCADA trip = confirmed outage, FDR-MAIN-001",
                "OMS->>IVR: Update IVR status\nSpringfield NW, 850 customers affected, ETA=Unknown",
                "Customer->>IVR: Call to report outage\nACCT-001: no power, premise=PREM-001, electric",
                "IVR->>OMS: Check premise outage\nPREM-001: within FDR-MAIN-001 outage polygon, 850 affected",
                "OMS->>IVR: Premise in outage\nknown_outage=OUT-2026-042, ETA=2 hrs, cause=Under investigation",
                "IVR->>Customer: Automated response\noutage confirmed, 850 affected, ETA 2 hrs, SMS updates",
                "IVR->>OMS: Log customer call\nACCT-001, source=IVR, timestamp=14:25:12, callback=True",
                "OMS->>IVR: Update IVR stats\n1,250 calls received, 850 unique, 92% IVR containment",
                "IVR->>Agent: Escalate high-priority call\ncustomer=VIP-001, medical_equipment=Yes, 300 customers",
                "Agent->>OMS: Customer notes\nVIP-001, medical baseline, critical care, need generator",
                "OMS->>Agent: Priority updated\nCUST-001: medical_priority=True, notification=Generator deployed",
                "OMS->>Notification: Send alerts\n850 customers: SMS+email, ETA=2 hrs, cause=Faulted line",
                "OMS->>OMS: Update metrics\ncustomers_out=850, SAIFI_impact=0.02, detect_time=2 min",
                "Analyst->>OMS: Review detection summary\nAMI last gasp + SCADA trip: detected in 2 min, 1,250 calls in 15 min",
            ],
            "integrations": [
                ("ODI", "AMILastGasp", "ProcessLastGaspAlert", "AMI Head-End", "OMS (Oracle Utilities)", "AMI API (REST)", "OMS API (REST)", "Event-driven", "High"),
                ("ODI", "SCADATrip", "ProcessBreakerTrip", "SCADA", "OMS (Oracle Utilities)", "SCADA API (ICCP)", "OMS API (REST)", "Event-driven", "High"),
                ("ODI", "Correlation", "CorrelateOutageEvents", "OMS (Oracle Utilities)", "OMS (Oracle Utilities)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("ODI", "IVR", "UpdateIVROutageStatus", "OMS (OracleUtilities)", "IVR", "OMS API (REST)", "IVR API (SOAP)", "Event-driven", "Medium"),
                ("ODI", "Customer", "LogCustomerOutageCall", "IVR", "OMS (Oracle Utilities)", "IVR API (SOAP)", "OMS API (REST)", "API-led (Real-time)", "Medium"),
                ("ODI", "Notification", "SendOutageNotifications", "OMS (Oracle Utilities)", "Outage Notification System", "OMS API (REST)", "Notification API (Email/SMS)", "Event-driven", "Medium"),
                ("ODI", "Priority", "UpdateMedicalPriority", "Call Center Agent", "OMS (Oracle Utilities)", "Agent HMI", "OMS API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-ODI-01", "Validate outage detection time under 5 minutes from AMI last gasp or SCADA trip", "ProcessLastGaspAlert", "OMS outage event created within 5 min of first alert", "High"),
                ("AC-ODI-02", "Confirm IVR containment rate exceeds 85% of total outage calls", "UpdateIVROutageStatus", ">85% of calls resolved without agent escalation", "Medium"),
                ("AC-ODI-03", "Verify call-logging timestamp accuracy within \u00b11 second of customer call arrival", "LogCustomerOutageCall", "OMS call log timestamp matches ACD timestamp within 1s", "Medium"),
                ("AC-ODI-04", "Ensure outage notifications reach 100% of affected customers within 15 minutes", "SendOutageNotifications", "SMS delivery receipt for all customers within 15 min", "High"),
            ],
        }),
        ("11.2", {
            "title": "Damage Assessment & Switching",
            "description": "After outage detection, system operator performs damage assessment via field reports, SCADA status, and GIS analysis. Switching orders isolate faulted sections and reconfigure the network.",
            "actors": ["System Operator", "Field Supervisor", "Damage Assessor"],
            "systems": ["OMS", "SCADA", "GIS (ArcGIS)", "Switching Order Management", "Mobile Crew App"],
            "mermaid": [
                "Operator->>OMS: Review outage scope\nOUT-2026-042: FDR-MAIN-001, 850 out, cause=Faulted line",
                "Operator->>SCADA: Check breaker status\nFDR-MAIN-001: trip=Open, recloser=RCL-001: lockout",
                "SCADA->>Operator: Status update\nBRK-MAIN-001: Open, RCL-001: Lockout, 4.2 kA fault",
                "Operator->>GIS: Analyze fault area\nFDR-MAIN-001: pole #47-#52, feeder section 3, overhead",
                "GIS->>Operator: Network view\nsection 3: 150 customers, fault between FCIs #7 and #8",
                "Operator->>Field_Sup: Dispatch assessment\nsection 3, pole #47-#52, suspected downed conductor",
                "Field_Sup->>OMS: En route\nETA=10 min, crew=C-ALPHA, vehicle=V-042",
                "Field_Sup->>Operator: Damage report\npole #48: broken crossarm, conductor down, energized ground",
                "Operator->>Switching: Create switching order\nSWO-2026-043: isolate section 3, 5 switching steps",
                "Switching->>SCADA: Execute isolation\nopen SW-047, open SW-048, confirm de-energized",
                "SCADA->>Switching: Section isolated\nSW-047=Open, SW-048=Open, section 3: 0 kV, 0 A",
                "Operator->>OMS: Update outage\nsection 3 isolated: 150 out, section 1-2 and 5-6 normal",
                "Switching->>SCADA: Close tie switch\nSW-TIE: close, backfeed FDR-BACKUP-001",
                "SCADA->>Switching: Tie closed\nSW-TIE=Closed, sections 1-2 and 5-6 restored via backfeed",
                "Operator->>OMS: Update customer count\n150 customers out (section 3), 700 restored",
                "Operator->>OMS: Log action\nswitching order SWO-2026-043, isolation complete, repair pending",
            ],
            "integrations": [
                ("DAS", "Scope", "ReviewOutageScope", "System Operator HMI", "OMS (Oracle Utilities)", "Operator UI", "OMS API (REST)", "API-led (Real-time)", "Simple"),
                ("DAS", "Status", "CheckBreakerStatus", "System Operator HMI", "SCADA", "Operator UI", "SCADA API (ICCP)", "API-led (Real-time)", "Medium"),
                ("DAS", "GIS", "AnalyzeFaultArea", "System Operator HMI", "GIS (ArcGIS)", "Operator UI", "GIS API (REST)", "API-led (Real-time)", "Medium"),
                ("DAS", "Assessment", "DispatchDamageAssessment", "OMS (Oracle Utilities)", "Mobile Crew App", "OMS API (REST)", "Mobile App API (OAuth2)", "API-led (Real-time)", "Medium"),
                ("DAS", "Switching", "CreateSwitchingOrder", "System Operator HMI", "Switching Order Management", "Operator UI", "Switching API (REST)", "API-led (Real-time)", "High"),
                ("DAS", "Isolate", "ExecuteSwitchingIsolation", "Switching Order Management", "SCADA", "Switching API (REST)", "SCADA DNP3", "API-led (Real-time)", "High"),
                ("DAS", "Restore", "CloseTieSwitchRestore", "Switching Order Management", "SCADA", "Switching API (REST)", "SCADA DNP3", "API-led (Real-time)", "High"),
            ],
            "acceptance_criteria": [
                ("AC-DAS-01", "Validate damage assessment dispatched within 15 minutes of outage confirmation", "DispatchDamageAssessment", "Field crew dispatched within 15 min of outage creation", "High"),
                ("AC-DAS-02", "Confirm switching order creation includes engineer-approved isolation sequence", "CreateSwitchingOrder", "Switching order reviewed and approved by system operator", "High"),
                ("AC-DAS-03", "Verify isolation switching completes within 30 minutes of switching order approval", "ExecuteSwitchingIsolation", "All switches operated and confirmed within 30 min", "High"),
                ("AC-DAS-04", "Ensure backfeed restoration does not exceed tie switch ampacity rating", "CloseTieSwitchRestore", "Post-restoration loading <90% of tie switch rating", "Medium"),
            ],
        }),
        ("11.3", {
            "title": "Crew Dispatch & Restoration",
            "description": "Crews are dispatched based on location, skillset, and priority. Mobile workforce management tracks ETA, work progress, and materials used. Supervisors coordinate restoration activities.",
            "actors": ["Dispatch Supervisor", "Field Crew", "Warehouse Clerk"],
            "systems": ["WFM (Mobile Workforce)", "OMS", "GIS", "CMMS (Maximo)", "Inventory System", "AVL/GPS"],
            "mermaid": [
                "OMS->>WFM: Create restoration order\nOUT-2026-042, section 3, pole #48: replace crossarm+conductor",
                "WFM->>WFM: Assign crew\nC-ALPHA: lineman (3), groundman (2), bucket truck (1)",
                "WFM->>Crew: Dispatch instruction\npole #48, crossarm=CA-12ft, conductor=ACSR-336, ETA=10 min",
                "Crew->>WFM: En route\nGPS=lat:39.74, lon:-89.49, ETA=10 min, traffic=Normal",
                "WFM->>Supervisor: Track ETA\nC-ALPHA: 8 min, C-BRAVO: 15 min, C-CHARLIE: 25 min",
                "Crew->>WFM: Arrived\nGPS=pole #48, site_safe=Yes, traffic_control=Setup",
                "Crew->>CMMS: Check materials\ncrossarm=CA-12ft: stock=5, conductor=ACSR-336: 500 ft",
                "CMMS->>Crew: Materials available\ncrossarm=5 in stock, conductor=500 ft, insulators=12",
                "Crew->>CMMS: Request material\ncrossarm=CA-12ft qty=1, ACSR-336 qty=50 ft, insulators=4",
                "CMMS->>Inventory: Reserve material\nreservation=RES-042, warehouse=WH-NW, picklist=PL-042",
                "Warehouse->>Crew: Materials issued\ncrossarm=CA-12ft qty=1, ACSR-336 qty=50 ft, issued=2026-07-07T15:30",
                "Crew->>WFM: Work started\nreplace crossarm and conductor, pole #48, ETA completion=90 min",
                "Crew->>WFM: Work complete\ncrossarm=Replaced, conductor=Replaced, grounds=Removed, test=Passed",
                "Crew->>OMS: Ready for restore\nsection 3: repaired, clearance=Removed, tags=Retired, ready=Yes",
                "WFM->>OMS: Update status\nC-ALPHA: complete at 16:45, materials used=$850, hours=1.25",
                "Operator->>SCADA: Close switches\nSW-047=Close, SW-048=Close, section 3 re-energized",
                "OMS->>WFM: Close restoration order\nOUT-2026-042: all customers restored, outage_duration=2.5 hrs",
                "Crew->>WFM: End shift report\nC-ALPHA: restoration complete, 2 OT hrs, truck=V-042 returned",
            ],
            "integrations": [
                ("CDR", "Order", "CreateRestorationOrder", "OMS (Oracle Utilities)", "WFM (Mobile Workforce)", "OMS API (REST)", "WFM API (REST)", "Event-driven", "High"),
                ("CDR", "Dispatch", "AssignCrewToJob", "WFM (Mobile Workforce)", "Mobile Crew App", "WFM API (REST)", "Mobile App API (OAuth2)", "API-led (Real-time)", "High"),
                ("CDR", "Tracking", "TrackCrewETA", "Mobile Crew App (GPS)", "WFM (Mobile Workforce)", "Mobile GPS (AVL)", "WFM API (REST)", "API-led (Real-time)", "Medium"),
                ("CDR", "Materials", "CheckMaterialAvailability", "Mobile Crew App", "CMMS (Maximo)", "Mobile App API (OAuth2)", "CMMS API (REST)", "API-led (Real-time)", "Medium"),
                ("CDR", "Inventory", "ReserveAndIssueMaterial", "CMMS (Maximo)", "Inventory System", "CMMS API (REST)", "Inventory API (REST)", "API-led (Real-time)", "Medium"),
                ("CDR", "Restore", "NotifyRestorationReady", "Mobile Crew App", "OMS (Oracle Utilities)", "Mobile App API (OAuth2)", "OMS API (REST)", "API-led (Real-time)", "High"),
                ("CDR", "Report", "CloseRestorationOrder", "OMS (OracleUtilities)", "WFM (Mobile Workforce)", "OMS API (REST)", "WFM API (REST)", "Event-driven", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-CDR-01", "Validate crew dispatch within 5 minutes of restoration order creation", "AssignCrewToJob", "Crew assigned and notified within 5 min of order creation", "High"),
                ("AC-CDR-02", "Confirm GPS location accuracy within 10 meters for crew ETA calculation", "TrackCrewETA", "AVL GPS coordinates accurate within 10m of actual location", "Medium"),
                ("AC-CDR-03", "Verify material availability check completes within 60 seconds of mobile request", "CheckMaterialAvailability", "CMMS responds with stock status within 60s", "Medium"),
                ("AC-CDR-04", "Ensure restoration order is closed within 30 minutes of all customers restored", "CloseRestorationOrder", "OMS and WFM synchronized within 30 min of full restoration", "High"),
            ],
        }),
        ("11.4", {
            "title": "Outage Analytics & Reporting",
            "description": "Post-event analysis calculates reliability metrics (SAIDI, SAIFI, CAIDI), identifies root causes, and generates regulatory reports. Trends are analyzed for system improvement planning.",
            "actors": ["Reliability Engineer", "Compliance Manager", "Planning Engineer"],
            "systems": ["OMS", "Analytics Platform", "Compliance Reporting", "GIS", "Regulatory Portal"],
            "mermaid": [
                "OMS->>Analytics: Export outage data\nYTD 2026: 142 outages, 45,000 customer-minutes, 15,000 customers affected",
                "Analytics->>Analytics: Calculate SAIDI\nSAIDI = 45,000 / 100,000 = 0.45 min (YTD), target=0.60",
                "Analytics->>Analytics: Calculate SAIFI\nSAIFI = 15,000 / 100,000 = 0.15 events (YTD), target=0.20",
                "Analytics->>Analytics: Calculate CAIDI\nCAIDI = 45,000 / 15,000 = 3.0 min, target=4.0 min",
                "Analytics->>Engineer: Reliability report\nSAIDI=0.45, SAIFI=0.15, CAIDI=3.0, all within targets",
                "Analytics->>Engineer: Root cause analysis\n40% weather, 25% equipment failure, 15% vegetation, 10% animal, 10% other",
                "Engineer->>Analytics: Drill down equip failures\n12 transformer failures: 8 overload, 4 lightning, avg age=22 yr",
                "Analytics->>Engineer: GIS overlay\nfaults clustered in NW district: aging transformers, tree conflicts",
                "Engineer->>GIS: Export outage map\n142 outage locations, classify by cause, equipment age=0-50 yr",
                "GIS->>Analytics: Spatial analysis\nNW district: outage density=3.2/sq mi vs city avg=1.8/sq mi",
                "Engineer->>Planning: Capital plan recommendation\nNW district: replace 12 transformers, $240K, priority=High",
                "Analytics->>Compliance: Regulatory report Q2\nSAIDI=0.45, SAIFI=0.15, report format=PUC-required",
                "Compliance->>Reg_Portal: Submit report\nQ2 2026 reliability, data complete, certification=Attached",
                "Reg_Portal->>Compliance: Submission confirmed\nreceived=2026-07-07T16:00, ref=REG-2026-Q2-042",
                "Engineer->>Analytics: Trend analysis\n2019: SAIDI=0.82, 2020: 0.75, 2021: 0.68, 2022: 0.60, 2023: 0.55, 2024: 0.50, 2025: 0.48, 2026: 0.45",
            ],
            "integrations": [
                ("OAR", "Data", "ExportOutageData", "OMS (Oracle Utilities)", "Analytics Platform", "OMS API (REST)", "Analytics API (REST)", "Batch (Scheduled)", "Medium"),
                ("OAR", "Metrics", "CalculateReliabilityMetrics", "Analytics Platform", "Analytics Platform", "Internal", "Internal", "Batch (Scheduled)", "High"),
                ("OAR", "RootCause", "AnalyzeRootCause", "Analytics Platform", "Reliability Engineer", "Analytics API (REST)", "Engineer UI", "Batch (Scheduled)", "Medium"),
                ("OAR", "Spatial", "ExportOutageGISMap", "GIS (ArcGIS)", "Analytics Platform", "GIS API (REST)", "Analytics API (REST)", "Batch (Scheduled)", "Simple"),
                ("OAR", "Plan", "UpdateCapitalPlan", "Reliability Engineer", "Planning System", "Engineer UI", "Planning API (REST)", "API-led (Real-time)", "Simple"),
                ("OAR", "Compliance", "GenerateRegulatoryReport", "Analytics Platform", "Compliance Reporting", "Analytics API (REST)", "Compliance API (REST)", "Batch (Scheduled)", "High"),
                ("OAR", "Submit", "SubmitToRegulatoryPortal", "Compliance Manager", "Regulatory Portal", "Compliance UI", "Reg Portal API (REST/SOAP)", "Batch (Scheduled)", "High"),
            ],
            "acceptance_criteria": [
                ("AC-OAR-01", "Validate SAIDI/SAIFI/CAIDI calculations match IEEE 1366 standard methodology", "CalculateReliabilityMetrics", "Metrics recalculated independently, match within 0.1%", "High"),
                ("AC-OAR-02", "Confirm root cause analysis categorizes 100% of outages with plausible cause", "AnalyzeRootCause", "All outages assigned cause code with <1% unknown category", "Medium"),
                ("AC-OAR-03", "Verify regulatory report submitted within filing deadline (30 days post-quarter)", "SubmitToRegulatoryPortal", "Regulatory portal confirms receipt before filing deadline", "High"),
                ("AC-OAR-04", "Ensure trend analysis includes minimum 5-year historical comparison", "ExportOutageData", "Trend report shows 5+ years of annual SAIDI/SAIFI values", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["AssetManagement"] = {
    "title": "Asset Management & GIS  - `UT-ARH` `UT-GIS` `UT-CMI` `UT-PMC`",
    "description": "Comprehensive asset management covering asset registry, GIS network model, IoT condition monitoring, and predictive maintenance for electrical and water infrastructure assets.",
    "capabilities": ["UT-ARH", "UT-GIS", "UT-CMI", "UT-PMC"],
    "subflows": OrderedDict([
        ("12.1", {
            "title": "Asset Registry & Hierarchy",
            "description": "Asset management team maintains the asset register with criticality ratings, lifecycle status, and hierarchical relationships (plant\u2192system\u2192equipment\u2192component).",
            "actors": ["Asset Manager", "Engineer", "Field Data Collector"],
            "systems": ["EAM (IBM Maximo)", "GIS (ArcGIS)", "Mobile Field App", "ERP (SAP)"],
            "mermaid": [
                "Collector->>Mobile: Scan asset barcode\nTX-001: transformer, serial=SER-042, manufacturer=ABB",
                "Mobile->>EAM: Create asset record\ntype=Transformer, subtype=Padmount, kVA=500, voltage=12.47 kV",
                "EAM->>EAM: Build hierarchy\nplant=SUB-MAIN-001, system=12kV_FDR, equipment=TX-001, component=TapChanger",
                "EAM->>Engineer: Criticality assessment\nTX-001: load=85%, customers=450, criticality=High (4.5/5)",
                "Engineer->>EAM: Set criticality\nTX-001: criticality=High, score=4.5, health_index=85, risk=Medium",
                "EAM->>Engineer: Lifecycle status\nTX-001: install_date=2010, expected_life=30 yr, remaining=14 yr",
                "Engineer->>EAM: Update status\nTX-001: lifecycle=Active, condition=Good, next_maintenance=2027-01-15",
                "EAM->>GIS: Sync asset location\nTX-001: lat=39.74, lon=-89.49, premise=PREM-001, feeder=FDR-MAIN-001",
                "GIS->>EAM: Location confirmed\nTX-001: mapped in GIS network, xy_accuracy=1m",
                "EAM->>ERP: Capitalize asset\nTX-001: replacement_cost=$45,000, installed=$38,000, deprec=straight-line",
                "ERP->>EAM: Asset capitalized\nTX-001: asset_num=AST-001, capital_gl=1500, depreciation=$1,267/yr",
                "Collector->>Mobile: Field verification\nTX-001: GPS=39.7401,-89.4902, photo=attached, rfid=read",
                "Mobile->>EAM: Verification update\nTX-001: location_verified=2026-07-07, rfid_installed=True",
                "EAM->>Manager: Asset registry report\n12,450 assets registered, 98% GIS-mapped, 85% condition assessed",
                "Manager->>EAM: Review registry\nTX-001 to TX-150: all critical, 3 assets missing location data",
            ],
            "integrations": [
                ("ARH", "Create", "CreateAssetRecord", "Mobile Field App", "EAM (IBM Maximo)", "Mobile App API (OAuth2)", "EAM API (REST)", "API-led (Real-time)", "Medium"),
                ("ARH", "Hierarchy", "BuildAssetHierarchy", "EAM (IBM Maximo)", "EAM (IBM Maximo)", "Internal", "Internal", "Batch (Real-time)", "Medium"),
                ("ARH", "Criticality", "AssessAssetCriticality", "Engineer HMI", "EAM (IBM Maximo)", "Engineer UI", "EAM API (REST)", "API-led (Real-time)", "Medium"),
                ("ARH", "GIS", "SyncAssetToGIS", "EAM (IBM Maximo)", "GIS (ArcGIS)", "EAM API (REST)", "GIS API (REST)", "API-led (Real-time)", "Medium"),
                ("ARH", "Financial", "CapitalizeAssetERP", "EAM (IBM Maximo)", "ERP (SAP)", "EAM API (REST)", "ERP API (SOAP/IDoc)", "Batch (Scheduled)", "High"),
                ("ARH", "Field", "VerifyAssetLocation", "Mobile Field App", "EAM (IBM Maximo)", "Mobile App API (OAuth2)", "EAM API (REST)", "API-led (Real-time)", "Medium"),
                ("ARH", "Report", "GenerateAssetRegistryReport", "EAM (IBM Maximo)", "Asset Manager UI", "EAM API (REST)", "Manager UI", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-ARH-01", "Validate asset hierarchy completeness (100% of physical assets in registry)", "BuildAssetHierarchy", "All field-verified assets have hierarchy parent-child relationships", "High"),
                ("AC-ARH-02", "Confirm GIS synchronization accuracy within 1 meter for all mapped assets", "SyncAssetToGIS", "Asset GPS coordinates match GIS location within 1m", "Medium"),
                ("AC-ARH-03", "Verify asset capitalization in ERP within 30 days of installation", "CapitalizeAssetERP", "ERP depreciation starts within 30 days of in-service date", "High"),
                ("AC-ARH-04", "Ensure field verification cycle covers 100% of critical assets annually", "VerifyAssetLocation", "100% of critical assets verified within calendar year", "Medium"),
            ],
        }),
        ("12.2", {
            "title": "GIS Network Model",
            "description": "GIS team manages the network model for electric (primary/secondary, substations, feeders, transformers) and water (mains, hydrants, valves, meters) distribution systems.",
            "actors": ["GIS Analyst", "Network Modeler", "Field Surveyor"],
            "systems": ["GIS (ArcGIS Utility Network)", "EAM (Maximo)", "SCADA", "OMS", "Mobile Data Collector"],
            "mermaid": [
                "Surveyor->>Mobile: Collect field data\npole #47: GPS=39.7401,-89.4901, conductor=ACSR-336, condition=Good",
                "Mobile->>GIS: Upload survey\ntype=OverheadPole, asset_id=POLE-047, attributes=37 fields",
                "GIS->>GIS: Update network model\npole #47: feeder=FDR-MAIN-001, section=3, span=d47-d48",
                "GIS->>GIS: Topology check\nconductivity=OK, connectivity=pole #46-#47-#48, voltage=12.47 kV",
                "Analyst->>GIS: Add new asset\nTX-NEW-001: padmount 500 kVA, lat=39.75, lon=-89.48, feeder=FDR-MAIN-002",
                "GIS->>GIS: Validate placement\ntransformer within service territory, feeder capacity=65%, OK",
                "GIS->>EAM: Create asset\nTX-NEW-001: in_service=2026-07-07, criticality=Medium (3.0/5)",
                "EAM->>GIS: Asset synced\nTX-NEW-001: EAM_id=AST-002, lifecycle=Active, warranty=10 yr",
                "Analyst->>GIS: Trace feeder\nFDR-MAIN-001: source=SUB-MAIN-001, 12.47 kV, 45 poles, 12 tx, 850 cust",
                "GIS->>Analyst: Upstream trace\nSUB-MAIN-001: 138/12.47 kV, 25 MVA, TX-001 to TX-050",
                "Analyst->>OMS: Update network model\nFDR-MAIN-001: new pole #47a, switched section 3, effective=now",
                "OMS->>GIS: Model confirmed\nFDR-MAIN-001 topology matches GIS, 850 customers mapped correctly",
                "Analyst->>GIS: Validate connectivity\nall 45 poles connected, 12 transformers, 850 service points",
                "GIS->>Analyst: Network report\nelectric: 45 feeders, 8,500 poles, 2,100 tx, 45,000 service points",
                "Analyst->>GIS: Publish network\nversion=2026-07-07, active_model=True, validated=True",
                "Analyst->>SCADA: Export network model\nFDR-MAIN-001 to FDR-050: node-breaker, for ADMS topology",
            ],
            "integrations": [
                ("GIS", "Survey", "UploadFieldSurvey", "Mobile Data Collector", "GIS (ArcGIS Utility Network)", "Mobile App API (OAuth2)", "GIS API (REST)", "API-led (Real-time)", "Medium"),
                ("GIS", "Topology", "ValidateNetworkTopology", "GIS (ArcGIS Utility Network)", "GIS (ArcGIS Utility Network)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("GIS", "Asset", "CreateGISAsset", "GIS (ArcGIS Utility Network)", "EAM (IBM Maximo)", "GIS API (REST)", "EAM API (REST)", "API-led (Real-time)", "Medium"),
                ("GIS", "Trace", "TraceFeederSource", "GIS Analyst HMI", "GIS (ArcGIS Utility Network)", "Analyst UI", "GIS API (REST)", "API-led (Real-time)", "Simple"),
                ("GIS", "OMS", "ExportNetworkToOMS", "GIS (ArcGIS Utility Network)", "OMS", "GIS API (REST)", "OMS API (REST)", "Batch (Scheduled)", "Medium"),
                ("GIS", "SCADA", "ExportNetworkToSCADA", "GIS (ArcGIS Utility Network)", "SCADA", "GIS API (REST)", "SCADA API (ICCP)", "Batch (Scheduled)", "Medium"),
                ("GIS", "Report", "GenerateNetworkReport", "GIS (ArcGIS Utility Network)", "GIS Analyst HMI", "GIS API (REST)", "Analyst UI", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-GIS-01", "Validate GIS network connectivity (100% of assets have valid parent-child topology)", "ValidateNetworkTopology", "Topology check passes for all network features with 0 errors", "High"),
                ("AC-GIS-02", "Confirm field survey data integrated into GIS within 24 hours of collection", "UploadFieldSurvey", "Survey data available in GIS within 24 hrs of field upload", "Medium"),
                ("AC-GIS-03", "Verify feeder trace returns complete upstream path from any service point to source", "TraceFeederSource", "Trace returns all intermediate nodes from service point to substation", "Medium"),
                ("AC-GIS-04", "Ensure OMS network model reflects GIS changes within 1 hour of GIS publish", "ExportNetworkToOMS", "OMS topology matches GIS within 1 hr of publication", "High"),
            ],
        }),
        ("12.3", {
            "title": "IoT Condition Monitoring",
            "description": "IoT sensors monitor asset condition in real-time: transformer temperature, dissolved gas, partial discharge, pole tilt, pipe corrosion, and pump vibration.",
            "actors": ["Condition Monitoring Engineer", "Asset Manager", "Field Technician"],
            "systems": ["IoT Platform (C3 AI / AWS IoT)", "EAM (Maximo)", "SCADA", "Sensor Network", "Analytics Platform"],
            "mermaid": [
                "Sensor->>IoT: Publish reading\nTX-001: oil_temp=95\u00b0C, ambient=35\u00b0C, load=85%, interval=5 min",
                "Sensor->>IoT: Publish reading\nTX-001: DGA=H2=50ppm, C2H2=2ppm, CO=150ppm, CO2=800ppm",
                "Sensor->>IoT: Publish reading\nTX-001: PD=pulse=250pC, phase=45\u00b0, frequency=ultrasonic",
                "IoT->>IoT: Aggregate telemetry\nTX-001: 3 sensors, 12 metrics, 5-min window, quality=Good",
                "IoT->>Analytics: Stream condition data\nTX-001: load=85%, oil_temp=95\u00b0C, DGA=normal, PD=moderate",
                "Analytics->>Analytics: Trend analysis\noil_temp: 85\u219295\u00b0C over 6 hrs, rate=+1.67\u00b0C/hr, threshold=105\u00b0C",
                "Analytics->>Engineer: Oil temp alert\nTX-001: 95\u00b0C, rate=+1.67\u00b0C/hr, forecast=105\u00b0C in 6 hrs",
                "Engineer->>IoT: Request DGA details\nTX-001: gas_chromatograph, full DGA panel + moisture",
                "IoT->>Engineer: DGA report\nH2=50ppm (normal), C2H2=2ppm (trace), moisture=12ppm (normal)",
                "Analytics->>Analytics: Calculate health index\nTX-001: health_index=78/100, trend=declining (-2/yr), remaining_life=12 yr",
                "Analytics->>Engineer: Health index alert\nTX-001: HI=78, amber zone, recommend: oil_sample + thermography",
                "Engineer->>EAM: Create work order\nTX-001: oil_sample+thermography, priority=Medium, by=2026-07-21",
                "EAM->>IoT: Schedule inspection\nWO-2026-042, sensor=TX-001, type=OilSample, due=2026-07-14",
                "Tech->>IoT: Field reading\noil_temp=94\u00b0C, IR=cooling_fans=1 failed, fan_1=0 RPM, fan_2=1750 RPM",
                "IoT->>Analytics: Update model\nfan_1 failed, expected: oil_temp decrease 5\u00b0C after fan repair",
                "Analytics->>Engineer: Recommendation\nreplace cooling fan FAN-001, priority=High, avoid overload by July 15",
            ],
            "integrations": [
                ("CMI", "Sensor", "PublishSensorReading", "Sensor (IoT)", "IoT Platform (C3 AI / AWS IoT)", "MQTT (JSON)", "IoT API (MQTT/HTTP)", "API-led (Real-time)", "High"),
                ("CMI", "DGA", "PublishDGAData", "DGA Monitor", "IoT Platform (C3 AI / AWS IoT)", "DGA Serial (Modbus)", "IoT API (MQTT/HTTP)", "API-led (Real-time)", "High"),
                ("CMI", "PD", "PublishPartialDischarge", "PD Sensor (HVPD)", "IoT Platform (C3 AI / AWS IoT)", "PD Sensor (IEC 61850)", "IoT API (MQTT/HTTP)", "API-led (Real-time)", "High"),
                ("CMI", "Analytics", "StreamConditionData", "IoT Platform (C3 AI / AWS IoT)", "Analytics Platform", "IoT API (REST)", "Analytics API (REST)", "API-led (Real-time)", "Medium"),
                ("CMI", "Alert", "GenerateConditionAlert", "Analytics Platform", "Condition Monitoring Engineer", "Analytics API (REST)", "Engineer HMI", "Event-driven", "Medium"),
                ("CMI", "WorkOrder", "CreateInspectionWorkOrder", "Condition Monitoring Engineer", "EAM (IBM Maximo)", "Engineer UI", "EAM API (REST)", "API-led (Real-time)", "Medium"),
                ("CMI", "Field", "LogFieldInspectionData", "Field Technician (Mobile)", "IoT Platform (C3 AI / AWS IoT)", "Mobile App API (OAuth2)", "IoT API (REST)", "API-led (Real-time)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-CMI-01", "Validate sensor data latency under 60 seconds from sensor to IoT platform", "PublishSensorReading", "IoT platform timestamp within 60s of sensor reading timestamp", "High"),
                ("AC-CMI-02", "Confirm DGA analysis identifies fault gases (H2, C2H2, CO, CO2, C2H4, CH4) within 24 hours", "PublishDGAData", "Full DGA panel reported with IEEE C57.104 interpretation", "High"),
                ("AC-CMI-03", "Verify health index calculation uses at least 3 condition parameters", "CalculateHealthIndex", "Health index weighted: DGA (30%), PD (25%), oil_temp (25%), load (20%)", "Medium"),
                ("AC-CMI-04", "Ensure alert-to-work-order creation completes within 1 hour of condition threshold breach", "GenerateConditionAlert", "Work order created in EAM within 1 hr of analytics alert", "Medium"),
            ],
        }),
        ("12.4", {
            "title": "Predictive Maintenance & CBM",
            "description": "Using condition data and AI models, the utility predicts asset failures, calculates remaining useful life (RUL), and optimizes maintenance schedules to transition from time-based to condition-based maintenance.",
            "actors": ["Reliability Engineer", "Asset Manager", "Maintenance Planner"],
            "systems": ["EAM (Maximo)", "Analytics Platform (SAS / Azure ML)", "IoT Platform", "SCADA Historian", "CMMS"],
            "mermaid": [
                "Analytics->>Analytics: Train RUL model\nalgorithm=Random Survival Forest, features=12 condition metrics, target=Failure",
                "Analytics->>IoT: Request training data\nTX-001 to TX-500: 5 years DGA, PD, temp, load, maintenance_history",
                "IoT->>Analytics: Historical data\n500 transformers, 5 yr, 3M records, 12 features, 45 failure events",
                "Analytics->>Analytics: Build failure model\nfeature_importance: DGA_H2=0.35, PD=0.25, oil_temp=0.20, load=0.20",
                "Analytics->>Analytics: Validate model\naccuracy=87%, precision=82%, recall=79%, F1=0.80, AUC=0.91",
                "Analytics->>IoT: Deploy inference model\nmodel_id=MDL-001, version=1.0, endpoint=RUL-inference/v1",
                "IoT->>Analytics: Live inference\nTX-001: RUL=3.2 yr, failure_prob=12% in 12 mo, confidence=85%",
                "IoT->>Analytics: Live inference\nTX-050: RUL=0.8 yr, failure_prob=45% in 12 mo, confidence=78%",
                "Analytics->>Engineer: RUL dashboard\nTX-050: critical (RUL<1 yr), TX-001: monitor (RUL 1-5 yr), 450: normal",
                "Engineer->>Analytics: TX-050 analysis\nfailure_mode=winding_degradation, DGA=yellow zone, PD=high",
                "Analytics->>Engineer: Recommend maintenance\nTX-050: oil_reclamation + winding test, by 2026-08-01, cost=$12K",
                "Engineer->>Planner: Schedule CBM\nTX-050: condition-based, replace 2026-Q3, defer from time-based 2027-Q1",
                "Planner->>EAM: Update maintenance plan\nTX-050: retire=TBM schedule, activate=CBM schedule, next=2026-08-01",
                "EAM->>Engineer: Maintenance plan updated\nTX-050: CBM active, 50 other assets on CBM, 400 on TBM",
                "Analytics->>Engineer: Savings report\n2026: 12 failures avoided, $450K savings, CBM ratio=11% (target 25%)",
                "Engineer->>Manager: CBM program review\n50 assets on CBM, $450K savings, expand to 100 assets by 2027-Q1",
            ],
            "integrations": [
                ("PMC", "Model", "TrainRULModel", "Analytics Platform (SAS / Azure ML)", "Analytics Platform (SAS / Azure ML)", "Internal", "Internal", "Batch (Scheduled)", "High"),
                ("PMC", "Data", "RequestTrainingData", "Analytics Platform (SAS / Azure ML)", "IoT Platform (C3 AI / AWS IoT)", "Analytics API (REST)", "IoT API (REST)", "Batch (Scheduled)", "Medium"),
                ("PMC", "Deploy", "DeployInferenceModel", "Analytics Platform (SAS / Azure ML)", "IoT Platform (C3 AI / AWS IoT)", "Analytics API (REST)", "IoT API (REST)", "API-led (Real-time)", "High"),
                ("PMC", "Inference", "RunLiveInference", "IoT Platform (C3 AI / AWS IoT)", "Analytics Platform (SAS / Azure ML)", "IoT API (REST)", "Analytics API (REST)", "API-led (Real-time)", "Medium"),
                ("PMC", "Alert", "AlertRULCritical", "Analytics Platform (SAS / Azure ML)", "Reliability Engineer", "Analytics API (REST)", "Engineer HMI", "Event-driven", "High"),
                ("PMC", "Schedule", "UpdateCBMSchedule", "Maintenance Planner", "EAM (IBM Maximo)", "Planner UI", "EAM API (REST)", "API-led (Real-time)", "Medium"),
                ("PMC", "Report", "GenerateCBMSavingsReport", "Analytics Platform (SAS / Azure ML)", "Asset Manager", "Analytics API (REST)", "Manager UI", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-PMC-01", "Validate RUL prediction accuracy within \u00b115% of actual failure date (historical backtest)", "TrainRULModel", "Backtested RUL predictions within 15% of actual failure dates", "High"),
                ("AC-PMC-02", "Confirm inference model processes 100% of monitored assets within each 24-hour cycle", "RunLiveInference", "All 500 transformers scored with RUL within daily batch window", "High"),
                ("AC-PMC-03", "Verify maintenance plan transition from TBM to CBM is tracked with before/after metrics", "UpdateCBMSchedule", "EAM audit trail shows TBM termination and CBM activation dates", "Medium"),
                ("AC-PMC-04", "Ensure CBM savings report includes failures avoided, maintenance cost reduction, and ROI", "GenerateCBMSavingsReport", "Report shows quantitative savings with auditable failure avoidance evidence", "Medium"),
            ],
        }),
    ]),
}
