"""Section data for Sections 13-16: ERP, Cybersecurity, Data/Analytics, Regulatory."""
from collections import OrderedDict

# Sections 13-16: Enterprise Resource Planning, Cybersecurity, Data/Analytics, Regulatory
SECTION_DATA = OrderedDict()

SECTION_DATA["ERP"] = {
    "title": "Enterprise Resource Planning  - `UT-FIN` `UT-HRP` `UT-PSC` `UT-INV`",
    "description": "Manages enterprise financial operations, human resources, payroll, procurement, supply chain, inventory, and warehousing for the multi-utility organization (electric + water).",
    "capabilities": ["UT-FIN", "UT-HRP", "UT-PSC", "UT-INV"],
    "subflows": OrderedDict([
        ("13.1", {
            "title": "Financial Management & Budgeting",
            "description": "AP invoice processing workflow from receipt through matching, approval, and payment. AR batch from CIS billing, GL journal entries, monthly close, and budget planning cycle where departments submit requests, finance consolidates, and leadership approves. Cash management reconciliations between bank portal and ERP.",
            "actors": ["AP Clerk", "Finance Manager", "Department Budget Owner", "Treasury Analyst"],
            "systems": ["ERP (SAP S/4HANA)", "CIS (Oracle Utilities)", "Bank Portal (BoA)", "Budget System (SAP BPC)"],
            "mermaid": [
                "AP_Clerk->>ERP: Receive supplier invoice\nINV-AP-2026-001: $45,230, PO-PO-2026-042",
                "ERP->>ERP: Match invoice to PO\nqty=100, unit_price=$452.30, tolerance=5%",
                "ERP->>AP_Clerk: Match result\n3-way match: PO, GR, Invoice - all within tolerance",
                "AP_Clerk->>ERP: Route for approval\nINV-AP-2026-001: $45,230, Dept=Operations",
                "ERP->>FinanceMgr: Approval request\nINV-AP-2026-001: $45,230, budget check=passed",
                "FinanceMgr->>ERP: Approve invoice\naccount=OPEX-5400, cost_center=CC-OP-001",
                "ERP->>AP_Clerk: Invoice approved\npayment term=Net 30, due=2026-08-06",
                "AP_Clerk->>ERP: Schedule payment\npayment run=AP-2026-007, batch=weekly",
                "ERP->>BankPortal: ACH payment\n$45,230, vendor=VEN-ACME-ELEC, ref=INV-AP-2026-001",
                "AP_Clerk->>ERP: Post AR batch\nCIS batch=BIL-2026-042: $1.2M, 2,400 customers",
                "ERP->>CIS: Request AR batch\nBIL-2026-042, billing period=June 2026",
                "CIS->>ERP: AR batch received\n$1,245,800, 2,400 accounts, clearing account=1-1200",
                "ERP->>AP_Clerk: AR batch posted\nGL: DR AR $1.2M, CR Revenue $1.1M, CR Tax $100K",
                "Treasury->>BankPortal: Download statement\nBoA acct 4242: 2026-07-06, ending=$4.18M",
                "BankPortal->>Treasury: Statement items\n25 cleared checks, 12 ACH debits, 3 wire transfers",
                "Treasury->>ERP: Reconcile entries\nvariance=$0.00, uncleared items=$20K, reconciled=OK",
            ],
            "integrations": [
                ("Financial", "AP", "MatchInvoiceToPO", "ERP (SAP S/4HANA)", "CIS (Oracle Utilities)", "SAP SOAP", "CIS SOAP", "API-led (Real-time)", "Medium"),
                ("Financial", "AR", "ReceiveARBatch", "CIS (Oracle Utilities)", "ERP (SAP S/4HANA)", "CIS REST API", "SAP REST API", "Batch (Scheduled)", "High"),
                ("Financial", "GL", "PostJournalEntry", "ERP (SAP S/4HANA)", "ERP (SAP S/4HANA)", "Internal", "Internal", "Batch (Real-time)", "Medium"),
                ("Financial", "Budget", "SubmitBudgetRequest", "Department Budget Owner", "Budget System (SAP BPC)", "Budget Web UI", "SAP BPC API (REST)", "API-led (Real-time)", "Simple"),
                ("Financial", "Cash", "ReconcileCash", "ERP (SAP S/4HANA)", "Bank Portal (BoA)", "SAP SFTP", "Bank Portal SFTP", "Batch (Scheduled)", "Medium"),
                ("Financial", "Payment", "ExecutePaymentRun", "ERP (SAP S/4HANA)", "Bank Portal (BoA)", "SAP EDI", "Bank Portal EDI", "Batch (Scheduled)", "High"),
                ("Financial", "Close", "RunMonthlyClose", "ERP (SAP S/4HANA)", "Reporting Database", "SAP JDBC", "Reporting SQL JDBC", "Batch (Scheduled)", "High"),
            ],
            "acceptance_criteria": [
                ("AC-FIN-01", "Validate 3-way PO match tolerance within configured thresholds (\u00b15% price, \u00b110% qty)", "MatchInvoiceToPO", "All invoice matches completed within tolerance before approval", "High"),
                ("AC-FIN-02", "Verify AR batch posting balances to GL within \u00b1$0.01", "ReceiveARBatch", "Batch totals match GL posting with zero variance", "High"),
                ("AC-FIN-03", "Confirm bank reconciliation completes daily with variance resolution", "ReconcileCash", "Daily reconciliation completed with all variances investigated", "Medium"),
                ("AC-FIN-04", "Ensure budget submission workflow enforces department manager approval before consolidation", "SubmitBudgetRequest", "All budget submissions approved by department manager before finance consolidation", "Medium"),
            ],
        }),
        ("13.2", {
            "title": "HR & Payroll",
            "description": "Employee time entry through HR portal with supervisor approval and SAP processing. Payroll calculation and disbursement from HR to SAP Payroll to ADP to bank. Benefits enrollment, recruiting lifecycle, training enrollment, and performance review cycle management.",
            "actors": ["Employee", "HR Manager", "Payroll Specialist", "Benefits Admin"],
            "systems": ["ERP (SAP SuccessFactors)", "Payroll (ADP)", "Benefit Carrier Portal", "Bank", "Time System (Kronos)"],
            "mermaid": [
                "Employee->>Kronos: Enter time sheet\nweek ending 2026-07-05: 40 hrs regular, 2 hrs OT",
                "Kronos->>SuccessFactors: Submit time\ntime_sheet_id=TS-2026-042, employee_id=E-1001",
                "SuccessFactors->>HR_Mgr: Approval request\nTS-2026-042: 42 hrs, regular+OT, review",
                "HR_Mgr->>SuccessFactors: Approve time sheet\nall hours verified, project codes correct",
                "SuccessFactors->>ADP: Send payroll data\nTS-2026-042: E-1001, 42 hrs, pay_rate=$45/hr",
                "ADP->>ADP: Calculate payroll\ngross=$1,935, tax=$483, net=$1,452, deductions=$120",
                "ADP->>SuccessFactors: Payroll results\nnet pay=$1,452, check_date=2026-07-10",
                "ADP->>Bank: ACH direct deposit\n$1,452, routing=021000021, acct=****4242",
                "Bank->>ADP: ACH confirmed\npayment_id=ACH-2026-042, settlement=2026-07-10",
                "Employee->>SuccessFactors: Enroll benefits\nmedical=Blue Shield PPO, dental=Delta, vision=VSP",
                "SuccessFactors->>BenefitPortal: Submit enrollment\nE-1001: medical, dental, vision effective Aug 1",
                "BenefitPortal->>SuccessFactors: Enrollment confirmed\npolicy=MED-4242, premium=$850/mo employer",
                "HR_Mgr->>LinkedIn: Post job req\njob=SCADA Engineer, location=Springfield, req=REQ-2026-003",
                "LinkedIn->>SuccessFactors: Candidate applies\nJane Smith, 12 yrs utility SCADA experience",
                "SuccessFactors->>HR_Mgr: Candidate in pipeline\n4 candidates: Jane Smith shortlisted, interview=July 10",
                "HR_Mgr->>SuccessFactors: Extend offer\nSCADA Engineer, salary=$120K, start=Aug 15",
            ],
            "integrations": [
                ("HR", "Time", "ImportTimeSheet", "Time System (Kronos)", "ERP (SAP SuccessFactors)", "Kronos OData", "SuccessFactors OData", "API-led (Real-time)", "Medium"),
                ("HR", "Payroll", "CalculatePayroll", "ERP (SAP SuccessFactors)", "Payroll (ADP)", "SuccessFactors SFTP", "ADP SFTP", "Batch (Scheduled)", "High"),
                ("HR", "Disbursement", "DisburseNetPay", "Payroll (ADP)", "Bank", "ADP EDI", "Bank EDI", "Batch (Scheduled)", "High"),
                ("HR", "Benefits", "EnrollBenefits", "ERP (SAP SuccessFactors)", "Benefit Carrier Portal", "SuccessFactors API (REST)", "Carrier API (REST)", "API-led (Real-time)", "Medium"),
                ("HR", "Recruiting", "PostJobRequistion", "LinkedIn", "ERP (SAP SuccessFactors)", "LinkedIn API (REST)", "SuccessFactors API (REST)", "API-led (Real-time)", "Simple"),
                ("HR", "Training", "EnrollInTraining", "ERP (SAP SuccessFactors)", "LMS (Cornerstone)", "SuccessFactors SCORM", "LMS SCORM", "API-led (Real-time)", "Simple"),
                ("HR", "OrgChart", "MaintainOrgChart", "ERP (SAP SuccessFactors)", "ERP (SAP SuccessFactors)", "Internal", "Internal", "Batch (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-HRP-01", "Validate time sheet approval completes within 48 hours of employee submission", "ImportTimeSheet", "All time sheets approved within 48 hrs of period end", "Medium"),
                ("AC-HRP-02", "Verify payroll calculation accuracy within \u00b1$0.01 of manual calculation for test cases", "CalculatePayroll", "Payroll register matches calculated gross/net/deductions exactly", "High"),
                ("AC-HRP-03", "Confirm ACH direct deposit settles on scheduled pay date", "DisburseNetPay", "Bank confirms ACH settlement on scheduled pay date", "High"),
                ("AC-HRP-04", "Ensure benefits enrollment changes are reflected in carrier systems within 24 hours", "EnrollBenefits", "Carrier portal confirms enrollment within 24 hrs of submission", "Medium"),
            ],
        }),
        ("13.3", {
            "title": "Procurement & Supply Chain",
            "description": "End-to-end procurement process: requisition through approval, purchase order creation, vendor confirmation, shipment, receipt, inspection, stock, invoice matching, and payment. Includes emergency procurement for outage materials, vendor evaluation scoring, and contract management lifecycle.",
            "actors": ["Requisitioner", "Procurement Manager", "Vendor", "Receiving Clerk", "AP Clerk"],
            "systems": ["ERP (SAP MM/SRM)", "Vendor Portal (Ariba)", "EAM (Maximo)", "Inventory System", "GRIR Reconciliation"],
            "mermaid": [
                "Req->>SAP_MM: Create requisition\nREQ-2026-042: 50 transformers, 75kVA, padmount",
                "SAP_MM->>ProcMgr: Route for approval\nREQ-2026-042: est_value=$450K, budget=CC-OP-001",
                "ProcMgr->>SAP_MM: Approve requisition\nrecommended vendor=VEN-ACME-ELEC, competitive bid",
                "SAP_MM->>Ariba: Create PO\nPO-2026-042: 50 units x $9,000 = $450K, FOB Origin",
                "Ariba->>Vendor: Send PO\nPO-2026-042: 50 padmount transformers, 75kVA, delivery=Aug 15",
                "Vendor->>Ariba: Order confirmed\nPO-2026-042: production lead=6 wks, ship=Aug 1",
                "Ariba->>SAP_MM: PO acknowledgement\nvendor confirmed, delivery window=Aug 1-15",
                "Vendor->>Ariba: ASN submitted\nshipment SH-2026-042: 50 units, carrier=UPS, tracking=1Z4242",
                "Receiving->>SAP_MM: Receive goods\ngoods_receipt GR-2026-042: 50 units, dock=42, inspected",
                "Receiving->>Inventory: Stock material\nbin=WH-01-A42, 50 units, valuation=$450K",
                "SAP_MM->>Inspector: Quality check\nsample=5 units: all passed, dielectric test=OK",
                "Inspector->>SAP_MM: Inspection complete\npass rate=100%, lot accepted, stock approved",
                "AP_Clerk->>SAP_MM: Invoice received\nINV-AP-2026-042: $450K from VEN-ACME-ELEC",
                "SAP_MM->>SAP_MM: GR/IR match\nGR=50 units @ $9K, IR=50 units @ $9K, match=OK",
                "AP_Clerk->>SAP_MM: Schedule payment\nNet 45, due=Sep 1, payment_run=AP-2026-009",
                "SAP_MM->>ProcMgr: Contract renewal alert\nVEN-ACME-ELEC: rating=4.5/5, on-time=98%, renew=recommended",
            ],
            "integrations": [
                ("Procurement", "Requisition", "CreateRequisition", "Requisitioner", "ERP (SAP MM/SRM)", "SAP Web UI", "SAP Internal", "API-led (Real-time)", "Simple"),
                ("Procurement", "PO", "SendPurchaseOrder", "ERP (SAP MM/SRM)", "Vendor Portal (Ariba)", "SAP cXML", "Ariba cXML", "API-led (Real-time)", "High"),
                ("Procurement", "ASN", "ReceiveAdvancedShipNotice", "Vendor Portal (Ariba)", "ERP (SAP MM/SRM)", "Ariba EDI 856", "SAP EDI", "Event-driven", "Medium"),
                ("Procurement", "Receipt", "ReceiveGoods", "Receiving Clerk (RF Scan)", "ERP (SAP MM/SRM)", "RF Scanner API", "SAP REST API", "API-led (Real-time)", "Medium"),
                ("Procurement", "Invoice", "MatchInvoiceGRIR", "ERP (SAP MM/SRM)", "ERP (SAP MM/SRM)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("Procurement", "Contract", "CreateContract", "ERP (SAP MM/SRM)", "ERP (SAP MM/SRM)", "Internal", "Internal", "API-led (Real-time)", "Simple"),
                ("Procurement", "Eval", "EvaluateVendor", "ERP (SAP MM/SRM)", "Supplier Portal", "SAP REST API", "Supplier Portal API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-PSC-01", "Validate PO-to-GR-to-IR 3-way match within tolerance before payment processing", "MatchInvoiceGRIR", "No payment processed without complete GR/IR match", "High"),
                ("AC-PSC-02", "Verify emergency procurement requests are processed within 4 hours for outage materials", "CreateRequisition", "Emergency PO issued within 4 hrs of requisition approval", "High"),
                ("AC-PSC-03", "Confirm ASN receipt triggers automatic dock scheduling 24+ hours before delivery", "ReceiveAdvancedShipNotice", "ASN processed and dock slot assigned before shipment arrival", "Medium"),
                ("AC-PSC-04", "Ensure vendor evaluations are updated quarterly with on-time delivery and quality scores", "EvaluateVendor", "All active vendors scored within 45 days of quarter end", "Medium"),
            ],
        }),
        ("13.4", {
            "title": "Inventory & Warehousing",
            "description": "Stock receipt through put-away, cycle counting, reorder point monitoring, picking for work order issue, inter-warehouse transfer, and inventory adjustments. Critical spares management for transmission transformers, substation breakers, and SCADA components with min/max stock replenishment.",
            "actors": ["Warehouse Clerk", "Inventory Manager", "Maintenance Planner"],
            "systems": ["ERP (SAP WM)", "EAM (Maximo)", "Barcode/RF Scanner", "Inventory Planning", "Logistics (UPS/FedEx)"],
            "mermaid": [
                "Receiving->>SAP_WM: Stock receipt posted\nGR-2026-042: 50 padmount transformers, 75kVA",
                "Warehouse->>SAP_WM: Put-away task\ndestination=WH-01, bin=Aisle A, Rack 12, Bin 42",
                "SAP_WM->>Warehouse: Confirm put-away\n50 units at WH-01-A-12-42, stock=$450K",
                "Warehouse->>SAP_WM: Cycle count\nbin A-12-42: expected=50, actual=49, variance=-1",
                "SAP_WM->>Warehouse: Variance flagged\ntolerance=2%, 1 unit missing, recount required",
                "Warehouse->>SAP_WM: Recount confirm\n49 units verified, create adjustment request",
                "SAP_WM->>InvMgr: Adjustment approval\nITEM-TRF-001: -1 unit, $9K, reason=damage",
                "InvMgr->>SAP_WM: Approve adjustment\nwrite-off account=INV-LOSS, cost center=CC-WH",
                "SAP_WM->>SAP_WM: Reorder point alert\nITEM-TRF-001: min=10, current=9, reorder qty=20",
                "SAP_WM->>Planning: Restock request\nITEM-TRF-001: 20 units, lead time=6 wks, urgent",
                "Maintenance->>Maximo: WO materials pick\nWO-2026-042: 2 transformers, replacement at SUB-MAIN",
                "Maximo->>SAP_WM: Material reservation\nRES-2026-042: 2 x ITEM-TRF-001, project=WO-2026-042",
                "Warehouse->>SAP_WM: Pick & issue\n2 transformers deducted, $18K, issued to WO-2026-042",
                "SAP_WM->>Maximo: Material issue confirm\n2 units issued, WO-2026-042, stock decrease confirmed",
                "Warehouse->>SAP_WM: Transfer stock\ninter-warehouse: WH-01 to WH-02, 5 units, carrier=FedEx",
                "SAP_WM->>SAP_WM: Min/max review\nBI report: 15 slow-moving items flagged, 20 urgent reorders",
            ],
            "integrations": [
                ("Inventory", "Stock", "ExecuteStockTransfer", "ERP (SAP WM)", "ERP (SAP WM)", "SAP Internal", "SAP Internal", "API-led (Real-time)", "Simple"),
                ("Inventory", "Count", "PerformCycleCount", "Barcode/RF Scanner", "ERP (SAP WM)", "Scanner API (REST)", "SAP REST API", "API-led (Real-time)", "Medium"),
                ("Inventory", "Reorder", "TriggerReorderPoint", "ERP (SAP WM)", "Inventory Planning", "SAP Internal", "Planning API (REST)", "Event-driven", "Medium"),
                ("Inventory", "Issue", "IssueMaterialToWO", "ERP (SAP WM)", "EAM (Maximo)", "SAP REST API", "Maximo REST API", "API-led (Real-time)", "High"),
                ("Inventory", "Review", "RunMinMaxReview", "ERP (SAP WM)", "BI Reporting", "SAP JDBC", "BI SQL JDBC", "Batch (Scheduled)", "Simple"),
                ("Inventory", "PhysInv", "ConfirmPhysicalInventory", "Barcode/RF Scanner", "ERP (SAP WM)", "Scanner RF API", "SAP REST API", "Batch (Scheduled)", "Medium"),
                ("Inventory", "Reserve", "CreateStockReservation", "EAM (Maximo)", "ERP (SAP WM)", "Maximo REST API", "SAP REST API", "API-led (Real-time)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-INV-01", "Validate cycle count accuracy within \u00b11% of system inventory for A-class items", "PerformCycleCount", "A-class items counted monthly with <1% variance", "High"),
                ("AC-INV-02", "Verify reorder point triggers purchase requisition within 1 hour of threshold breach", "TriggerReorderPoint", "Requisition created within 1 hr of stock below reorder point", "Medium"),
                ("AC-INV-03", "Confirm stock-out rate for critical spares remains below 2% annually", "RunMinMaxReview", "Critical spares available 98% of time when requested", "High"),
                ("AC-INV-04", "Ensure material issue to work order updates both SAP inventory and Maximo within 5 minutes", "IssueMaterialToWO", "Inventory balance and WO materials synchronized within 5 min", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["Cybersecurity"] = {
    "title": "Cybersecurity & Compliance  - `UT-IAM` `UT-SSM` `UT-VPM` `UT-NCC`",
    "description": "Manages cybersecurity across OT and IT domains: identity and access management, security monitoring (SIEM), vulnerability and patch management, and NERC CIP compliance for critical infrastructure protection.",
    "capabilities": ["UT-IAM", "UT-SSM", "UT-VPM", "UT-NCC"],
    "subflows": OrderedDict([
        ("14.1", {
            "title": "Identity & Access Management (IAM/PAM)",
            "description": "User onboarding through role assignment, access provisioning for IT applications and OT systems, privileged access vaulting via PAM, session monitoring, periodic access recertification, and deprovisioning on termination. Privileged access to substation HMIs, SCADA servers, and ADMS consoles managed with CyberArk.",
            "actors": ["IAM Admin", "OT User", "IT User", "Security Auditor", "PAM Administrator"],
            "systems": ["IAM (Okta/SailPoint)", "PAM (CyberArk)", "AD/Azure AD", "SCADA AD", "HMI Workstations", "HRIS (SuccessFactors)"],
            "mermaid": [
                "IAM_Admin->>IAM: Onboard new user\nIT user John Doe, engineer, role=SCADA-Engineer",
                "IAM->>HRIS: Verify employment\nE-1001: active, dept=OT-Engineering, mgr=Jane Smith",
                "HRIS->>IAM: Employee confirmed\nstart date=July 7, probation=90 days",
                "IAM->>AD: Create AD account\njohn.doe@utility.com, UPN=JD001, group=DOMAIN-USERS",
                "IAM->>Okta: Assign applications\nOkta apps: SAP, EMS view, ADMS view, Email",
                "IAM->>IAM: Role-based access\nrole=SCADA-Engineer: SAP=read, EMS=read, SCADA=read-only",
                "IAM_Admin->>CyberArk: Onboard privileged\naccess to SCADA servers, ADMS admin, HMI substations",
                "CyberArk->>SCADA_AD: Create priv account\nsvc-scada-mon, vaulted, RDP proxy configured",
                "OT_User->>CyberArk: Check-out creds\nrequest=SCADA-ADMIN-SRV-001, reason=patch maintenance",
                "CyberArk->>OT_User: Session launched\nRDP proxy: SRV-SCADA-001, session_id=SES-2026-042",
                "CyberArk->>SIEM: Stream session log\nall keystrokes, screen recording, syslog stream",
                "IAM->>Managers: Recertification email\nQ2 2026: review 150 user access, due=July 15",
                "Manager->>IAM: Certify users\n148 users re-certified, 2 disabled (terminated)",
                "IAM->>AD: Disable terminations\njohn.doe@utility.com: disabled, group membership removed",
                "IAM->>Okta: Remove app access\nOkta: all apps deprovisioned, login disabled",
                "IAM_Admin->>IAM: Audit report\nQ2 2026: 150 users cert'd, 0 exceptions, 2 terminated",
            ],
            "integrations": [
                ("IAM", "Provision", "ProvisionUserFromHR", "HRIS (SuccessFactors)", "IAM (Okta/SailPoint)", "SuccessFactors SCIM", "IAM SCIM", "Event-driven", "High"),
                ("IAM", "Access", "AssignApplicationAccess", "IAM (Okta/SailPoint)", "Okta", "IAM REST API", "Okta REST API", "API-led (Real-time)", "Medium"),
                ("IAM", "PAM", "CheckoutPrivilegedAccount", "PAM (CyberArk)", "SCADA AD", "CyberArk RDP Proxy", "SCADA RDP", "API-led (Real-time)", "High"),
                ("IAM", "Recert", "RunAccessRecertification", "IAM (Okta/SailPoint)", "Manager Email", "IAM REST API", "Email Webhook (SMTP)", "Batch (Scheduled)", "Medium"),
                ("IAM", "Deprovision", "DeprovisionOnTermination", "IAM (Okta/SailPoint)", "AD/Azure AD", "IAM REST API", "AD LDAP", "Event-driven", "High"),
                ("IAM", "Session", "RecordPrivilegedSession", "PAM (CyberArk)", "SIEM (Splunk)", "CyberArk Syslog", "SIEM Syslog", "API-led (Real-time)", "Medium"),
                ("IAM", "RoleMining", "AnalyzeRoleAssignments", "IAM (Okta/SailPoint)", "AD/Azure AD", "IAM LDAP", "AD LDAP", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-IAM-01", "Verify user provisioning completes within 4 hours of HR onboarding event", "ProvisionUserFromHR", "Active Directory account created and applications assigned within 4 hrs", "High"),
                ("AC-IAM-02", "Confirm privileged access session recording captures all keystrokes and screen activity", "RecordPrivilegedSession", "SIEM contains complete session recording for every PAM session", "High"),
                ("AC-IAM-03", "Validate quarterly access recertification completed with 100% manager attestation", "RunAccessRecertification", "All active users recertified within 45 days of quarter end", "Medium"),
                ("AC-IAM-04", "Ensure terminated user access is revoked within 2 hours of HR notification", "DeprovisionOnTermination", "AD disabled, Okta deprovisioned within 2 hrs of termination event", "High"),
            ],
        }),
        ("14.2", {
            "title": "Security Monitoring & SIEM",
            "description": "Log collection from OT environments (firewalls, IEDs, RTUs) and IT (servers, applications, endpoints) into SIEM for correlation, threat detection, alert triage, investigation, incident response, remediation, and documentation. Phishing incident response walkthrough included.",
            "actors": ["SOC Analyst", "Threat Hunter", "OT Security Engineer", "CISO"],
            "systems": ["SIEM (Splunk/ArcSight)", "OT Monitoring (Nozomi/Claroty)", "EDR (CrowdStrike)", "Firewall (Palo Alto)", "SOAR"],
            "mermaid": [
                "Nozomi->>SIEM: OT log stream\nSEL-421 relay: login success, user=tech1042, src=10.0.1.50, 22:00",
                "Windows_Event->>SIEM: IT log stream\nEventID=4624: user=jsmith, workstation=WS-042, success",
                "CrowdStrike->>SIEM: EDR detection\nmalware.exe: hash=f3a2..., alert=Falcon-2026-042, severity=High",
                "SIEM->>SIEM: Correlation rule\nexample: 3 failed logins + 1 success in 5 min = brute force",
                "SIEM->>SOAR: Create alert\nAL-2026-042: brute force detected, user=tech1042, asset=SCADA-SRV",
                "SOAR->>SOC_Analyst: Incident ticket\nINC-2026-042: priority=Critical, asset=SCADA-SRV-001",
                "SOC_Analyst->>SIEM: Investigate\nsearch: all events from 10.0.1.50 last 24 hours",
                "SIEM->>SOC_Analyst: Results\n15 failed logins, 1 success, geo=unexpected country",
                "SOC_Analyst->>SOAR: Escalate to IR\nINC-2026-042: confirmed brute force, contain required",
                "SOAR->>Firewall: Block IP\nPalo Alto: block 10.0.1.50, all ports, duration=24 hrs",
                "Firewall->>SOAR: Rule applied\nblock rule=BL-2026-042, interface=eth1/1, committed",
                "SOC_Analyst->>SOAR: Isolate endpoint\nCrowdStrike: isolate SCADA-SRV-001 from network",
                "CrowdStrike->>SOAR: Host isolated\nSCADA-SRV-001: network restriction active, process halted",
                "SOC_Analyst->>SIEM: Document IR\ntimeline=14:22-15:10, root cause=phished creds, remediated",
                "SOAR->>ServiceNow: Create incident record\nINC-2026-042: resolved, cause=phishing, lessons learned",
                "SIEM->>CISO: Weekly report\n7 incidents: 3 phishing, 2 brute force, 1 malware, 1 policy violation",
            ],
            "integrations": [
                ("SIEM", "OT", "IngestOTLogs", "OT Monitoring (Nozomi/Claroty)", "SIEM (Splunk/ArcSight)", "Nozomi Syslog", "SIEM Syslog", "API-led (Real-time)", "High"),
                ("SIEM", "IT", "IngestITLogs", "Windows Event Collector", "SIEM (Splunk/ArcSight)", "WinCollect", "SIEM Syslog", "API-led (Real-time)", "High"),
                ("SIEM", "ThreatIntel", "ReceiveThreatIntelligence", "Threat Feed (AlienVault)", "SIEM (Splunk/ArcSight)", "Threat Feed API (STIX)", "SIEM API (REST)", "Batch (Scheduled)", "Medium"),
                ("SIEM", "Alert", "CreateSOARAlert", "SIEM (Splunk/ArcSight)", "SOAR", "SIEM REST API", "SOAR REST API", "Event-driven", "High"),
                ("SIEM", "Ticket", "CreateIncidentTicket", "SOAR", "ServiceNow", "SOAR REST API", "ServiceNow REST API", "Event-driven", "Medium"),
                ("SIEM", "Block", "BlockIndicators", "SOAR", "Firewall (Palo Alto)", "SOAR REST API", "PAN-OS REST API", "API-led (Real-time)", "High"),
                ("SIEM", "Report", "GenerateComplianceReport", "SIEM (Splunk/ArcSight)", "Compliance Email", "SIEM REST API", "SMTP Email", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-SSM-01", "Validate OT log ingestion under 5 seconds from Nozomi to SIEM for critical assets", "IngestOTLogs", "SIEM receives OT events within 5s of Nozomi detection", "High"),
                ("AC-SSM-02", "Confirm SOAR playbook executes containment actions within 5 minutes of alert", "BlockIndicators", "Firewall block rule applied within 5 min of alert creation", "High"),
                ("AC-SSM-03", "Verify correlation rules cover all MITRE ATT&CK techniques relevant to utility OT", "CreateSOARAlert", "100% of defined ICS ATT&CK techniques have active correlation rules", "Medium"),
                ("AC-SSM-04", "Ensure incident tickets include full timeline, root cause, and remediation steps", "CreateIncidentTicket", "All closed incidents contain required IR fields", "Medium"),
            ],
        }),
        ("14.3", {
            "title": "Vulnerability & Patch Management",
            "description": "Vulnerability scanning across OT and IT networks, reporting, prioritization by CVSS, approval workflow, patch testing in sandbox, deployment to production, and verification scanning. OT patching considerations for substation relays, RTU firmware, and PLC logic with change management windows.",
            "actors": ["Vuln Mgmt Analyst", "OT Patch Engineer", "Change Manager", "IT SysAdmin"],
            "systems": ["Vulnerability Scanner (Tenable/Qualys)", "Patch Mgmt (WSUS/SCCM)", "OT Asset Inventory", "ServiceNow Change Mgmt", "EAM (Maximo)"],
            "mermaid": [
                "Scanner->>IT_Assets: Scan IT network\n2,500 endpoints: servers=450, workstations=1,800, network=250",
                "Scanner->>OT_Assets: Scan OT network\n1,200 assets: RTUs=300, relays=400, PLCs=200, HMIs=150, FW=150",
                "Scanner->>ServiceNow: Import findings\n3,200 vulns: Critical=45, High=230, Medium=1,100, Low=1,825",
                "ServiceNow->>ServiceNow: Prioritize by CVSS\nCVE-2026-042: CVSS 9.8, Windows RCE, affected=120 servers",
                "Vuln_Analyst->>ServiceNow: Assign to teams\nCritical=OT Patch Eng (20), IT SysAdmin (25), due=7 days",
                "ServiceNow->>ChangeMgr: Submit change\nCHG-2026-042: patch Windows RCE, 120 servers, outage impact=high",
                "ChangeMgr->>ServiceNow: Review change\nwindow=July 12, 02:00-06:00, rollback plan=required",
                "OT_Patch_Eng->>Scanner: Request OT scan\ntarget=substation relays, firmware versions, restricted scope",
                "Scanner->>OT_Patch_Eng: OT scan results\nSEL-421: firmware=v4.2, latest=v4.5, vuln=CVE-2026-043 (relay)",
                "OT_Patch_Eng->>OT_Sandbox: Test patch\nSEL-421 firmware v4.5 in lab, full protection test suite",
                "OT_Sandbox->>OT_Patch_Eng: Patch validation\nall 12 protection tests pass, no regression, comms stable",
                "OT_Patch_Eng->>ServiceNow: Approve deployment\nfirmware v4.5 qualified, change window=July 14 04:00-06:00",
                "SCCM->>IT_Servers: Deploy patches\n120 servers: Windows Update KB504042, reboot=staggered 5 min",
                "IT_Servers->>SCCM: Patch status\n118 success, 2 failed (check WSUS connectivity), pending retry",
                "Scanner->>IT_Assets: Verify scan\npost-patch: CVE-2026-042 remediated on 118/120 servers",
                "Scanner->>ServiceNow: Compliance report\nCVE-2026-042: 98.3% patched, 2 exceptions, SLA=98% met",
            ],
            "integrations": [
                ("VulnMgmt", "Scan", "ScheduleVulnerabilityScan", "Vulnerability Scanner (Tenable/Qualys)", "IT/OT Assets", "Scanner API (REST)", "Asset Agent", "Batch (Scheduled)", "Medium"),
                ("VulnMgmt", "Report", "ImportVulnerabilityReport", "Vulnerability Scanner (Tenable/Qualys)", "ServiceNow Change Mgmt", "Scanner REST API", "ServiceNow REST API", "Batch (Scheduled)", "High"),
                ("VulnMgmt", "Patch", "DeployPatchSCCM", "Patch Mgmt (WSUS/SCCM)", "Windows Servers", "SCCM GPO", "Windows Update Agent", "Batch (Scheduled)", "High"),
                ("VulnMgmt", "OTTest", "TestOTPatchSandbox", "Vulnerability Scanner (Tenable/Qualys)", "OT Sandbox Environment", "Scanner REST API (restricted)", "OT Sandbox Agent", "API-led (Real-time)", "High"),
                ("VulnMgmt", "Change", "CreateChangeTicket", "ServiceNow Change Mgmt", "ServiceNow Change Mgmt", "Internal", "Internal", "API-led (Real-time)", "Medium"),
                ("VulnMgmt", "Approval", "ApprovePatchDeployment", "ServiceNow Change Mgmt", "Manager Email", "ServiceNow Email", "SMTP Email", "API-led (Real-time)", "Simple"),
                ("VulnMgmt", "Compliance", "GenerateComplianceReport", "Vulnerability Scanner (Tenable/Qualys)", "GRC System", "Scanner JDBC", "GRC SQL JDBC", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-VPM-01", "Validate critical vulnerability patches deployed within 7 days of discovery", "DeployPatchSCCM", "100% of critical vulns patched or exception-approved within 7 days", "High"),
                ("AC-VPM-02", "Confirm OT patch testing in sandbox environment completes before production deployment", "TestOTPatchSandbox", "All protection tests pass and no regression observed in sandbox", "High"),
                ("AC-VPM-03", "Verify patch compliance SLA of 98% coverage for critical and high severity vulnerabilities", "GenerateComplianceReport", "Patch coverage >=98% for critical and high vulns", "Medium"),
                ("AC-VPM-04", "Ensure change management approval obtained for all patching with outage windows", "CreateChangeTicket", "All patch deployments have approved change ticket with rollback plan", "High"),
            ],
        }),
        ("14.4", {
            "title": "NERC CIP Compliance",
            "description": "Identify BES Cyber Assets, classify by impact rating (High/Medium/Low), document Electronic Security Perimeter (ESP), implement controls for electronic access, physical security, and personnel training. Self-certification, audit preparation, remediation tracking, and evidence reporting for CIP-005 (ESP), CIP-007 (patch mgmt), and CIP-010 (configuration management).",
            "actors": ["CIP Compliance Lead", "System Administrator", "Auditor (Regional Entity)", "IT/OT Engineer"],
            "systems": ["GRC (Archer/ServiceNow IRM)", "OT Asset Inventory", "PAM (CyberArk)", "SIEM (Splunk)", "Training System", "NERC Portal"],
            "mermaid": [
                "Compliance->>Asset_DB: Identify BES assets\nSUB-MAIN-001: relay=SEL-421, RTU=SEL-3530, impact=High",
                "Asset_DB->>GRC: Register BES assets\n42 High, 86 Medium, 124 Low impact BES Cyber Assets",
                "Compliance->>OT: Classify ESP boundary\nSUB-MAIN-001: ESP includes relay, RTU, network switch HMI",
                "OT->>FW: Configure ESP rules\nPalo Alto: allow only SCADA-CC to relay:port 443, deny all else",
                "FW->>GRC: Document ESP\nesp_id=ESP-SUB-001-01, rules=12, assets=4, last_updated=today",
                "Compliance->>CyberArk: Review PAM\nall BES assets in vault, session recording enabled",
                "CyberArk->>GRC: PAM evidence\n42 High impact BES: PAM check-out logs, session recordings",
                "Compliance->>SIEM: Collect audit logs\nCIP-005: electronic access logs, 90-day retention, syslog archive",
                "SIEM->>GRC: Log evidence\nall BES access events, user=sys, timestamp, source IP, action",
                "Compliance->>Training: Verify training\nCIP-004: all OT personnel completed annual training",
                "Training->>GRC: Training records\n104 employees: CIP-004 current, expiration=2027-01-01",
                "Compliance->>GRC: Self-certify\nCIP-005=compliant, CIP-007=compliant, CIP-010=compliant",
                "Auditor->>GRC: Request evidence\nCIP-005 ESP rules, CIP-007 patch logs, CIP-010 config baseline",
                "GRC->>Auditor: Evidence package\nall controls documented, test results=pass, no exceptions",
                "Auditor->>Compliance: Audit findings\n0 violations, 2 observations (improve documentation), status=Compliant",
                "Compliance->>GRC: Remediation plan\nOBS-001: update ESP docs by Aug 1, OBS-002: add config backup by Aug 15",
            ],
            "integrations": [
                ("CIP", "Inventory", "RegisterBESAssets", "OT Asset Inventory", "GRC (Archer/ServiceNow IRM)", "Asset DB REST API", "GRC REST API", "Batch (Scheduled)", "High"),
                ("CIP", "ESP", "ManageESPBoundary", "OT Network", "Firewall (Palo Alto)", "OT REST API", "PAN-OS API (REST)", "API-led (Real-time)", "High"),
                ("CIP", "Evidence", "CollectAuditEvidence", "ARC (Asset/Log Source)", "GRC (Archer/ServiceNow IRM)", "ARC REST API", "GRC REST API", "Batch (Scheduled)", "Medium"),
                ("CIP", "Violation", "TrackViolations", "GRC (Archer/ServiceNow IRM)", "NERC Portal", "GRC REST API", "NERC Web Portal", "Batch (Scheduled)", "High"),
                ("CIP", "Training", "ReportTrainingRecords", "Training System (LMS)", "GRC (Archer/ServiceNow IRM)", "LMS SCORM", "GRC REST API", "Batch (Scheduled)", "Simple"),
                ("CIP", "Remediation", "TrackRemediation", "ServiceNow", "GRC (Archer/ServiceNow IRM)", "ServiceNow REST API", "GRC REST API", "Event-driven", "Medium"),
                ("CIP", "Report", "GenerateComplianceReport", "GRC (Archer/ServiceNow IRM)", "Management Email", "GRC REST API", "SMTP Email", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-NCC-01", "Validate all High Impact BES Cyber Assets have documented ESP with firewall rules enforced", "ManageESPBoundary", "100% of High impact BES assets inside defined ESP with access rules", "High"),
                ("AC-NCC-02", "Confirm audit evidence collection covers CIP-005, CIP-007, and CIP-010 with 90-day retention", "CollectAuditEvidence", "Evidence package contains logs, configs, and access records within retention period", "High"),
                ("AC-NCC-03", "Verify CIP-004 personnel training completion rate at 100% for OT personnel", "ReportTrainingRecords", "All OT personnel with access to BES assets have current training", "High"),
                ("AC-NCC-04", "Ensure audit findings and observations are tracked to closure with documented remediation", "TrackRemediation", "All audit findings closed or on track with approved remediation plan", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["DataAnalyticsAI"] = {
    "title": "Data, Analytics & AI  - `UT-ODL` `UT-GAF` `UT-CAN` `UT-AHP`",
    "description": "Enterprise data and analytics covering operational data lake (PI System), grid analytics (load forecasting, DER integration), customer analytics (segmentation, EE targeting), and asset health predictive analytics.",
    "capabilities": ["UT-ODL", "UT-GAF", "UT-CAN", "UT-AHP"],
    "subflows": OrderedDict([
        ("15.1", {
            "title": "Operational Data Lake (PI System)",
            "description": "Data ingestion from SCADA, DCS, AMI, GIS, and CMMS through PI Interface nodes into PI Asset Framework and PI Data Archive, then to Enterprise Data Lake (Azure/Snowflake) for curation and analytics datasets. Data quality monitoring dashboards and metadata management via data catalog.",
            "actors": ["Data Engineer", "OT Data Steward", "PI Administrator"],
            "systems": ["OSIsoft PI System (Data Archive / AF)", "SCADA", "DCS (ABB)", "AMI Head-End", "Data Lake (Snowflake)", "Data Catalog (Collibra)"],
            "mermaid": [
                "SCADA->>PI_Interface: Tag data stream\nPT-2026-001 (Turbine Speed): 3600 RPM, quality=Good",
                "DCS->>PI_Interface: Process data\nBoiler: steam_pressure=1800 psi, temp=1005\u00b0F, 1s interval",
                "AMI->>PI_Interface: Interval reads\nMTR-2026-001: 12.45 kWh, 15-min interval, 50 meters/batch",
                "PI_Interface->>PI_Archive: Buffer and send\nbuffered=10s, compressed=deadband 0.5%, reliable delivery",
                "PI_Archive->>PI_AF: Asset frame mapping\nAsset=GEN-2026-001: tags={speed, temp, pressure, vibration}",
                "PI_AF->>PI_AF: Calculate PI tags\nefficiency=58.2%, heat_rate=7.5 MMBTU/MWh, analytics",
                "Data_Engineer->>Snowflake: Extract PI data\nbatch=15-min intervals, 10K tags, format=Parquet",
                "Snowflake->>Data_Engineer: Load complete\nraw schema=PI_RAW, curated schema=PI_CURATED",
                "Data_Engineer->>Snowflake: Curate dataset\ncleansed=nulls removed, outliers flagged, UoM standardized",
                "Snowflake->>Data_Engineer: Quality metrics\ncompleteness=99.7%, timeliness=<30s, accuracy=validated",
                "Data_Steward->>Collibra: Register dataset\nPI_Curated_Generation: owner=OT Team, glossary=Generation",
                "Collibra->>Data_Steward: Metadata catalogued\n50 datasets, 10K PI tags, business terms linked",
                "Data_Engineer->>Snowflake: Create analytics view\nagg=hourly, by unit, for load forecasting ML pipeline",
                "Snowflake->>Data_Engineer: View created\nGEN_HOURLY_AGG: 24 hrs x 4 units x 20 metrics",
                "Data_Steward->>PI_Archive: Monitor data quality\nmissing tags=2 of 10,000, 1 interface down (auto restarted)",
                "PI_Admin->>PI_Interface: Restart interface node\nIIN-SCADA-001: reconnected, backlog=5 min, caught up",
            ],
            "integrations": [
                ("DataLake", "SCADA", "IngestSCADAData", "SCADA (Siemens Spectrum Power)", "PI Interface Node", "SCADA API (ICCP)", "PI Interface (OPC-DA)", "API-led (Real-time)", "High"),
                ("DataLake", "DCS", "IngestDCSProcessData", "DCS (ABB 800xA)", "PI Interface Node", "DCS OPC-UA", "PI Interface (OPC-UA)", "API-led (Real-time)", "High"),
                ("DataLake", "AF", "MapAssetFramework", "PI Interface Node", "PI Asset Framework", "PI API (REST)", "PI AF SDK", "Batch (Real-time)", "Medium"),
                ("DataLake", "Lake", "ExtractToDataLake", "PI Data Archive", "Data Lake (Snowflake)", "PI ODBC/JDBC", "Snowflake SQL", "Batch (Scheduled)", "High"),
                ("DataLake", "Quality", "MonitorDataQuality", "Data Lake (Snowflake)", "Data Catalog (Collibra)", "Snowflake SQL", "Collibra REST API", "Batch (Scheduled)", "Medium"),
                ("DataLake", "Catalog", "RegisterDataset", "Data Lake (Snowflake)", "Data Catalog (Collibra)", "Snowflake SQL", "Collibra REST API", "API-led (Real-time)", "Simple"),
                ("DataLake", "PI_Admin", "ManagePIConnections", "PI Administrator", "PI Interface Node", "PI Admin Console", "PI API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-ODL-01", "Validate PI tag data latency from source to Data Archive under 30 seconds for critical tags", "IngestSCADAData", "Critical tag timestamps within 30s of source scan time", "High"),
                ("AC-ODL-02", "Confirm Snowflake data completeness above 99% for all PI tags in curated layer", "ExtractToDataLake", "Curated datasets have <1% missing values after PI extraction", "Medium"),
                ("AC-ODL-03", "Verify PI Interface deadband compression preserves data within 0.5% accuracy", "IngestDCSProcessData", "Compressed data reconstructs within 0.5% of original values", "Medium"),
                ("AC-ODL-04", "Ensure data catalog coverage is 100% for all production analytics datasets", "RegisterDataset", "All curated datasets have business terms and owners in Collibra", "Medium"),
            ],
        }),
        ("15.2", {
            "title": "Grid Analytics & Forecasting",
            "description": "Historical load data combined with weather forecasts to run ML-based load forecaster producing day-ahead and hour-ahead forecasts for ISO submission and grid operator decision support. DER penetration forecasting, renewable integration analysis, and what-if scenarios for capacity planning.",
            "actors": ["Grid Analyst", "Load Forecaster", "ISO Scheduler"],
            "systems": ["Analytics Platform (SAS/Azure ML)", "Data Lake (Snowflake)", "Weather Service", "ISO Portal", "EMS", "DERMS"],
            "mermaid": [
                "Analyst->>Snowflake: Query historical load\nSUB-MAIN-001: 2 years, hourly, peak=480 MW, min=220 MW",
                "Snowflake->>Analyst: Load history\ntraining set=18 months, validation=6 months",
                "Analyst->>WeatherSvc: Fetch forecast\nSpringfield: July 8, max=95\u00b0F, sunny, wind=5 mph",
                "WeatherSvc->>Analyst: Forecast data\nhourly: temp, humidity, cloud cover, wind speed, pressure",
                "Analyst->>AzureML: Train load model\nalgorithm=XGBoost, features=temp, hour, day, holiday, lag_24",
                "AzureML->>Analyst: Model metrics\nMAE=12 MW (2.5%), R2=0.96, feature_importance=temp(0.45), hour(0.25)",
                "AzureML->>Analyst: Generate forecast\nDA: July 8, peak=465 MW at 16:00, min=235 MW at 04:00",
                "Analyst->>EMS: Send DA forecast\nSpringfield: 465 MW peak, ramp=+8 MW/min at 06:00-09:00",
                "EMS->>ISO: Submit DA schedule\nGEN-001=250 MW, GEN-002=215 MW, total=465 MW, block=16:00",
                "ISO->>EMS: Schedule accepted\nDA market clearing: $32/MWh, Springfield schedule confirmed",
                "Analyst->>AzureML: DER forecast\nsolar=85 MW, wind=45 MW, DER penetration=28% of peak",
                "AzureML->>Analyst: DER impact\nnet load=335 MW (peak less DER), duck curve inflection at 16:00",
                "Analyst->>DERMS: What-if scenario\nwhat-if: 50 MW battery discharge at 16:00, flat net load",
                "DERMS->>Analyst: Scenario result\nnet load flat=335 MW, ramp reduced by 60%, reserve margin=15%",
                "Analyst->>Snowflake: Archive forecast\nforecast_id=FC-2026-042, actual vs forecast comparison",
                "Analyst->>ISO: HA forecast update\nhour-ahead: revised 455 MW (cloud cover increased solar=72 MW)",
            ],
            "integrations": [
                ("GridAnalytics", "Data", "QueryHistoricalLoad", "Data Lake (Snowflake)", "Analytics Platform (Azure ML)", "Snowflake SQL", "Azure ML SDK (Python)", "Batch (Scheduled)", "Medium"),
                ("GridAnalytics", "Weather", "FetchWeatherForecast", "Weather Service (DTN/The Weather Co)", "Analytics Platform (Azure ML)", "Weather API (REST)", "Azure ML REST API", "API-led (Real-time)", "Medium"),
                ("GridAnalytics", "Model", "TrainLoadForecastModel", "Analytics Platform (Azure ML)", "Analytics Platform (Azure ML)", "Azure ML Internal", "Azure ML Internal", "Batch (Scheduled)", "High"),
                ("GridAnalytics", "Forecast", "SendDAForecast", "Analytics Platform (Azure ML)", "EMS", "Azure ML REST API", "EMS API (REST)", "API-led (Real-time)", "High"),
                ("GridAnalytics", "ISO", "SubmitDASchedule", "EMS", "ISO Portal (PJM/MISO/CAISO)", "EMS API (ICCP)", "ISO API (ICCP)", "Batch (Scheduled)", "High"),
                ("GridAnalytics", "DER", "AnalyzeDERPenetration", "Analytics Platform (Azure ML)", "DERMS", "Azure ML REST API", "DERMS API (REST)", "Batch (Real-time)", "Medium"),
                ("GridAnalytics", "Archive", "ArchiveForecastResults", "Analytics Platform (Azure ML)", "Data Lake (Snowflake)", "Azure ML SDK", "Snowflake SQL", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-GAF-01", "Validate day-ahead load forecast accuracy within \u00b13% MAPE for system peak", "TrainLoadForecastModel", "DA forecast MAE <3% of actual peak load", "High"),
                ("AC-GAF-02", "Confirm hour-ahead forecast update submitted to ISO at least 30 minutes before delivery hour", "SendDAForecast", "HA forecast submitted before ISO deadline each hour", "High"),
                ("AC-GAF-03", "Verify DER penetration forecast includes solar, wind, and battery scenarios with confidence intervals", "AnalyzeDERPenetration", "DER forecast includes P50/P90 scenarios and confidence bounds", "Medium"),
                ("AC-GAF-04", "Ensure forecast accuracy is tracked and reported monthly with model retraining trigger at drift >5%", "ArchiveForecastResults", "Model retraining initiated when monthly MAPE exceeds 5% for 2 months", "Medium"),
            ],
        }),
        ("15.3", {
            "title": "Customer Analytics & Segmentation",
            "description": "Customer data analysis using usage patterns for k-means clustering to create segments (residential, commercial & industrial, energy efficiency prospects). Targeted campaign design, program enrollment tracking, energy savings measurement, and M&V (Measurement and Verification) reporting.",
            "actors": ["Data Scientist", "Marketing Analyst", "EE Program Manager"],
            "systems": ["Analytics Platform (Python/R)", "Data Lake (Snowflake)", "CRM (Salesforce)", "CIS", "MDM", "Campaign Mgmt (Marketo)"],
            "mermaid": [
                "DataScientist->>Snowflake: Load customer data\nCUST-2026-001 to 050K: usage, rate, billing, premise data",
                "Snowflake->>DataScientist: Customer dataset\n50K customers, 24 months, 15-min interval usage, 30 features",
                "DataScientist->>Python: Feature engineering\navg_load, peak_load, load_factor, night_ratio, summer_peak",
                "Python->>DataScientist: Feature matrix\n50K x 30 features, scaled=StandardScaler, outliers=capped at 3sigma",
                "DataScientist->>Python: K-Means clustering\nk=5, inertia=0.85, silhouette=0.62, clusters=optimal",
                "Python->>DataScientist: Segment profiles\nSeg 0: Res Low (40%), Seg 1: Res High (25%), Seg 2: C&I (20%), Seg 3: EE Prospects (10%), Seg 4: EV Owners (5%)",
                "DataScientist->>Salesforce: Push segments\nCUST-2026-001: segment=EE_Prospect, propensity=0.72, next_best_action=audit",
                "Salesforce->>Marketo: Launch campaign\nEE Audit Offer: target=5K EE prospects, channel=email, offer=free audit",
                "Marketo->>Customer: Send email\nsubject=Save Energy, Free Home Energy Audit, offer code=AUDIT-2026",
                "Customer->>Marketo: Click-through\nlink=schedule audit, click_rate=8.2%, 410 customers engaged",
                "Marketo->>Salesforce: Campaign results\n5K sent, 410 clicked (8.2%), 85 enrolled in audit program",
                "EE_Mgr->>CIS: Track enrollments\n85 audits scheduled, baseline usage established for M&V",
                "CIS->>EE_Mgr: Baseline load\npre-audit: avg=850 kWh/mo, post-audit forecast=765 kWh/mo (-10%)",
                "DataScientist->>Python: M&V analysis\nsavings=85 customers x 85 kWh/mo avg = 7,225 kWh/mo total",
                "Python->>EE_Mgr: M&V report\nQ2 2026: program savings=21,675 kWh, goal=100,000 kWh, 22% achieved",
                "EE_Mgr->>Regulator: Submit EE report\nIL EE Portfolio: Q2 2026, 21,675 kWh saved, cost=$0.03/kWh",
            ],
            "integrations": [
                ("CustAnalytics", "Data", "LoadCustomerUsage", "Data Lake (Snowflake)", "Analytics Platform (Python/R)", "Snowflake SQL", "Python JDBC", "Batch (Scheduled)", "Medium"),
                ("CustAnalytics", "Cluster", "RunKMeansSegmentation", "Analytics Platform (Python/R)", "Analytics Platform (Python/R)", "Internal", "Internal", "Batch (Scheduled)", "Medium"),
                ("CustAnalytics", "CRM", "PushSegmentsToCRM", "Analytics Platform (Python/R)", "CRM (Salesforce)", "Python REST API", "Salesforce REST API", "Batch (Scheduled)", "High"),
                ("CustAnalytics", "Campaign", "LaunchEECampaign", "CRM (Salesforce)", "Campaign Mgmt (Marketo)", "Salesforce REST API", "Marketo REST API", "API-led (Real-time)", "Medium"),
                ("CustAnalytics", "Enroll", "TrackProgramEnrollment", "CRM (Salesforce)", "CIS", "Salesforce REST API", "CIS REST API", "Event-driven", "Simple"),
                ("CustAnalytics", "M&V", "CalculateEnergySavings", "Analytics Platform (Python/R)", "CIS", "Python REST API", "CIS REST API", "Batch (Scheduled)", "Medium"),
                ("CustAnalytics", "Report", "GenerateEEReport", "Analytics Platform (Python/R)", "Regulatory Portal", "Python REST API", "Reg Portal (REST/SOAP)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-CAN-01", "Validate segmentation silhouette score above 0.5 indicating well-separated clusters", "RunKMeansSegmentation", "Silhouette score >=0.5 for customer segmentation model", "Medium"),
                ("AC-CAN-02", "Confirm campaign targeting accuracy: at least 70% of EE prospects enroll or engage", "LaunchEECampaign", "EE prospect engagement rate >=70% across all campaigns", "Medium"),
                ("AC-CAN-03", "Verify M&V savings calculation uses approved IPMVP Option C methodology", "CalculateEnergySavings", "M&V methodology documented and consistent with IPMVP Option C", "High"),
                ("AC-CAN-04", "Ensure EE program savings are tracked quarterly and reported to regulator within deadlines", "GenerateEEReport", "Quarterly EE report submitted within 30 days of quarter end", "High"),
            ],
        }),
        ("15.4", {
            "title": "Asset Health & Predictive Analytics",
            "description": "IoT sensor data collection from critical assets, feature engineering, ML model training (Random Forest/XGBoost) for remaining useful life (RUL) prediction, risk matrix scoring, maintenance recommendation generation, CMMS work order creation, cost avoidance calculation, and model retraining lifecycle.",
            "actors": ["Data Scientist", "Reliability Engineer", "Maintenance Manager"],
            "systems": ["IoT Platform (C3 AI / AWS IoT)", "Analytics Platform (Azure ML / DataBricks)", "EAM (Maximo)", "SCADA Historian (PI)", "Visualization (Tableau)"],
            "mermaid": [
                "PI_Historian->>IoT_Platform: Stream sensor data\nTRB-2026-001: vibration=0.02 in/s, temp=195\u00b0F, bearing_oil_press=30 psi",
                "IoT_Platform->>Analytics: Batch features\nhourly: vibration_avg, temp_max, oil_pressure_min, trend_1hr",
                "Analytics->>Analytics: Feature engineering\nrolling_window=7 days, lag_features=24 hrs, moving_avg=1hr",
                "Analytics->>Analytics: ML inference\nmodel=Random Forest, assets=50 critical turbines/pumps/transformers",
                "Analytics->>DataScientist: RUL prediction\nTRB-2026-001: RUL=45 days, vibration trend=+0.002 in/s/week",
                "Analytics->>DataScientist: Risk matrix\nTRB-2026-001: likelihood=High (4), consequence=Critical (5), risk=20",
                "DataScientist->>Tableau: Publish dashboard\nasset health score=62/100, TRB-2026-001 red-flagged",
                "Tableau->>ReliabilityEng: View risk heatmap\nturbine TRB-2026-001: RUL=45 days, maintenance recommended <30 days",
                "ReliabilityEng->>Analytics: What-if analysis\nwhat-if: bearing replaced in 14 days, RUL extends to 180 days",
                "Analytics->>ReliabilityEng: Scenario result\nbearing replacement: RUL from 45 to 180 days, cost=$45K, savings=$250K",
                "ReliabilityEng->>Maximo: Create work order\nWO-2026-042: replace bearing TRB-2026-001, due=July 21, priority=High",
                "Maximo->>ReliabilityEng: WO created\nWO-2026-042: scheduled July 21-22, cost_est=$45K, labor=16 hrs",
                "ReliabilityEng->>Analytics: Confirm maintenance\nTRB-2026-001: bearing replaced, vibration dropped to 0.008 in/s",
                "Analytics->>Analytics: Model retraining\ntraining data updated with actual RUL, feature_retrain=monthly",
                "Analytics->>DataScientist: New model metrics\ndelta RUL accuracy: pre=68%, post=73%, improvement=+5%",
                "DataScientist->>Tableau: Cost avoidance report\nTRB-2026-001: avoided catastrophic failure, savings=$250K, ROI=5.5x",
            ],
            "integrations": [
                ("AssetHealth", "Sensors", "IngestSensorData", "SCADA Historian (PI)", "IoT Platform (C3 AI / AWS IoT)", "PI API (REST)", "IoT Platform API (MQTT)", "API-led (Real-time)", "High"),
                ("AssetHealth", "Features", "EngineerFeatures", "IoT Platform (C3 AI / AWS IoT)", "Analytics Platform (Azure ML)", "IoT API (REST)", "Azure ML SDK", "Batch (Scheduled)", "Medium"),
                ("AssetHealth", "Model", "RunPredictiveModel", "Analytics Platform (Azure ML / DataBricks)", "Analytics Platform (Azure ML / DataBricks)", "Internal", "Internal", "Batch (Scheduled)", "High"),
                ("AssetHealth", "Risk", "GenerateRiskMatrix", "Analytics Platform (Azure ML / DataBricks)", "Visualization (Tableau)", "Analytics REST API", "Tableau REST API", "Batch (Real-time)", "Medium"),
                ("AssetHealth", "WO", "CreateMaintenanceWO", "Analytics Platform (Azure ML / DataBricks)", "EAM (Maximo)", "Analytics REST API", "Maximo REST API", "Event-driven", "High"),
                ("AssetHealth", "Retrain", "RetrainPredictiveModel", "Analytics Platform (Azure ML / DataBricks)", "Analytics Platform (Azure ML / DataBricks)", "Internal", "Internal", "Batch (Scheduled)", "Medium"),
                ("AssetHealth", "Report", "ReportCostAvoidance", "Visualization (Tableau)", "Maintenance Manager Email", "Tableau REST API", "SMTP Email", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-AHP-01", "Validate RUL prediction accuracy within \u00b115% of actual failure date for critical assets", "RunPredictiveModel", "RUL prediction within 15% of actual remaining life for training set", "High"),
                ("AC-AHP-02", "Confirm risk matrix scoring follows standardized 5x5 likelihood x consequence methodology", "GenerateRiskMatrix", "All critical assets scored using approved risk matrix methodology", "Medium"),
                ("AC-AHP-03", "Verify predictive model triggers work order creation at RUL threshold >30 days for actionable lead time", "CreateMaintenanceWO", "WO created when predicted RUL crosses 30-day threshold", "High"),
                ("AC-AHP-04", "Ensure model retraining occurs monthly with validation on latest failure events", "RetrainPredictiveModel", "Model retrained monthly and validated against held-out failure data", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["RegulatoryMarket"] = {
    "title": "Regulatory, Market & Environmental Compliance  - `UT-RRP` `UT-ISO` `UT-ENV` `UT-EHS`",
    "description": "Manages regulatory reporting (FERC, NERC, PUC, EPA), ISO/RTO wholesale market operations, environmental compliance (emissions, water discharge, waste), and EHS (safety, health, incident management).",
    "capabilities": ["UT-RRP", "UT-ISO", "UT-ENV", "UT-EHS"],
    "subflows": OrderedDict([
        ("16.1", {
            "title": "Regulatory Reporting (FERC/NERC/PUC)",
            "description": "Data collection from financial, operational, and reliability systems, validation, FERC Form 1 preparation, NERC GADS reporting for generator availability, PUC rate case support with cost-of-service studies, audit evidence compilation, submission via regulatory portals, and responses to data requests.",
            "actors": ["Regulatory Analyst", "Compliance Manager", "Legal Counsel", "Auditor"],
            "systems": ["ERP (SAP)", "OMS", "EMS Historian", "GRC (Archer)", "FERC eForms Portal", "NERC Compliance Portal"],
            "mermaid": [
                "Analyst->>SAP: Extract financial data\nFERC Form 1: income statement, balance sheet, O&M expenses by function",
                "SAP->>Analyst: Financial extract\n2025 FY: total rev=$850M, O&M=$520M, dep=$85M, taxes=$45M",
                "Analyst->>OMS: Extract reliability data\nSAIDI=89 min, SAIFI=0.95, CAIDI=94 min, MAIFI=0.12",
                "OMS->>Analyst: Reliability extract\n2025 calendar year: all indices calculated per IEEE 1366",
                "Analyst->>EMS: Generate availability\nGADS data: GEN-001 forced outage rate=2.1%, EAF=92%",
                "EMS->>Analyst: GADS report\nGEN-001: 8,760 hrs, available=8,059 hrs, forced_outage=184 hrs",
                "Analyst->>FERC_Portal: Submit Form 1\nFERC Form 1: 2025 FY, all schedules complete, certified",
                "FERC_Portal->>Analyst: Submission accepted\nreceipt=FERC-2026-042, filing date=Apr 15, on-time",
                "Analyst->>NERC_Portal: Submit GADS\nGADS-2026-042: 25 generating units, 2025 annual data",
                "NERC_Portal->>Analyst: GADS accepted\nNERC acknowledgment, next data call=2026-Q1 due July 30",
                "Legal->>Analyst: PUC data request\nDPU-2026-003: cost of service study, rate base, ROE calculation",
                "Analyst->>SAP: Cost of service model\nfunctionalized: generation=$420M, transmission=$180M, distribution=$250M",
                "SAP->>Analyst: Cost allocation\nby customer class: Res=55%, C&I=35%, Lighting=10%",
                "Analyst->>GRC: Archive evidence\nDocket DPU-2026-003: all exhibits, workpapers, testimony drafts",
                "Auditor->>GRC: Request audit evidence\nFERC audit 2026: 25 information requests, due=30 days",
                "GRC->>Auditor: Evidence package\nall 25 items: documents, data, procedures, org charts, narratives",
            ],
            "integrations": [
                ("RegReporting", "Financial", "ExtractFERCForm1Data", "ERP (SAP)", "Regulatory Analyst", "SAP JDBC", "Analyst Excel/SQL", "Batch (Scheduled)", "Medium"),
                ("RegReporting", "Reliability", "ExtractReliabilityData", "OMS", "Regulatory Analyst", "OMS REST API", "Analyst REST API", "Batch (Scheduled)", "Medium"),
                ("RegReporting", "GADS", "GenerateGADSReport", "EMS Historian", "NERC Compliance Portal", "EMS SQL JDBC", "NERC Portal Web", "Batch (Scheduled)", "High"),
                ("RegReporting", "FERC", "SubmitFERCForm1", "Regulatory Analyst", "FERC eForms Portal", "Analyst Portal UI", "FERC eForms API (SOAP)", "Batch (Scheduled)", "High"),
                ("RegReporting", "PUC", "RespondToDataRequest", "Regulatory Analyst", "GRC (Archer)", "Analyst REST API", "GRC REST API", "API-led (Real-time)", "Medium"),
                ("RegReporting", "Evidence", "ArchiveAuditEvidence", "Regulatory Analyst", "GRC (Archer)", "Analyst REST API", "GRC REST API", "API-led (Real-time)", "Medium"),
                ("RegReporting", "Audit", "SubmitAuditEvidence", "GRC (Archer)", "Auditor Portal", "GRC REST API", "Auditor Portal (REST)", "Event-driven", "High"),
            ],
            "acceptance_criteria": [
                ("AC-RRP-01", "Validate FERC Form 1 data consistency across all schedules before submission", "ExtractFERCForm1Data", "Cross-schedule totals balance with zero variance flagged", "High"),
                ("AC-RRP-02", "Confirm GADS data submission meets NERC deadline (60 days after quarter end)", "GenerateGADSReport", "GADS submitted within NERC reporting window", "High"),
                ("AC-RRP-03", "Verify PUC data request responses are reviewed by legal counsel before submission", "RespondToDataRequest", "All PUC responses have legal review stamp in GRC", "High"),
                ("AC-RRP-04", "Ensure audit evidence responses are submitted within regulatory deadline", "SubmitAuditEvidence", "100% of audit data requests responded within 30-day window", "High"),
            ],
        }),
        ("16.2", {
            "title": "ISO/RTO Market Operations",
            "description": "Generation offers submitted to ISO, market clearing process, dispatch schedule receipt, real-time balancing and unit commitment, settlement statements reconciliation, discrepancy resolution, and invoicing. Day-ahead and real-time market participation including ancillary services offers (regulation, reserves, reactive).",
            "actors": ["Market Operator", "Settlements Analyst", "Generation Scheduler"],
            "systems": ["Market System (ABB Promod)", "EMS", "ISO Portal (PJM/MISO/CAISO)", "ERP (SAP)", "Trade Capture System"],
            "mermaid": [
                "Operator->>MarketSys: Prepare DA offers\nGEN-001: 250 MW @ $32, GEN-002: 200 MW @ $35, ancillary=reg $5/MW",
                "MarketSys->>ISO: Submit DA offers\nSpringfield portfolio: 450 MW energy, 50 MW regulation, 30 MW reserve",
                "ISO->>MarketSys: DA market results\nclearing=$34/MWh, GEN-001=250 cleared, GEN-002=180 cleared, reg=50 cleared",
                "Operator->>EMS: Schedule DA dispatch\nGEN-001=250 MW baseline, GEN-002=180 MW baseline, 24-hr profile",
                "EMS->>MarketSys: Real-time telemetry\nGEN-001=248 MW, GEN-002=178 MW, total=426 MW, 16:00",
                "ISO->>MarketSys: RT balancing signal\nACE=+15 MW, dispatch GEN-002 up 10 MW, ramp=5 min",
                "MarketSys->>EMS: RT dispatch instruction\nGEN-002: setpoint 180\u2192190 MW, ramp=2 MW/min, AGC enabled",
                "EMS->>Operator: Unit response\nGEN-002: 190 MW, ramp completed in 4.5 min, within limits",
                "ISO->>MarketSys: Settlement statement\nDA=426 MW x $34 = $14,484, RT deviation=+12 MW x $36=$432, total=$14,916",
                "MarketSys->>Settlements: Import settlement\nstatement_id=STMT-2026-042, trading_date=July 7, total=$14,916",
                "Settlements->>MarketSys: Verify settlement\nDA match=OK, RT deviation=+12 MW confirmed by EMS telemetry",
                "Settlements->>MarketSys: Flag discrepancy\nancillary reg: 50 MW cleared but only 48 MW delivered (-2 MW penalty=$200)",
                "MarketSys->>Operator: Discrepancy report\nSTMT-2026-042: -2 MW regulation penalty, dispute filed with ISO",
                "Settlements->>SAP: Post settlement\nDR Cash $14,716, CR Revenue $14,716, after penalty adjustment",
                "MarketSys->>TradeCapture: Log trade\ntrade_id=TRD-2026-042, DA+RT energy, volume=10,224 MWh, value=$358K (monthly)",
                "Operator->>ISO: Submit ancillary offer\nnext day: regulation=55 MW, spin=35 MW, non-spin=20 MW, reactive=50 MVAR",
            ],
            "integrations": [
                ("Market", "Offer", "SubmitDAOffer", "Market System (ABB Promod)", "ISO Portal (PJM/MISO/CAISO)", "Market Sys API (ICCP)", "ISO API (ICCP)", "Batch (Scheduled)", "High"),
                ("Market", "Clear", "ReceiveDAClearing", "ISO Portal (PJM/MISO/CAISO)", "Market System (ABB Promod)", "ISO API (ICCP)", "Market Sys API (ICCP)", "Event-driven", "High"),
                ("Market", "Dispatch", "SendDispatchInstruction", "ISO Portal (PJM/MISO/CAISO)", "EMS", "ISO API (ICCP)", "EMS API (ICCP)", "API-led (Real-time)", "High"),
                ("Market", "Settlement", "ImportSettlementStatement", "ISO Portal (PJM/MISO/CAISO)", "Market System (ABB Promod)", "ISO API (REST)", "Market Sys API (REST)", "Batch (Scheduled)", "High"),
                ("Market", "Reconcile", "ReconcileSettlement", "Market System (ABB Promod)", "ERP (SAP)", "Market Sys JDBC", "SAP JDBC", "Batch (Scheduled)", "Medium"),
                ("Market", "Trade", "LogTradeCapture", "Market System (ABB Promod)", "Trade Capture System", "Market Sys API (REST)", "Trade Capture API (REST)", "API-led (Real-time)", "Medium"),
                ("Market", "Invoice", "PostSettlementInvoice", "Market System (ABB Promod)", "ERP (SAP)", "Market Sys REST API", "SAP REST API", "Batch (Scheduled)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-ISO-01", "Validate DA offer submission before ISO deadline (10:00 AM for next day)", "SubmitDAOffer", "All DA offers submitted before ISO deadline with confirmation receipt", "High"),
                ("AC-ISO-02", "Confirm settlement statement reconciliation identifies discrepancies >$500 within 48 hours", "ReconcileSettlement", "All material discrepancies flagged and disputed within 48 hrs", "High"),
                ("AC-ISO-03", "Verify RT dispatch instructions are executed within ramp time limits per generator capability", "SendDispatchInstruction", "Generator response to RT dispatch within ramp rate parameters", "High"),
                ("AC-ISO-04", "Ensure ancillary services offers are optimized to avoid penalty charges for non-delivery", "SubmitDAOffer", "Ancillary delivery accuracy >=98% to avoid ISO penalties", "Medium"),
            ],
        }),
        ("16.3", {
            "title": "Environmental Emissions Reporting",
            "description": "Continuous Emissions Monitoring System (CEMS) data quality assurance, EPA CAMD submission for CO2, NOx, SO2, and Hg via ECMPS, permit compliance tracking, allowance management (RGGI/CARB), public GHG report preparation, and third-party verification.",
            "actors": ["Environmental Engineer", "Compliance Manager", "EPA Reviewer"],
            "systems": ["CEMS Data System", "EPA CAMD Portal", "DCS (ABB)", "Emissions Management", "Allowance Tracking", "Public Portal"],
            "mermaid": [
                "DCS->>CEMS: Raw emissions data\nCO2=1250 TPD, NOx=320 lbs/hr, SO2=15 lbs/hr, Hg=0.005 lbs/hr, O2=4.5%",
                "CEMS->>CEMS: Quality assurance\ncalibration: span gas passed, linearity=0.99, drift=0.5%",
                "CEMS->>CEMS: Data validation\nmissing data=0 hrs, replacement=no, bi-directional status=valid",
                "Operator->>CEMS: Review hourly data\nUnit 1: gross load=250 MW, heat input=1,875 MMBtu/hr",
                "CEMS->>EPA_CAMD: Submit hourly ECMPS\nunit_id=GEN-001, date=July 7, hrs 00-23, all params valid",
                "EPA_CAMD->>CEMS: Acknowledgment\nhourly data accepted, ECMPS batch_id=ECMPS-2026-042",
                "Operator->>CEMS: Check permit limits\nNOx limit=400 lbs/hr, current=320 lbs/hr, margin=20%",
                "CEMS->>Operator: Compliance status\nALL permit limits: CO2=OK, NOx=OK, SO2=OK, Hg=OK",
                "Compliance->>Allowance: Track RGGI allowances\n2026 vintage: 50,000 tons CO2 allocated, 42,000 tons used",
                "Allowance->>Compliance: Allowance position\n8,000 tons remaining, market price=$12/ton, value=$96K",
                "Compliance->>RGGI_Portal: Q2 compliance report\nQ2 2026: 15,000 tons CO2, allowances=16,000, surplus=1,000",
                "RGGI_Portal->>Compliance: Compliance approved\nRGGI Q2: surplus retired, account balance=7,000 tons",
                "Environmental->>Public_Portal: Publish GHG report\n2025 annual: 1.2M tons CO2e, scope 1=1.0M, scope 2=0.2M",
                "Verifier->>Environmental: Verify GHG report\nsite visit=complete, data sampling=95% confidence, verified",
                "Environmental->>EPA_CAMD: Annual report\n2025: 1.2M tons CO2e, verified, per 40 CFR Part 98",
                "EPA_CAMD->>Environmental: Annual accepted\nGHGRP ID=GHG-2026-042, facility=Springfield Power Station",
            ],
            "integrations": [
                ("Emissions", "CEMS", "SendHourlyEmissions", "DCS (ABB)", "CEMS Data System", "DCS OPC-UA", "CEMS Modbus TCP", "API-led (Real-time)", "High"),
                ("Emissions", "QA", "PerformQualityAssurance", "CEMS Data System", "CEMS Data System", "Internal", "Internal", "API-led (Real-time)", "High"),
                ("Emissions", "EPA", "SubmitECMPSCAMD", "CEMS Data System", "EPA CAMD Portal", "CEMS API (REST)", "EPA CAMD Web Services (SOAP)", "Batch (Scheduled)", "High"),
                ("Emissions", "Permit", "VerifyPermitCompliance", "CEMS Data System", "Emissions Management", "CEMS REST API", "Emissions Mgmt REST API", "API-led (Real-time)", "Medium"),
                ("Emissions", "Allowance", "TrackRGGIAllowances", "Allowance Tracking System", "RGGI/CARB Portal", "Allowance API (REST)", "RGGI Portal API (SOAP)", "Batch (Scheduled)", "Medium"),
                ("Emissions", "GHG", "SubmitGHGReport", "Emissions Management", "EPA CAMD Portal", "Emissions REST API", "EPA CAMD Web Services", "Batch (Scheduled)", "High"),
                ("Emissions", "Verification", "CompleteThirdPartyVerification", "Third-Party Verifier", "Emissions Management", "Verifier Portal API", "Emissions API (REST)", "Batch (Scheduled)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-ENV-01", "Validate CEMS data completeness >95% with missing data substitution per 40 CFR Part 75", "PerformQualityAssurance", "No data gaps >2 hrs without valid substitute data", "High"),
                ("AC-ENV-02", "Confirm EPA CAMD hourly submission is within 30-day reporting window", "SubmitECMPSCAMD", "All hourly data submitted by 30th day of following month", "High"),
                ("AC-ENV-03", "Verify emission limits are never exceeded: NOx <400 lbs/hr, SO2 <50 lbs/hr, Hg <0.01 lbs/hr", "VerifyPermitCompliance", "Zero exceedance events for permitted emission limits", "High"),
                ("AC-ENV-04", "Ensure annual GHG report is verified by accredited third party before public submission", "SubmitGHGReport", "Third-party verification statement included with annual GHG submission", "Medium"),
            ],
        }),
        ("16.4", {
            "title": "EHS Management & Safety",
            "description": "Incident reporting, investigation with root cause analysis, corrective action tracking, safety observations, hazard identification and JSA (Job Safety Analysis), training management, safety audits, OSHA recordkeeping (300 log), injury metrics (DART, TRIR), safety meetings, and leadership dashboard review.",
            "actors": ["Safety Officer", "Employee", "EHS Manager", "OSHA Representative"],
            "systems": ["EHS System (Intelex/Enablon)", "HRIS (SuccessFactors)", "Training System", "OSHA Portal", "IoT Safety Sensors"],
            "mermaid": [
                "Employee->>EHS_System: Report near miss\nNM-2026-042: slip hazard at substation SUB-MAIN-001, wet floor near panel",
                "EHS_System->>SafetyOfficer: Near miss assigned\ninvestigator=John Smith, due=7 days, location=SUB-MAIN-001",
                "SafetyOfficer->>EHS_System: Initial assessment\nhazard=standing water near 480V panel, severity=Medium, likelihood=3",
                "SafetyOfficer->>EHS_System: Investigate root cause\n5-why: drain clogged, gutter not cleaned, no PM schedule for drains",
                "SafetyOfficer->>EHS_System: CAPA required\nCAPA-2026-042: clean drains weekly, install drain cover, inspect monthly",
                "EHS_System->>SafetyOfficer: CAPA approved\naction=assign to maintenance, due=July 14, status=Open",
                "Employee->>EHS_System: Hazard observation\nobs-2026-042: technician not wearing arc flash PPE at switchgear",
                "EHS_System->>SafetyOfficer: Safety observation\nobs-2026-042: immediate corrective action=stop work, retrain",
                "SafetyOfficer->>EHS_System: JSA required\nJSA-2026-042: arc flash hazard, switchgear maintenance, PPE=HRC 2",
                "SafetyOfficer->>Training: Schedule training\narc flash awareness, 10 employees, July 15, classroom",
                "Training->>EHS_System: Training completed\n10 employees certified arc flash, expiration=2027-07-15",
                "EHS_System->>OSHA: Log recordable\nOSHA-300: first aid only=0, medical treatment=1, restricted duty=0",
                "OSHA->>EHS_System: Recordkeeping audit\n2025 log: TRIR=0.85, DART=0.42, all logs complete and posted",
                "EHS_Mgr->>EHS_System: Safety metrics dashboard\nQ2 2026: TRIR=0.72 (target<1.0), DART=0.38 (target<0.5)",
                "EHS_System->>EHS_Mgr: Trend analysis\nnear misses up 15% (good reporting culture), recordables down 20%",
                "EHS_System->>Dashboard: Leadership review\nsafety: 42 days since last recordable, 5 CAPAs open, 3 overdue",
            ],
            "integrations": [
                ("EHS", "Incident", "ReportNearMiss", "Employee Mobile App", "EHS System (Intelex/Enablon)", "Mobile API (OAuth2)", "EHS REST API", "API-led (Real-time)", "Simple"),
                ("EHS", "Investigation", "PerformRootCauseAnalysis", "EHS System (Intelex/Enablon)", "EHS System (Intelex/Enablon)", "Internal", "Internal", "API-led (Real-time)", "Medium"),
                ("EHS", "CAPA", "TrackCorrectiveAction", "EHS System (Intelex/Enablon)", "EHS System (Intelex/Enablon)", "Internal", "Internal", "API-led (Real-time)", "Medium"),
                ("EHS", "Training", "ScheduleSafetyTraining", "EHS System (Intelex/Enablon)", "Training System (LMS)", "EHS REST API", "LMS SCORM", "Event-driven", "Simple"),
                ("EHS", "OSHA", "SubmitOSHA300Log", "EHS System (Intelex/Enablon)", "OSHA Portal", "EHS REST API", "OSHA Portal API (SOAP)", "Batch (Scheduled)", "High"),
                ("EHS", "Dashboard", "GenerateSafetyDashboard", "EHS System (Intelex/Enablon)", "HRIS (SuccessFactors)", "EHS SQL JDBC", "SuccessFactors REST API", "Batch (Real-time)", "Medium"),
                ("EHS", "IoT", "MonitorIoTSafetySensors", "IoT Safety Sensors (gas/arc flash)", "EHS System (Intelex/Enablon)", "Sensor MQTT", "EHS API (MQTT)", "API-led (Real-time)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-EHS-01", "Validate all safety incidents (near miss, first aid, recordable) are reported within 24 hours", "ReportNearMiss", "100% of incidents reported in EHS system within 24 hrs of occurrence", "High"),
                ("AC-EHS-02", "Confirm root cause investigation completed within 7 days for all recordable incidents", "PerformRootCauseAnalysis", "RCA report approved in EHS system within 7-day target", "High"),
                ("AC-EHS-03", "Verify CAPA closure rate above 90% within original due date", "TrackCorrectiveAction", "At least 90% of CAPAs closed on or before original due date", "Medium"),
                ("AC-EHS-04", "Ensure OSHA 300 log is posted annually by February 1 and retained for 5 years", "SubmitOSHA300Log", "OSHA 300 log posted in workplace and submitted per regulatory requirement", "High"),
            ],
        }),
    ]),
}
