"""Section data for Sections 5-8: Water, Wastewater, Metering, Customer."""
from collections import OrderedDict

# Sections 5-8: Water Treatment, Distribution, Wastewater, Metering
SECTION_DATA = OrderedDict()

SECTION_DATA["WaterTreatment"] = {
    "title": "Water Treatment Plant Operations (WTP) - `UT-WTC` `UT-WQM`",
    "description": "Monitor and control water treatment processes including raw water intake, chemical dosing, coagulation/flocculation, filtration, disinfection, and clearwell storage. SCADA and DCS systems manage plant operations with real-time quality monitoring.",
    "capabilities": ["UT-WTC", "UT-WQM"],
    "subflows": OrderedDict([
        ("5.1", {
            "title": "Raw Water Intake & Preliminary Treatment",
            "description": "Operators monitor raw water quality from the source reservoir, control intake gates and screens, manage chemical pre-treatment dosing, and oversee the settling basin operations.",
            "actors": ["Treatment Plant Operator", "Plant Manager", "Lab Technician"],
            "systems": ["SCADA (Schneider Electric EcoStruxure)", "DCS (Rockwell PlantPAx)", "Water Quality Analyzers", "Chemical Dosing System"],
            "mermaid": [
                "Operator->>SCADA: Check raw water quality\nWTP-2026-001: turbidity=12 NTU, pH=7.0, temp=18°C",
                "SCADA->>Analyzer: Sample raw water\nintake channel, 15-min cycle",
                "Analyzer->>SCADA: Raw water params\nturbidity=12.5 NTU, pH=7.1, algae=250 cells/mL",
                "SCADA->>Operator: Review inlet conditions\nflow=35 MGD, river stage=4.2 ft",
                "Operator->>DCS: Adjust coagulant dose\nalum=25 mg/L, based on turbidity",
                "DCS->>Dosing: Set chemical feed rate\nalum pump=185 GPH, polymer=12 GPH",
                "Dosing->>DCS: Flow established\nalum=185 GPH (±2%), polymer=12 GPH",
                "DCS->>SCADA: Update chemical feed\nalum=25 mg/L, polymer=1.2 mg/L",
                "SCADA->>Operator: Monitor flash mixer\nG=700 s^-1, detention=45s",
                "Operator->>DCS: Adjust rapid mix speed\nG target=700, current=680, increase 3%",
                "DCS->>Mixer: Increase flash mixer RPM\nvariable drive: 45 Hz → 48 Hz",
                "Mixer->>DCS: Speed confirmed\n48 Hz, G=705 s^-1, within spec",
                "Operator->>SCADA: Review settled water\nturbidity=3.2 NTU, pH=6.8",
                "SCADA->>Lab: Send sample alert\nsettled water, collect for jar testing",
                "Lab->>SCADA: Jar test results\noptimum alum=24 mg/L, pH=6.7",
                "Operator->>DCS: Fine-tune dose\nset alum=24 mg/L, confirm settled turbidity=2.8 NTU",
            ],
            "integrations": [
                ("Water Treatment", "Raw Water", "SampleRawWater", "Water Quality Analyzer", "SCADA (EcoStruxure)", "Analyzer Modbus RTU", "SCADA Modbus TCP", "API-led (Real-time)", "Medium"),
                ("Water Treatment", "Dosing", "SetChemicalDose", "DCS (Rockwell PlantPAx)", "Chemical Dosing System", "DCS OPC-UA", "Dosing Pump PLC", "API-led (Real-time)", "Medium"),
                ("Water Treatment", "Mixing", "AdjustFlashMixerSpeed", "DCS (Rockwell PlantPAx)", "Flash Mixer VFD", "DCS OPC-UA", "VFD Modbus RTU", "API-led (Real-time)", "Simple"),
                ("Water Treatment", "Settled", "MonitorSettledWater", "SCADA (EcoStruxure)", "DCS (Rockwell PlantPAx)", "SCADA OPC-DA", "DCS OPC-UA", "API-led (Real-time)", "Medium"),
                ("Water Treatment", "Lab", "AnalyzeJarTest", "Lab Information System", "SCADA (EcoStruxure)", "LIS API (REST)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
                ("Water Treatment", "Chemical", "LogChemicalUsage", "DCS (Rockwell PlantPAx)", "Plant Historian (OSIsoft PI)", "DCS OPC-UA", "PI API (REST)", "Batch (Scheduled)", "Simple"),
                ("Water Treatment", "Compliance", "RecordRawWaterQuality", "SCADA (EcoStruxure)", "Compliance Database", "SCADA API (REST)", "SQL JDBC", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-WT-01", "Verify coagulant dose optimization achieves settled turbidity <5 NTU", "SetChemicalDose", "Settled turbidity below 5 NTU within 30 min of dose change", "High"),
                ("AC-WT-02", "Validate raw water quality sample frequency meets regulatory minimum (every 15 min)", "SampleRawWater", "Analyzer logs show 15-min sampling interval maintained", "High"),
                ("AC-WT-03", "Confirm flash mixer G value within ±10% of design target", "AdjustFlashMixerSpeed", "G value between 630-770 s^-1", "Medium"),
                ("AC-WT-04", "Ensure chemical feed rate accuracy within ±5% of setpoint", "SetChemicalDose", "Flow meter verifies dosing within 5% of commanded rate", "Medium"),
            ],
        }),
        ("5.2", {
            "title": "Filtration & Disinfection Control",
            "description": "Operators manage dual-media filtration process, backwash cycles, chlorination disinfection, and clearwell storage levels. CT (concentration × time) values are calculated for regulatory compliance.",
            "actors": ["Treatment Plant Operator", "Lab Technician", "Compliance Officer"],
            "systems": ["DCS (Rockwell PlantPAx)", "SCADA (EcoStruxure)", "Chlorine Analyzers", "Filter Control System", "Clearwell Level Sensors"],
            "mermaid": [
                "Operator->>SCADA: Review filter performance\n8 filters online, total flow=35 MGD",
                "SCADA->>DCS: Filter effluent turbidity\nfilter 3: 0.12 NTU, filter 7: 0.45 NTU (high)",
                "DCS->>FilterCtrl: Initiate backwash\nfilter 7: turbidity exceeds 0.3 NTU threshold",
                "FilterCtrl->>DCS: Backwash sequence\nfilter 7: drain, air scour, water wash, rinse",
                "DCS->>Operator: Filter 7 in backwash\nduration=15 min, water loss=0.05 MG",
                "SCADA->>ChlorAnalyzer: Check chlorine residual\npost-filtration: 0.5 mg/L free Cl2",
                "ChlorAnalyzer->>SCADA: Free Cl2=0.48 mg/L\ncontact tank, pH=6.8, temp=16°C",
                "Operator->>DCS: Adjust chlorine dose\nsetpoint=2.0 mg/L, maintain residual 0.8 mg/L",
                "DCS->>ChlorDosing: Set feed rate\nchlorine gas: 180 lbs/day",
                "ChlorDosing->>DCS: Feed rate confirmed\n180 lbs/day, flow paced",
                "SCADA->>DCS: Calculate CT value\nCT=120 mg-min/L, requirement=90",
                "DCS->>Operator: CT compliant\nCT=120 ≥ 90, log entry for compliance",
                "Operator->>SCADA: Check clearwell level\nclearwell 1: 12.5 ft, clearwell 2: 14.2 ft",
                "SCADA->>Operator: Clearwell total=2.8 MG\nfreeboard=3.2 ft, detention=2.2 hrs",
                "Operator->>DCS: Adjust finished water pH\ncaustic feed=8 GPH, target pH=7.4",
                "DCS->>Operator: Finished water quality\nturbidity=0.08 NTU, pH=7.4, Cl2=0.85 mg/L",
            ],
            "integrations": [
                ("Filtration", "Filter", "MonitorFilterPerformance", "SCADA (EcoStruxure)", "DCS (Rockwell PlantPAx)", "SCADA OPC-DA", "DCS OPC-UA", "API-led (Real-time)", "Medium"),
                ("Filtration", "Backwash", "InitiateBackwashSequence", "DCS (Rockwell PlantPAx)", "Filter Control System", "DCS OPC-UA", "Filter PLC", "API-led (Real-time)", "High"),
                ("Filtration", "Chlorine", "AnalyzeChlorineResidual", "Chlorine Analyzer", "SCADA (EcoStruxure)", "Analyzer 4-20mA", "SCADA Modbus TCP", "API-led (Real-time)", "Medium"),
                ("Filtration", "CT", "CalculateCTValue", "SCADA (EcoStruxure)", "DCS (Rockwell PlantPAx)", "SCADA API (REST)", "DCS OPC-UA", "API-led (Real-time)", "High"),
                ("Filtration", "Clearwell", "MonitorClearwellLevel", "Clearwell Level Sensor", "SCADA (EcoStruxure)", "Sensor 4-20mA", "SCADA Modbus RTU", "API-led (Real-time)", "Simple"),
                ("Filtration", "pH", "AdjustFinishedWaterpH", "DCS (Rockwell PlantPAx)", "Chemical Dosing System", "DCS OPC-UA", "Dosing Pump PLC", "API-led (Real-time)", "Simple"),
                ("Filtration", "Compliance", "LogFinishedWaterQuality", "SCADA (EcoStruxure)", "Compliance Database", "SCADA API (REST)", "SQL JDBC", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-FL-01", "Verify filter effluent turbidity <0.3 NTU for all operating filters", "MonitorFilterPerformance", "All filters below 0.3 NTU except those in backwash", "High"),
                ("AC-FL-02", "Validate CT value meets regulatory minimum for Giardia inactivation (CT≥90)", "CalculateCTValue", "CT value meets or exceeds regulatory requirement", "High"),
                ("AC-FL-03", "Confirm backwash sequence completes within 20 minutes without operator intervention", "InitiateBackwashSequence", "Backwash completes automatically in ≤20 min", "Medium"),
                ("AC-FL-04", "Ensure clearwell detention time >30 minutes at peak flow", "MonitorClearwellLevel", "Clearwell volume provides ≥30 min detention at max flow", "Medium"),
            ],
        }),
        ("5.3", {
            "title": "Plant Maintenance & CIP (Clean-in-Place)",
            "description": "Maintenance team plans and executes preventive maintenance on plant equipment including pumps, valves, chemical systems, and instrumentation. Clean-in-Place (CIP) operations are managed for membrane systems.",
            "actors": ["Maintenance Manager", "Plant Operator", "Vendor Technician"],
            "systems": ["CMMS (IBM Maximo)", "SCADA (EcoStruxure)", "DCS (Rockwell PlantPAx)", "Vendor Portal", "Inventory System"],
            "mermaid": [
                "MaintMgr->>CMMS: Review PM schedule\npump PM due: PUMP-2026-001, 2500 hrs runtime",
                "CMMS->>SCADA: Check pump runtime\nPUMP-2026-001: 2,480 hrs, due at 2,500",
                "SCADA->>CMMS: Runtime confirmed\nstill running, schedule shutdown",
                "MaintMgr->>CMMS: Create work order\nWO-2026-002, pump overhaul, priority=Medium",
                "CMMS->>Inventory: Reserve parts\nmechanical seal, bearings, gaskets",
                "Inventory->>CMMS: Parts reserved\nbin=B-42, quantity=1 kit",
                "MaintMgr->>Operator: Coordinate shutdown\nPUMP-2026-001, Sunday 02:00-06:00",
                "Operator->>DCS: Prepare for shutdown\nstart standby pump, open crossover valve",
                "DCS->>Operator: Standby pump online\nPUMP-2026-002: 2,400 GPM, normal",
                "Operator->>DCS: Isolate PUMP-001\nclose suction valve, close discharge valve",
                "DCS->>Operator: PUMP-001 isolated\nLOTO applied, energy isolated",
                "MaintMgr->>Vendor: Schedule tech visit\nseal replacement, calibration",
                "Vendor->>CMMS: Tech dispatched\nETA=07:00, duration=4 hrs",
                "Tech->>CMMS: Work complete\nseal replaced, bearings OK, test run=pass",
                "MaintMgr->>CMMS: Close WO\nPUMP-001 returned to service, runtime reset=0",
            ],
            "integrations": [
                ("Maintenance", "PM", "CheckPMPriority", "CMMS (IBM Maximo)", "SCADA (EcoStruxure)", "Maximo API (REST)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
                ("Maintenance", "WO", "CreateWorkOrder", "CMMS (IBM Maximo)", "CMMS (IBM Maximo)", "Internal", "Internal", "API-led (Real-time)", "Simple"),
                ("Maintenance", "Parts", "ReserveSpareParts", "CMMS (IBM Maximo)", "Inventory System", "Maximo API (REST)", "Inventory API (SOAP)", "API-led (Real-time)", "Simple"),
                ("Maintenance", "Shutdown", "CoordinatePumpShutdown", "CMMS (IBM Maximo)", "DCS (Rockwell PlantPAx)", "Maximo API (REST)", "DCS OPC-UA", "Event-driven", "Medium"),
                ("Maintenance", "Isolation", "IsolateEquipment", "Operator HMI", "DCS (Rockwell PlantPAx)", "HMI API", "DCS OPC-UA", "API-led (Real-time)", "High"),
                ("Maintenance", "Vendor", "DispatchTech", "CMMS (IBM Maximo)", "Vendor Portal", "Maximo API (REST)", "Vendor API (REST)", "Event-driven", "Medium"),
                ("Maintenance", "Close", "CloseWorkOrder", "Tech Mobile App", "CMMS (IBM Maximo)", "Mobile API (OAuth2)", "Maximo API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-MT-01", "Verify PM completion rate >90% of scheduled tasks within window", "CheckPMPriority", "At least 90% of PMs completed within scheduled period", "Medium"),
                ("AC-MT-02", "Validate LOTO (Lock-Out/Tag-Out) compliance before equipment isolation", "IsolateEquipment", "Zero energy verified before maintenance begins", "High"),
                ("AC-MT-03", "Confirm spare parts availability >95% for critical equipment", "ReserveSpareParts", "Critical parts in stock or on order with ETA", "Medium"),
                ("AC-MT-04", "Ensure work order closure includes test run results and parts consumed", "CloseWorkOrder", "WO complete with test results and parts used", "Medium"),
            ],
        }),
        ("5.4", {
            "title": "Water Quality Compliance & Reporting",
            "description": "Laboratory team analyzes water samples throughout the treatment process and distribution system. Compliance reports are prepared for state and federal regulators covering SDWA (Safe Drinking Water Act) requirements.",
            "actors": ["Lab Manager", "Compliance Officer", "Plant Manager", "State Regulator"],
            "systems": ["LIMS (Lab Information System)", "SCADA (EcoStruxure)", "Compliance Reporting System", "State Drinking Water Portal (SDWIS)"],
            "mermaid": [
                "LabTech->>LIMS: Enter sample results\nWQ-2026-001: pH=7.2, turbidity=0.08 NTU",
                "LIMS->>SCADA: Cross-reference online\nonline Cl2=0.85 mg/L vs lab=0.82 mg/L",
                "SCADA->>LIMS: Correlation valid\nwithin 5%, all parameters match",
                "Operator->>SCADA: Collect distribution sample\nSP-2026-001: 123 Oak Street, routine",
                "SCADA->>LIMS: Sample logged\nbottle=batch-42, chain-of-custody",
                "LIMS->>Compliance: Review sample plan\nmonthly: 30 bacteriological, 5 chemical",
                "Compliance->>LIMS: Schedule additional\ntesting: lead/copper, quarterly due",
                "LabTech->>LIMS: Analyze coliform\npresence/absence: negative",
                "LIMS->>Compliance: Bacteriological results\nall 30 samples: absent, compliant",
                "Compliance->>State: Submit monthly report\nSDWIS format: WTP-2026-001",
                "State->>Compliance: Report accepted\nno violations, next report=August 5",
                "Compliance->>LIMS: Archive compliance data\nmonthly, per 40 CFR Part 141",
                "PlantMgr->>Compliance: Request compliance summary\n2026-Q2: 100% compliant",
                "Compliance->>PlantMgr: Q2 Report\nno MCL violations, all monitoring complete",
                "LIMS->>Historian: Archive lab results\nWQ-2026-001 through WQ-2026-060",
                "Compliance->>SCADA: Update control limits\nCl2 min=0.2 mg/L, max=4.0 mg/L",
            ],
            "integrations": [
                ("Water Quality", "Sample", "EnterLabResults", "LIMS", "SCADA (EcoStruxure)", "LIMS API (REST)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
                ("Water Quality", "Correlation", "CrossReferenceOnline", "SCADA (EcoStruxure)", "LIMS", "SCADA API (REST)", "LIMS API (REST)", "API-led (Real-time)", "Medium"),
                ("Water Quality", "Sampling", "CollectDistributionSample", "Operator Mobile App", "SCADA (EcoStruxure)", "Mobile API (OAuth2)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
                ("Water Quality", "Bacteriological", "AnalyzeColiformSample", "LIMS", "LIMS", "Internal", "Internal", "API-led (Real-time)", "High"),
                ("Water Quality", "Reporting", "SubmitSDWISReport", "Compliance System", "State Drinking Water Portal (SDWIS)", "Compliance API (REST)", "SDWIS API (SOAP)", "Batch (Scheduled)", "High"),
                ("Water Quality", "Archive", "ArchiveComplianceData", "Compliance System", "LIMS", "Compliance API (REST)", "LIMS API (REST)", "Batch (Scheduled)", "Simple"),
                ("Water Quality", "Limits", "UpdateControlLimits", "Compliance System", "SCADA (EcoStruxure)", "Compliance API (REST)", "SCADA API (REST)", "Event-driven", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-WQ-01", "Validate lab results within ±5% of online analyzer values for critical parameters", "CrossReferenceOnline", "Lab vs online correlation within 5% for all parameters", "High"),
                ("AC-WQ-02", "Verify monthly bacteriological sample count meets regulatory minimum (30/month)", "AnalyzeColiformSample", "At least 30 bacteriological samples collected and analyzed monthly", "High"),
                ("AC-WQ-03", "Confirm SDWIS report submission before regulatory deadline (10th of month)", "SubmitSDWISReport", "State acknowledges receipt before monthly deadline", "High"),
                ("AC-WQ-04", "Ensure all MCL violations are reported to state within 24 hours", "SubmitSDWISReport", "No unreported MCL violations", "High"),
            ],
        }),
    ]),
}

SECTION_DATA["WaterDistribution"] = {
    "title": "Water Distribution Network Management - `UT-WDM` `UT-WQM`",
    "description": "Management of the potable water distribution system including pressure zone management, reservoir tank level control, leak detection, flow monitoring, and hydrant/valve operations for the water utility network.",
    "capabilities": ["UT-WDM", "UT-WQM"],
    "subflows": OrderedDict([
        ("6.1", {
            "title": "Pressure Zone Management & SCADA",
            "description": "Operators monitor and control pressure zones across the distribution network. Pressure reducing valves (PRVs), booster pumps, and altitude valves are managed to maintain optimal pressure ranges throughout the system.",
            "actors": ["Distribution Operator", "Field Technician", "Hydraulic Engineer"],
            "systems": ["SCADA (Schneider EcoStruxure)", "Pressure Monitoring System", "PRV Controllers", "Pump Station PLCs", "Hydraulic Model"],
            "mermaid": [
                "Operator->>SCADA: Check pressure zones\nZone 3: 65 psi, Zone 4: 52 psi, Zone 5: 78 psi",
                "SCADA->>PRV_Zone3: Read downstream pressure\nPRV-2026-001: 65 psi, setpoint=60 psi",
                "PRV_Zone3->>SCADA: PRV status\nopen=42%, flow=1.2 MGD, valve=normal",
                "Operator->>SCADA: Zone 4 low pressure\n52 psi, min=55 psi threshold",
                "SCADA->>PumpStation: Start booster\nPS-OAK: PUMP-2026-002, 2,500 GPM",
                "PumpStation->>SCADA: Booster online\nPUMP-002: 2,450 GPM, discharge=72 psi",
                "SCADA->>Operator: Zone 4 pressure rising\n54 psi, 56 psi, 58 psi... stabilizing at 62 psi",
                "Operator->>SCADA: Zone 5 high pressure\n78 psi, max=80 psi, advisory",
                "SCADA->>PRV_Zone5: Reduce setpoint\nPRV-2026-002: 78→72 psi",
                "PRV_Zone5->>SCADA: Adjusting\nopen=38→32%, downstream=74 psi",
                "SCADA->>Operator: All zones stable\nZone 3: 62 psi, Zone 4: 62 psi, Zone 5: 72 psi",
                "Operator->>Hydraulic: Run pressure model\nZone 4: expected=60 psi, actual=62 psi (±3%)",
                "Hydraulic->>Operator: Model validated\ncorrelates with SCADA, no anomalies",
                "Operator->>SCADA: Log pressure event\nZone 4 low pressure, duration=18 min, cause=valve closed",
                "SCADA->>Historian: Archive trend\n24-hr pressure: Zone 3,4,5, daily report",
                "FieldTech->>SCADA: Field check complete\nPRV-2026-001: mechanical OK, no leaks",
            ],
            "integrations": [
                ("Pressure", "PRV", "MonitorPRVDownstream", "SCADA (EcoStruxure)", "PRV Controller (Zone 3)", "SCADA Modbus RTU", "PRV Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Pressure", "Booster", "StartBoosterPump", "SCADA (EcoStruxure)", "Pump Station PLC", "SCADA Modbus TCP", "PLC Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Pressure", "Monitoring", "MonitorZonePressure", "SCADA (EcoStruxure)", "Operator HMI", "SCADA API (REST)", "HMI Display", "API-led (Real-time)", "Simple"),
                ("Pressure", "PRV", "AdjustPRVSetpoint", "SCADA (EcoStruxure)", "PRV Controller (Zone 5)", "SCADA Modbus RTU", "PRV Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Pressure", "Model", "ValidateHydraulicModel", "Hydraulic Model Software", "SCADA (EcoStruxure)", "Model API (REST)", "SCADA API (REST)", "Batch (Real-time)", "Medium"),
                ("Pressure", "Log", "LogPressureEvent", "SCADA (EcoStruxure)", "Plant Historian (OSIsoft PI)", "SCADA API (REST)", "PI API (REST)", "Event-driven", "Simple"),
                ("Pressure", "Field", "ConfirmFieldCheck", "Field Tech Mobile App", "SCADA (EcoStruxure)", "Mobile API (OAuth2)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-PZ-01", "Verify all pressure zones maintain pressure between 40-80 psi at critical nodes", "MonitorZonePressure", "All critical nodes within 40-80 psi range 99.5% of time", "High"),
                ("AC-PZ-02", "Validate pressure recovery time under 30 minutes after low-pressure event", "StartBoosterPump", "Pressure returns to >55 psi within 30 min", "Medium"),
                ("AC-PZ-03", "Confirm hydraulic model accuracy within ±5% of actual SCADA readings", "ValidateHydraulicModel", "Model vs actual pressure difference <5%", "Medium"),
                ("AC-PZ-04", "Ensure PRV setpoint changes are logged with operator ID and reason", "AdjustPRVSetpoint", "Complete audit trail for every PRV adjustment", "Medium"),
            ],
        }),
        ("6.2", {
            "title": "Leak Detection & Flow Monitoring",
            "description": "The utility monitors distribution system flows to detect leaks, manage non-revenue water (NRW), and optimize system operations. District Metered Areas (DMAs) are analyzed for minimum night flow to identify potential leaks.",
            "actors": ["Water Loss Engineer", "Distribution Operator", "Field Technician"],
            "systems": ["SCADA (EcoStruxure)", "DMA Flow Analyzer", "Acoustic Leak Detection", "GIS (ArcGIS)", "Hydraulic Model"],
            "mermaid": [
                "Operator->>SCADA: Review DMA flows\nDMA-3: inflow=1.2 MGD, night flow=0.35 MGD",
                "SCADA->>DMA: Analyze minimum night flow\n02:00-04:00: 0.35 MGD, baseline=0.20 MGD",
                "DMA->>Operator: Alert: possible leak\nMNF=0.35, baseline=0.20, delta=0.15 MGD",
                "Operator->>GIS: Identify DMA-3 pipes\nzone=3, pipe=PIPE-2026-001, ductile iron 24\"",
                "GIS->>Operator: Pipe details\ninstalled=1985, length=3,200 ft, material=Ductile Iron",
                "Operator->>Acoustic: Deploy leak sensors\nDMA-3, 8 sensors, night survey",
                "Acoustic->>FieldTech: Correlate signals\nleak candidate: 2,200 ft from valve V-42",
                "FieldTech->>Acoustic: Confirm leak\nPIPE-2026-001, leak rate=25 GPM",
                "FieldTech->>SCADA: Log leak found\nPIPE-2026-001, 25 GPM, priority=Medium",
                "Operator->>DMA: Isolate leak zone\nclose valve V-42 and V-43",
                "DMA->>SCADA: Isolation confirmed\nDMA-3 inflow dropped to 0.85 MGD",
                "Operator->>Work: Create repair WO\nWO-2026-003, pipe repair, crew dispatched",
                "FieldTech->>SCADA: Repair complete\nclamp installed, test pressure=80 psi",
                "SCADA->>DMA: Verify night flow\npost-repair MNF=0.22 MGD (baseline=0.20)",
                "DMA->>Operator: Leak resolved\nNRW reduction: 25 GPM, 13 MG/year saved",
            ],
            "integrations": [
                ("Leak", "DMA", "AnalyzeMinimumNightFlow", "SCADA (EcoStruxure)", "DMA Flow Analyzer", "SCADA API (REST)", "DMA API (REST)", "Batch (Scheduled)", "High"),
                ("Leak", "Alert", "FlagLeakCandidate", "DMA Flow Analyzer", "Operator Console", "DMA API (REST)", "SCADA HMI", "Event-driven", "High"),
                ("Leak", "GIS", "IdentifyPipeAsset", "GIS (ArcGIS)", "Operator Console", "GIS API (REST)", "SCADA HMI", "API-led (Real-time)", "Simple"),
                ("Leak", "Acoustic", "DeployLeakSensors", "Acoustic Leak Detection System", "Field Tech Mobile App", "Acoustic API (REST)", "Mobile API (OAuth2)", "API-led (Real-time)", "Medium"),
                ("Leak", "Isolation", "IsolateLeakZone", "SCADA (EcoStruxure)", "Valve Controllers", "SCADA Modbus RTU", "Valve PLC Modbus", "API-led (Real-time)", "Medium"),
                ("Leak", "Repair", "CreateRepairWorkOrder", "Operator Console", "CMMS (IBM Maximo)", "SCADA API (REST)", "Maximo API (REST)", "Event-driven", "Simple"),
                ("Leak", "NRW", "CalculateNRWReduction", "DMA Flow Analyzer", "Water Loss System", "DMA API (REST)", "Water Loss API", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-LK-01", "Detect leaks >10 GPM within 48 hours of occurrence", "AnalyzeMinimumNightFlow", "DMA alerts for leak candidates within 48 hrs", "High"),
                ("AC-LK-02", "Validate minimum night flow is <25% of average daily flow for each DMA", "FlagLeakCandidate", "MNF/Average Daily Flow ratio <0.25", "Medium"),
                ("AC-LK-03", "Confirm leak location accuracy within 10 ft of actual pipe", "DeployLeakSensors", "Correlation pinpoints leak within 10 ft", "Medium"),
                ("AC-LK-04", "Ensure NRW is below 15% of system input volume", "CalculateNRWReduction", "Annual NRW below 15% of total production", "High"),
            ],
        }),
        ("6.3", {
            "title": "Reservoir & Tank Level Control",
            "description": "Operators manage elevated storage tanks and ground reservoirs to maintain water levels, ensure fire flow capacity, and optimize pumping schedules for energy efficiency.",
            "actors": ["Distribution Operator", "Energy Manager", "Pump Station Technician"],
            "systems": ["SCADA (EcoStruxure)", "Tank Level Sensors", "Pump Station PLCs", "Energy Management System (EMS)", "Hydraulic Model"],
            "mermaid": [
                "Operator->>SCADA: Check tank levels\nTank-1: 42 ft (72%), Tank-2: 28 ft (55%)",
                "SCADA->>TankSensor: Read levels\nelevated tank: 42 ft, ground tank: 28 ft",
                "TankSensor->>SCADA: Levels confirmed\nTank-1=42.3 ft, Tank-2=28.1 ft",
                "Operator->>SCADA: Night fill schedule\nfill Tank-1: 23:00-05:00, fill target=85%",
                "SCADA->>PumpPLC: Start fill pump\nPS-MAIN: 2 pumps @ 3,000 GPM each",
                "PumpPLC->>SCADA: Pumps running\n2 pumps: 5,800 GPM, discharge=80 psi",
                "SCADA->>Operator: Filling progress\nTank-1: 42 ft → 47 ft → 52 ft",
                "EnergyMgr->>EMS: Check energy rates\non-peak=$0.12/kWh, off-peak=$0.06/kWh",
                "EMS->>Operator: Off-peak window\n23:00-05:00: fill to 90%, save $240/night",
                "Operator->>SCADA: Extend fill target\nfill to 90% by 05:00, optimize pump combo",
                "SCADA->>PumpPLC: Adjust pump combo\n2 pumps @ 3,000 GPM → 1 pump @ 4,200 GPM (VFD)",
                "PumpPLC->>SCADA: VFD speed=58 Hz\n4,100 GPM, 65 kW vs 2 pumps=110 kW",
                "SCADA->>Operator: Level rising per plan\nTank-1: 85% at 03:00, on track for 90%",
                "Operator->>SCADA: Morning draw begins\n06:00: Tank-1=87%, demand=6.5 MGD",
                "SCADA->>Operator: Tank cycle complete\nTank-1: max=90% (05:00), min=40% (18:00)",
            ],
            "integrations": [
                ("Tank", "Level", "ReadTankLevel", "Tank Level Sensor", "SCADA (EcoStruxure)", "Sensor 4-20mA", "SCADA Modbus RTU", "API-led (Real-time)", "Simple"),
                ("Tank", "Fill", "StartNightFillPump", "SCADA (EcoStruxure)", "Pump Station PLC", "SCADA Modbus TCP", "PLC Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Tank", "Energy", "CheckOffPeakRates", "Energy Management System", "SCADA (EcoStruxure)", "EMS API (REST)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
                ("Tank", "Optimization", "AdjustPumpCombo", "SCADA (EcoStruxure)", "Pump VFD", "SCADA Modbus TCP", "VFD Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Tank", "Schedule", "MonitorFillProgress", "SCADA (EcoStruxure)", "Operator HMI", "SCADA API (REST)", "HMI Display", "API-led (Real-time)", "Simple"),
                ("Tank", "Draw", "MonitorMorningDraw", "SCADA (EcoStruxure)", "Plant Historian (OSIsoft PI)", "SCADA API (REST)", "PI API (REST)", "API-led (Real-time)", "Simple"),
                ("Tank", "Optimization", "CalculateEnergySavings", "Energy Management System", "Plant Historian (OSIsoft PI)", "EMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-TK-01", "Verify tank levels return to target fill level by end of off-peak window (05:00)", "StartNightFillPump", "Tank reaches ≥90% by 05:00", "Medium"),
                ("AC-TK-02", "Validate minimum storage capacity for fire flow (per NFPA 22)", "ReadTankLevel", "Tank never drops below fire storage reserve level", "High"),
                ("AC-TK-03", "Confirm energy cost savings ≥15% vs day-fill schedule", "CalculateEnergySavings", "Night-fill reduces pumping energy cost by ≥15%", "Medium"),
                ("AC-TK-04", "Ensure pump cycling frequency stays below 6 starts/hour", "AdjustPumpCombo", "Pump starts ≤6 per hour to prevent motor damage", "Medium"),
            ],
        }),
        ("6.4", {
            "title": "Hydrant & Valve Operations",
            "description": "Field crews perform hydrant flushing and flow testing, valve exercising, and main breaks response. GIS tracks asset location and condition. SCADA monitors system impacts during operations.",
            "actors": ["Field Crew Lead", "Distribution Operator", "Hydrant Tester"],
            "systems": ["GIS (ArcGIS)", "Mobile Field App", "SCADA (EcoStruxure)", "CMMS (IBM Maximo)", "Hydrant Management System"],
            "mermaid": [
                "FieldCrew->>Mobile: Check valve exercise schedule\nVALV-2026-001 through 010, quarterly exercise",
                "Mobile->>GIS: Navigate to valve\nVALV-2026-003: 123 Oak St, butterfly 16\"",
                "FieldCrew->>Mobile: Exercise valve\nturn counterclockwise 5 turns, torque=30 ft-lbs",
                "Mobile->>CMMS: Log valve exercise\nVALV-2026-003: op=Normal, turns=5, torque=30",
                "FieldCrew->>Mobile: Hydrant flow test\nHYD-2026-001: static=62 psi, residual=48 psi, flow=950 GPM",
                "Mobile->>SCADA: Alert system\nhydrant flow test, zone=3, duration=10 min",
                "SCADA->>Operator: Flow test in progress\nZone 3: drop 62→58 psi, expected, ignore alarm",
                "Mobile->>HydrantSys: Log flow test results\nHYD-2026-001: A=62, B=48, C=950 GPM",
                "HydrantSys->>Operator: Update C-factor\npipe PIPE-2026-001: C=110, condition=Good",
                "Operator->>GIS: Update hydrant data\nHYD-2026-001: last test=2026-07-07, flow=950 GPM",
                "FieldCrew->>Mobile: Main break report\nPIPE-2026-002: 16\" ductile iron, leak visible",
                "Mobile->>SCADA: Emergency alert\nmain break, Zone 4, isolate valves V-44 and V-45",
                "SCADA->>Operator: Main break isolation\nvalves V-44 and V-45 closed, 50 customers affected",
                "Operator->>FieldCrew: Isolation confirmed\nproceed with repair, water outage notice sent",
                "FieldCrew->>CMMS: Create emergency WO\nWO-2026-004, pipe repair, damage assessed",
            ],
            "integrations": [
                ("Hydrant", "Valve", "ExerciseValve", "Field Crew Mobile App", "GIS (ArcGIS)", "Mobile API (OAuth2)", "GIS API (REST)", "API-led (Real-time)", "Simple"),
                ("Hydrant", "Exercise", "LogValveExercise", "Field Crew Mobile App", "CMMS (IBM Maximo)", "Mobile API (OAuth2)", "Maximo API (REST)", "API-led (Real-time)", "Simple"),
                ("Hydrant", "FlowTest", "RecordHydrantFlowTest", "Field Crew Mobile App", "SCADA (EcoStruxure)", "Mobile API (OAuth2)", "SCADA API (REST)", "API-led (Real-time)", "Medium"),
                ("Hydrant", "CFactor", "UpdatePipeCFactor", "Hydrant Management System", "GIS (ArcGIS)", "Hydrant API (REST)", "GIS API (REST)", "API-led (Real-time)", "Simple"),
                ("Hydrant", "MainBreak", "AlertMainBreak", "Field Crew Mobile App", "SCADA (EcoStruxure)", "Mobile API (OAuth2)", "SCADA API (REST)", "Event-driven", "High"),
                ("Hydrant", "Isolation", "IsolateMainBreak", "SCADA (EcoStruxure)", "Valve Controllers", "SCADA Modbus RTU", "Valve PLC Modbus", "API-led (Real-time)", "High"),
                ("Hydrant", "WO", "CreateEmergencyWorkOrder", "Field Crew Mobile App", "CMMS (IBM Maximo)", "Mobile API (OAuth2)", "Maximo API (REST)", "Event-driven", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-HV-01", "Complete valve exercising within annual schedule (all valves every 12 months)", "ExerciseValve", "100% of valves exercised within 12-month cycle", "Medium"),
                ("AC-HV-02", "Verify hydrant flow test data accuracy within ±5% (flow) and ±2 psi (pressure)", "RecordHydrantFlowTest", "Calibrated pitot gauge and pressure gauge used", "Medium"),
                ("AC-HV-03", "Confirm main break isolation time under 45 minutes from notification", "AlertMainBreak", "Valves closed within 45 min of break notification", "High"),
                ("AC-HV-04", "Ensure affected customers notified within 30 minutes of isolation", "IsolateMainBreak", "Customer notification sent ≤30 min after isolation", "High"),
            ],
        }),
    ]),
}

SECTION_DATA["Wastewater"] = {
    "title": "Wastewater Collection & Treatment - `UT-WWC` `UT-WQM`",
    "description": "Management of wastewater collection system (lift stations, force mains, gravity sewers) and wastewater treatment processes (primary, secondary, tertiary treatment, and biosolids management) with regulatory effluent compliance.",
    "capabilities": ["UT-WWC", "UT-WQM"],
    "subflows": OrderedDict([
        ("7.1", {
            "title": "Collection System SCADA (Lift Stations)",
            "description": "Operators monitor and control wastewater lift stations across the collection network. SCADA system tracks wet well levels, pump status, flow rates, and alarms for overflow prevention.",
            "actors": ["Collection System Operator", "Field Technician", "Maintenance Supervisor"],
            "systems": ["SCADA (Schneider EcoStruxure)", "Lift Station PLCs", "Level Sensors", "Flow Meters", "CMMS (IBM Maximo)"],
            "mermaid": [
                "Operator->>SCADA: View collection system\n20 lift stations online, 3 standby",
                "SCADA->>LS_01: Read wet well level\nLS-2026-001: 8.2 ft, high level=10 ft",
                "LS_01->>SCADA: Level rising\ninflow=600 GPM, pump 1 running",
                "SCADA->>Operator: LS-001 status\npump 1: 580 GPM, pump 2: standby, level=8.5 ft",
                "Operator->>SCADA: Start pump 2\nLS-001: add pump, level rising above 9 ft",
                "SCADA->>LS_01: Start pump 2\nlead/lag: pump 2 start, sequence B",
                "LS_01->>SCADA: Pump 2 online\n1,150 GPM total, level=8.7 ft and dropping",
                "Operator->>SCADA: Check LS-007 alarm\nhigh level alarm, LS-2026-007, level=9.8 ft",
                "SCADA->>LS_07: Read status\npump 1 failed, pump 2 running solo",
                "Operator->>SCADA: LS-007 emergency\nlevel=9.8 ft, approaching overflow (10 ft)",
                "Operator->>SCADA: Dispatch crew\nCREW-2026-001, LS-007, pump failure",
                "Crew->>LS_07: Onsite assessment\npump 1: thermal overload tripped, reset",
                "LS_07->>SCADA: Pump 1 restored\n2 pumps running: 800 GPM total",
                "SCADA->>Operator: LS-007 stable\nlevel dropping: 9.5→9.0→8.2 ft",
                "Operator->>CMMS: Create PM work order\nLS-007 pump 1: investigate overload cause",
                "SCADA->>Historian: Log event\nLS-007 high level, duration=22 min, cause=pump trip",
            ],
            "integrations": [
                ("LiftStation", "Level", "ReadWetWellLevel", "Level Sensor (LS-001)", "Lift Station PLC (LS-001)", "Sensor 4-20mA", "PLC Analog Input", "API-led (Real-time)", "Simple"),
                ("LiftStation", "Pump", "StartLiftStationPump", "SCADA (EcoStruxure)", "Lift Station PLC (LS-001)", "SCADA Modbus TCP", "PLC Modbus RTU", "API-led (Real-time)", "Medium"),
                ("LiftStation", "Alarm", "MonitorHighLevelAlarm", "Lift Station PLC (LS-007)", "SCADA (EcoStruxure)", "PLC Modbus RTU", "SCADA Modbus TCP", "Event-driven", "High"),
                ("LiftStation", "Dispatch", "DispatchCrew", "SCADA (EcoStruxure)", "CMMS (IBM Maximo)", "SCADA API (REST)", "Maximo API (REST)", "Event-driven", "Medium"),
                ("LiftStation", "Field", "OnsiteAssessment", "Field Tech Mobile App", "CMMS (IBM Maximo)", "Mobile API (OAuth2)", "Maximo API (REST)", "API-led (Real-time)", "Simple"),
                ("LiftStation", "PM", "CreatePmWorkOrder", "SCADA (EcoStruxure)", "CMMS (IBM Maximo)", "SCADA API (REST)", "Maximo API (REST)", "Event-driven", "Simple"),
                ("LiftStation", "Log", "LogAlarmEvent", "SCADA (EcoStruxure)", "Plant Historian (OSIsoft PI)", "SCADA API (REST)", "PI API (REST)", "Event-driven", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-LS-01", "Verify all lift stations maintain wet well level below 90% of high-level setpoint", "ReadWetWellLevel", "No lift station exceeds high-level alarm threshold", "High"),
                ("AC-LS-02", "Validate pump run-time alternation to ensure equal wear across duty/standby pumps", "StartLiftStationPump", "Lead/lag alternation schedule maintained", "Medium"),
                ("AC-LS-03", "Confirm overflow prevention: no sanitary sewer overflows (SSOs) from lift stations", "MonitorHighLevelAlarm", "Zero SSO events from monitored lift stations", "High"),
                ("AC-LS-04", "Ensure crew dispatch and arrival on site within 60 minutes for high-priority alarms", "DispatchCrew", "Crew on-site within 60 min of alarm", "Medium"),
            ],
        }),
        ("7.2", {
            "title": "Wastewater Treatment Process Control",
            "description": "Operators manage the wastewater treatment process including primary clarification, biological treatment (activated sludge), secondary clarification, and disinfection (UV/chlorine). Process control parameters are continuously monitored and adjusted.",
            "actors": ["WWTP Operator", "Process Engineer", "Lab Technician"],
            "systems": ["DCS (Rockwell PlantPAx)", "SCADA (EcoStruxure)", "Biological Process Analyzer", "UV Disinfection System", "Aeration Control System"],
            "mermaid": [
                "Operator->>DCS: Review plant influent\nflow=18 MGD, BOD=220 mg/L, TSS=250 mg/L",
                "DCS->>SCADA: Primary clarifier status\nclarifier 1: sludge blanket=2.5 ft, effluent TSS=120",
                "SCADA->>Operator: Primary effluent\nBOD=140 mg/L, TSS=120 mg/L, removal=45%",
                "Operator->>DCS: Adjust aeration basin DO\nDO setpoint=2.0 mg/L, zone 1-4",
                "DCS->>Aeration: Increase blower speed\nblower 2: VFD 45 Hz → 52 Hz",
                "Aeration->>DCS: Air flow increased\n8,500 SCFM, DO zone 1: 1.8→2.1 mg/L",
                "DCS->>Operator: DO stabilized\nzones 1-4: avg=2.1 mg/L, ±0.2 mg/L",
                "Operator->>DCS: Check MLSS\nMLSS=3,200 mg/L, F/M ratio=0.25",
                "DCS->>BioAnalyzer: Measure SVI\nsludge volume index",
                "BioAnalyzer->>DCS: SVI=120 mL/g\nsettleability=good, no bulking",
                "Operator->>DCS: Adjust waste rate\nWAS flow=0.35 MGD, maintain SRT=8 days",
                "DCS->>Valve: Set WAS valve\nWAS-001: 35% open, 0.35 MGD",
                "Operator->>SCADA: Review secondary effluent\nTSS=15 mg/L, BOD=10 mg/L, NH3=1.2 mg/L",
                "SCADA->>UvSystem: Set UV dose\n30 mJ/cm², flow-paced, transmittance=68%",
                "UvSystem->>SCADA: UV dose confirmed\n29.8 mJ/cm², 2 banks online",
                "Operator->>Effluent: Final effluent quality\nCBOD=5 mg/L, TSS=8 mg/L, NH3=0.5 mg/L, E.coli=10 CFU",
            ],
            "integrations": [
                ("Treatment", "Influent", "MonitorPlantInfluent", "SCADA (EcoStruxure)", "DCS (Rockwell PlantPAx)", "SCADA OPC-DA", "DCS OPC-UA", "API-led (Real-time)", "Medium"),
                ("Treatment", "DO", "AdjustAerationDO", "DCS (Rockwell PlantPAx)", "Aeration Control System", "DCS OPC-UA", "Blower PLC Modbus", "API-led (Real-time)", "High"),
                ("Treatment", "SVI", "MeasureSludgeSettleability", "Biological Process Analyzer", "DCS (Rockwell PlantPAx)", "Analyzer Modbus RTU", "DCS OPC-UA", "API-led (Real-time)", "Medium"),
                ("Treatment", "WAS", "AdjustWasteActivatedSludge", "DCS (Rockwell PlantPAx)", "WAS Valve Actuator", "DCS OPC-UA", "Valve Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Treatment", "UV", "SetUvDose", "SCADA (EcoStruxure)", "UV Disinfection System", "SCADA Modbus TCP", "UV System Modbus", "API-led (Real-time)", "Medium"),
                ("Treatment", "Effluent", "MonitorFinalEffluent", "SCADA (EcoStruxure)", "Effluent Analyzers", "SCADA Modbus TCP", "Analyzer 4-20mA", "API-led (Real-time)", "High"),
                ("Treatment", "Compliance", "LogEffluentQuality", "DCS (Rockwell PlantPAx)", "Plant Historian (OSIsoft PI)", "DCS OPC-UA", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-WW-01", "Verify effluent BOD and TSS consistently below permit limits (30 mg/L each)", "MonitorFinalEffluent", "Daily average BOD <20 mg/L and TSS <20 mg/L", "High"),
                ("AC-WW-02", "Validate DO control maintains setpoint within ±0.3 mg/L across all aeration zones", "AdjustAerationDO", "DO within ±0.3 mg/L of setpoint 95% of time", "High"),
                ("AC-WW-03", "Confirm UV dose ≥30 mJ/cm² at peak flow for pathogen inactivation", "SetUvDose", "UV dose meets or exceeds 30 mJ/cm² at all flow conditions", "High"),
                ("AC-WW-04", "Ensure SRT maintained within ±1 day of target for biological process stability", "AdjustWasteActivatedSludge", "SRT between 7-9 days for target of 8 days", "Medium"),
            ],
        }),
        ("7.3", {
            "title": "Effluent Quality Compliance",
            "description": "Continuous monitoring of effluent quality parameters with real-time reporting to regulatory agencies. NPDES permit compliance is managed with automated sampling, data validation, and discharge reporting.",
            "actors": ["WWTP Operator", "Compliance Manager", "Lab Manager", "State Regulator"],
            "systems": ["SCADA (EcoStruxure)", "LIMS", "Compliance Reporting System", "EPA ICIS-NPDES Portal", "Online Analyzers"],
            "mermaid": [
                "Analyzer->>SCADA: Effluent reading\nCBOD=5 mg/L, TSS=8 mg/L, NH3=0.5 mg/L, pH=7.1",
                "SCADA->>Operator: Permit compliance check\nall parameters below NPDES limits",
                "Operator->>SCADA: Collect 24-hr composite\nauto-sampler bottle change, 4°C",
                "SCADA->>LIMS: Send composite to lab\nWQ-2026-042, 24-hr, flow-proportional",
                "LIMS->>SCADA: Lab results received\nCBOD=4.8, TSS=7.5, NH3=0.45",
                "SCADA->>Compliance: Validate results\nall within permit limits, DMR ready",
                "Compliance->>EPA: Submit monthly DMR\nNPDES Permit #IL0023456, June 2026",
                "EPA->>Compliance: DMR accepted\nno violations, no enforcement action",
                "Operator->>SCADA: Check for bypass event\nnone reported, wet weather flow=22 MGD",
                "SCADA->>Operator: Peak flow handling\nequalization basin in use, 4 MG stored",
                "Compliance->>SCADA: Update permit limits\nnew limits effective August 1: NH3=1.0 mg/L",
                "SCADA->>Operator: New limits logged\nadjust alarm setpoints: NH3=0.8 mg/L (warning)",
                "Operator->>SCADA: Review annual report\n100% compliance, 12 DMRs submitted",
                "SCADA->>Historian: Archive NPDES data\n12 months rolling, per permit requirement",
                "Compliance->>State: Submit annual report\n2026: 100% compliant, 0 violations",
            ],
            "integrations": [
                ("Effluent", "Analyzer", "ReadEffluentParameters", "Online Analyzers", "SCADA (EcoStruxure)", "Analyzer Modbus RTU", "SCADA Modbus TCP", "API-led (Real-time)", "Medium"),
                ("Effluent", "Composite", "CollectCompositeSample", "Auto-Sampler", "SCADA (EcoStruxure)", "Sampler Modbus", "SCADA Modbus TCP", "Batch (Scheduled)", "Simple"),
                ("Effluent", "Lab", "AnalyzeLabComposite", "LIMS", "SCADA (EcoStruxure)", "LIMS API (REST)", "SCADA API (REST)", "API-led (Real-time)", "Simple"),
                ("Effluent", "DMR", "SubmitMonthlyDMR", "Compliance System", "EPA ICIS-NPDES Portal", "Compliance API (REST)", "EPA CDX (SOAP)", "Batch (Scheduled)", "High"),
                ("Effluent", "Bypass", "MonitorWetWeatherFlow", "SCADA (EcoStruxure)", "Equalization Basin System", "SCADA Modbus TCP", "EQ Basin PLC Modbus", "API-led (Real-time)", "Medium"),
                ("Effluent", "Permit", "UpdatePermitLimits", "Compliance System", "SCADA (EcoStruxure)", "Compliance API (REST)", "SCADA API (REST)", "Event-driven", "Medium"),
                ("Effluent", "Archive", "ArchiveNpdesData", "SCADA (EcoStruxure)", "Plant Historian (OSIsoft PI)", "SCADA API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-EF-01", "Validate DMR submission before regulatory deadline (10th of month)", "SubmitMonthlyDMR", "DMR submitted and acknowledged by EPA before deadline", "High"),
                ("AC-EF-02", "Verify online analyzer calibration within ±10% of lab results for critical parameters", "AnalyzeLabComposite", "Lab vs online correlation within 10%", "Medium"),
                ("AC-EF-03", "Confirm no un-reported bypass events or NPDES excursions", "MonitorWetWeatherFlow", "All bypass events logged and reported per permit", "High"),
                ("AC-EF-04", "Ensure data retention of NPDES records meets minimum 3-year regulatory requirement", "ArchiveNpdesData", "All NPDES data archived for ≥3 years", "Medium"),
            ],
        }),
        ("7.4", {
            "title": "Biosolids Management",
            "description": "Operators manage the biosolids treatment process including thickening, anaerobic digestion, dewatering (centrifuge/belt press), and beneficial reuse or disposal. Gas production from digesters is monitored for energy recovery.",
            "actors": ["WWTP Operator", "Biosolids Coordinator", "Hauler", "Land Application Manager"],
            "systems": ["DCS (Rockwell PlantPAx)", "SCADA (EcoStruxure)", "Digester Control System", "Centrifuge PLC", "Biosolids Tracking System", "Weigh Scale"],
            "mermaid": [
                "Operator->>DCS: Review WAS inventory\nWAS flow=0.35 MGD, TSS=8,000 mg/L",
                "DCS->>Thickener: Start gravity belt\nfeed=200 GPM, polymer=8 GPH",
                "Thickener->>DCS: Thickened sludge\n5% solids, 80 GPM, capture=95%",
                "Operator->>DCS: Feed digester 1\nsludge vol=80,000 gal/day, temp=98°F",
                "DCS->>Digester: Start feed pump\n40 GPM, mesophilic digester 1",
                "Digester->>DCS: Gas production\nbiogas=85,000 CF/day, CH4=62%",
                "Operator->>DCS: Check digester temp\n98°F, target=98°F, within ±1°F",
                "DCS->>Operator: Digester stable\npH=7.1, VFA/ALK=0.08, gas=85,000 CF",
                "Operator->>DCS: Feed centrifuge\ndigested sludge: 4% solids, 60 GPM",
                "DCS->>Centrifuge: Start centrifuge\nbowl speed=2,500 RPM, polymer=12 GPH",
                "Centrifuge->>DCS: Cake solids\n22% solids, 15 wet tons/hr",
                "Operator->>BiosolidsSys: Record loadout\nsemi-trailer #42, 22.5 wet tons, Class B",
                "BiosolidsSys->>WeighScale: Net weight\n22.5 tons, transport to farm #12",
                "Operator->>SCADA: Log biosolids data\nmonthly: 450 wet tons, 22% solids",
                "SCADA->>Compliance: Biosolids report\n503 compliance: metals below limits",
                "Operator->>Digester: Adjust feed rate\nreduce to 35 GPM, stabilize VFA/ALK",
            ],
            "integrations": [
                ("Biosolids", "Thickening", "StartGravityBeltThickener", "DCS (Rockwell PlantPAx)", "Sludge Thickener PLC", "DCS OPC-UA", "Thickener PLC Modbus", "API-led (Real-time)", "Medium"),
                ("Biosolids", "Digester", "FeedAnaerobicDigester", "DCS (Rockwell PlantPAx)", "Digester Control System", "DCS OPC-UA", "Digester PLC Modbus", "API-led (Real-time)", "High"),
                ("Biosolids", "Gas", "MonitorBiogasProduction", "Digester Control System", "SCADA (EcoStruxure)", "Digester Modbus", "SCADA Modbus TCP", "API-led (Real-time)", "Medium"),
                ("Biosolids", "Dewatering", "StartCentrifuge", "DCS (Rockwell PlantPAx)", "Centrifuge PLC", "DCS OPC-UA", "Centrifuge Modbus RTU", "API-led (Real-time)", "Medium"),
                ("Biosolids", "Loadout", "RecordBiosolidsLoadout", "Biosolids Tracking System", "Weigh Scale System", "Biosolids API (REST)", "Scale API (Serial)", "API-led (Real-time)", "Simple"),
                ("Biosolids", "Compliance", "ReportBiosolids503", "SCADA (EcoStruxure)", "Compliance System", "SCADA API (REST)", "Compliance API (REST)", "Batch (Scheduled)", "High"),
                ("Biosolids", "Optimization", "AdjustDigesterFeedRate", "DCS (Rockwell PlantPAx)", "Digester Control System", "DCS OPC-UA", "Digester PLC Modbus", "API-led (Real-time)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-BS-01", "Verify digester temperature maintained at 98°F ±1°F for mesophilic operation", "FeedAnaerobicDigester", "Digester temp within 97-99°F range 99% of time", "High"),
                ("AC-BS-02", "Validate biosolids pathogen reduction meets Class B requirements (Part 503)", "ReportBiosolids503", "Fecal coliform <2M MPN/g dry solids", "High"),
                ("AC-BS-03", "Confirm centrifuge cake solids ≥20% for economical hauling", "StartCentrifuge", "Cake solids ≥20% averaged monthly", "Medium"),
                ("AC-BS-04", "Ensure trace metals in biosolids below 503 Table 3 ceiling concentrations", "ReportBiosolids503", "All metals below regulatory limits", "High"),
            ],
        }),
    ]),
}

SECTION_DATA["Metering"] = {
    "title": "Metering & Smart Grid - `UT-AMI` `UT-MDM` `UT-SGO` `UT-GBD`",
    "description": "Management of the advanced metering infrastructure (AMI) including head-end operations, meter data management (MDM), VEE processing, and Green Button data access for customer energy usage.",
    "capabilities": ["UT-AMI", "UT-MDM", "UT-SGO", "UT-GBD"],
    "subflows": OrderedDict([
        ("8.1", {
            "title": "AMI Head-End Operations",
            "description": "AMI head-end system manages two-way communication with smart meters across the service territory. System collects interval reads, processes time-of-use data, manages firmware updates, and monitors network health.",
            "actors": ["Metering Specialist", "Network Engineer", "Field Technician"],
            "systems": ["AMI Head-End (Itron OMS/IEE)", "Smart Meters (Itron OpenWay)", "Network Management System", "MDM"],
            "mermaid": [
                "Meter->>HeadEnd: Interval data push\nMTR-2026-001: 12.45 kWh, 15-min interval",
                "HeadEnd->>MDM: Validate reading\nMTR-001: 12.45 kWh, interval=15, quality=Good",
                "MDM->>HeadEnd: Acknowledged\nread_id=RDG-2026-001, timestamp valid",
                "Meter->>HeadEnd: Alarm: tamper\nMTR-2026-001: seal broken, enclosure open",
                "HeadEnd->>Operator: Tamper alert\nMTR-2026-001, 123 Oak Street, dispatch required",
                "Operator->>HeadEnd: Query meter status\ndiagnostics: battery=3.2V, RSSI=-72 dBm",
                "HeadEnd->>Meter: Ping command",
                "Meter->>HeadEnd: Online, FW=v4.2.1\nevents=12 (tamper=1, power quality=3, other=8)",
                "Operator->>HeadEnd: Schedule firmware update\nMTR-2026-001: v4.2.1 → v4.3.0",
                "HeadEnd->>Meter: Push firmware\n186 KB, ECC validation",
                "Meter->>HeadEnd: Update complete\nv4.3.0, reboot OK, normal operation",
                "Operator->>NetMgmt: Check RF network\n10,423 meters online, 12 offline",
                "NetMgmt->>Operator: Network health\n99.88% online, RSSI avg=-68 dBm",
                "Operator->>NetMgmt: Investigate offline\n12 meters: 8 in Area 3, possible interference",
                "FieldTech->>NetMgmt: Site survey\nArea 3: new structure blocking, install repeater",
                "HeadEnd->>MDM: Daily read summary\n10,423 meters, 99.3% reads collected",
            ],
            "integrations": [
                ("AMI", "Interval", "CollectIntervalRead", "Smart Meter (Itron OpenWay)", "AMI Head-End (Itron OMS/IEE)", "RF Mesh", "Head-End WAN", "Batch (Scheduled)", "High"),
                ("AMI", "VEE", "ValidateMeterReading", "AMI Head-End (Itron OMS/IEE)", "MDM", "Head-End API (SOAP)", "MDM API (REST)", "API-led (Real-time)", "Medium"),
                ("AMI", "Alarm", "ProcessTamperAlarm", "Smart Meter (Itron OpenWay)", "AMI Head-End (Itron OMS/IEE)", "RF Mesh", "Head-End Event Bus", "Event-driven", "High"),
                ("AMI", "Diagnostics", "QueryMeterDiagnostics", "AMI Head-End (Itron OMS/IEE)", "Smart Meter (Itron OpenWay)", "Head-End API (SOAP)", "RF Mesh", "API-led (Real-time)", "Simple"),
                ("AMI", "Firmware", "PushFirmwareUpdate", "AMI Head-End (Itron OMS/IEE)", "Smart Meter (Itron OpenWay)", "Head-End FW Server", "RF Mesh (Over-the-Air)", "Batch (Scheduled)", "Medium"),
                ("AMI", "Network", "MonitorNetworkHealth", "Network Management System", "Operator Console", "NetMgmt API (SNMP)", "SCADA HMI", "API-led (Real-time)", "Simple"),
                ("AMI", "Summary", "GenerateDailyReadSummary", "AMI Head-End (Itron OMS/IEE)", "MDM", "Head-End API (SOAP)", "MDM API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-AM-01", "Verify daily meter read success rate ≥99% of registered meters", "GenerateDailyReadSummary", "Daily read success rate at or above 99%", "High"),
                ("AC-AM-02", "Validate tamper alerts are processed and dispatched within 2 hours", "ProcessTamperAlarm", "Tamper alert to dispatch ≤2 hours", "Medium"),
                ("AC-AM-03", "Confirm firmware update completion rate ≥95% within scheduled window", "PushFirmwareUpdate", "95% of targeted meters updated successfully", "Medium"),
                ("AC-AM-04", "Ensure AMI network availability ≥99.5% (meters online/total registered)", "MonitorNetworkHealth", "Network availability meets 99.5% threshold", "High"),
            ],
        }),
    ]),
}
