"""Section data for Sections 1-4: Generation, Transmission, Substation, Distribution."""
from collections import OrderedDict

# Sections 1-4: Generation, Transmission, Substation, Distribution
SECTION_DATA = OrderedDict()

SECTION_DATA["Generation"] = {
    "title": "Power Generation & SCADA Operations",
    "description": "Monitor and control power generation assets including thermal (combined cycle gas turbine), hydro, and renewable generation. Manages real-time DCS/SCADA operations, automatic generation control (AGC), fuel management, and emissions monitoring across the generation fleet.",
    "capabilities": ["UT-TGC", "UT-RGM", "UT-GDA", "UT-FMG"],
    "subflows": OrderedDict([
        ("1.1", {
            "title": "Thermal Power Plant DCS/SCADA Operations",
            "description": "Control room operators monitor boiler, turbine, and generator parameters via distributed control system (DCS). SCADA system provides real-time data acquisition, alarm management, and historical trending for the thermal power plant.",
            "actors": ["Control Room Operator", "Shift Supervisor", "Plant Engineer"],
            "systems": ["DCS (ABB 800xA)", "SCADA (Siemens Spectrum Power)", "Plant Historian (OSIsoft PI)", "Alarm Management System"],
            "mermaid": [
                "Operator->>DCS: Monitor plant overview\nUnit 1: 500 MW, 98% load",
                "DCS->>DCS: Scan boiler parameters\nsteam_pressure=1800 psi, temp=1005\u00b0F",
                "DCS->>SCADA: Transmit telemetry\nGEN-2026-001: 250 MW, 3600 RPM",
                "SCADA->>Operator: Display overview\nPlant total: 498 MW, 4 units online",
                "Operator->>DCS: Adjust boiler firing rate\nincrease 2%, ramp=5 min",
                "DCS->>Boiler: Set fuel valve\nBLR-2026-001, valve_pos=72%",
                "Boiler->>DCS: Steam pressure response\n1805 psi, rising 1 psi/min",
                "DCS->>Turbine: Adjust governor\nTRB-2026-001, setpoint=250 MW",
                "Turbine->>DCS: Speed stable\n3600 RPM, vibration=0.02 in/s",
                "DCS->>Operator: Unit stable at 250 MW\ntemp=1005\u00b0F, efficiency=58.2%",
                "Alarm->>DCS: Bearing temp high\nTRB-2026-001, 195\u00b0F, alarm=Warning",
                "DCS->>Operator: Alert operator\nbearing temp rising, trend=+2\u00b0F/hr",
                "Operator->>DCS: Investigate alarm\ncheck lube oil, cooling water",
                "DCS->>Operator: Lube oil temp=140\u00b0F\ncooler valve 65% open",
                "Operator->>DCS: Open cooler valve\nset to 80%, monitor 15 min",
                "DCS->>SCADA: Update historian\nPID=PT-2026-001, value=3600",
            ],
            "integrations": [
                ("Thermal Plant", "Boiler", "MonitorBoilerParameters", "DCS (ABB 800xA)", "SCADA (Siemens Spectrum Power)", "DCS OPC-UA", "SCADA OPC-DA", "API-led (Real-time)", "High"),
                ("Thermal Plant", "Turbine", "AdjustGovernor", "DCS (ABB 800xA)", "Turbine Governor (Woodward)", "DCS Modbus TCP", "Governor Modbus RTU", "API-led (Real-time)", "High"),
                ("Thermal Plant", "Generator", "TransmitTelemetry", "SCADA (Siemens Spectrum Power)", "Plant Historian (OSIsoft PI)", "SCADA API (ICCP)", "PI Interface (OPC-DA)", "API-led (Real-time)", "Medium"),
                ("Thermal Plant", "Alarm", "AlertOperator", "DCS (ABB 800xA)", "Alarm Management System", "DCS OPC-A&E", "Alarm API (REST)", "Event-driven", "Medium"),
                ("Thermal Plant", "Setpoint", "AdjustBoilerFiringRate", "Operator HMI", "DCS (ABB 800xA)", "HMI API (OAuth2)", "DCS OPC-UA", "API-led (Real-time)", "Simple"),
                ("Thermal Plant", "Trend", "LogTrendData", "Plant Historian (OSIsoft PI)", "Reporting Database", "PI API (REST)", "SQL JDBC", "Batch (Scheduled)", "Simple"),
                ("Thermal Plant", "Performance", "CalculateEfficiency", "DCS (ABB 800xA)", "Plant Historian (OSIsoft PI)", "DCS OPC-UA", "PI API (REST)", "API-led (Real-time)", "Medium"),
                ("Thermal Plant", "Vibration", "MonitorVibration", "DCS (ABB 800xA)", "Condition Monitoring System", "DCS OPC-UA", "CMS API (Modbus TCP)", "API-led (Real-time)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-TP-01", "Validate real-time telemetry accuracy within \u00b10.5% of field values", "MonitorBoilerParameters", "Telemetry values match field instruments within tolerance", "High"),
                ("AC-TP-02", "Verify alarm response time under 30 seconds from event occurrence", "AlertOperator", "Alarms are displayed on HMI within 30s of trigger", "High"),
                ("AC-TP-03", "Confirm DCS-to-SCADA data latency below 1 second for critical points", "TransmitTelemetry", "PI historian shows data timestamp within 1s of DCS scan", "Medium"),
                ("AC-TP-04", "Ensure all operator setpoint changes are logged with user identity and timestamp", "AdjustBoilerFiringRate", "Audit trail shows user, value, time for every setpoint change", "Medium"),
            ],
        }),
        ("1.2", {
            "title": "Renewable Generation & Solar/Wind Integration",
            "description": "Operators monitor and control renewable generation assets including solar PV farms and wind turbines. The renewable management system handles variability forecasting, curtailment commands, and power quality compliance.",
            "actors": ["Renewable Operator", "Grid Integration Engineer", "ISO Scheduler"],
            "systems": ["Renewable Management System (GE Renewable)", "SCADA (Siemens Spectrum Power)", "Weather Forecasting Service", "ISO Market Portal"],
            "mermaid": [
                "REN_OP->>RMS: Monitor renewable fleet\nsolar=120 MW, wind=85 MW, total=205 MW",
                "RMS->>Weather: Fetch forecast\nnext 4 hours, solar irradiance, wind speed",
                "Weather->>RMS: Forecast data\nsolar: 100-130 MW, wind: 70-95 MW",
                "RMS->>SCADA: Transmit aggregated telemetry\nREN total: 205 MW, ramp rate=+2 MW/min",
                "SCADA->>ISO: Report generation\nSpringfield Renewable: 205 MW, 2026-07-07T10:00",
                "ISO->>SCADA: Curtailment order\nreduce to 180 MW, grid congestion",
                "SCADA->>RMS: Dispatch curtailment\nsetpoint=180 MW, ramp=10 min",
                "RMS->>SolarPV: Reduce inverter output\nDER-2026-001 to DER-2026-050: 80% setpoint",
                "RMS->>WindTurbine: Pitch control\nWTG-001 to WTG-020: feather blades",
                "SolarPV->>RMS: Acknowledged\n40 inverters: 80% output, total=96 MW",
                "WindTurbine->>RMS: Acknowledged\n20 turbines: 60% output, total=68 MW",
                "RMS->>SCADA: Curtailment complete\ntotal=164 MW, below 180 MW threshold",
                "SCADA->>ISO: Confirm curtailment\nSpringfield Renewable: 164 MW, compliant",
                "RMS->>Weather: Refresh forecast\nhourly, for next dispatch interval",
                "REN_OP->>RMS: Review curtailment report\nsolar curtailed 24 MW, wind curtailed 17 MW",
            ],
            "integrations": [
                ("Renewable", "Forecast", "FetchWeatherForecast", "RMS (GE Renewable)", "Weather Forecasting Service", "RMS API (REST)", "Weather API (REST)", "API-led (Real-time)", "Medium"),
                ("Renewable", "Curtailment", "ReceiveCurtailmentOrder", "ISO Market Portal", "SCADA (Siemens Spectrum Power)", "ISO API (ICCP)", "SCADA API (ICCP)", "Event-driven", "High"),
                ("Renewable", "Dispatch", "DispatchCurtailment", "SCADA (Siemens Spectrum Power)", "RMS (GE Renewable)", "SCADA API (ICCP)", "RMS API (Modbus TCP)", "API-led (Real-time)", "High"),
                ("Renewable", "Solar", "ReduceInverterOutput", "RMS (GE Renewable)", "Solar PV Inverters", "RMS API (Modbus TCP)", "Inverter API (SunSpec Modbus)", "API-led (Real-time)", "Medium"),
                ("Renewable", "Wind", "ActivatePitchControl", "RMS (GE Renewable)", "Wind Turbine Controllers", "RMS API (OPC-UA)", "Turbine API (IEC 61400-25)", "API-led (Real-time)", "Medium"),
                ("Renewable", "Compliance", "ConfirmCurtailment", "SCADA (Siemens Spectrum Power)", "ISO Market Portal", "SCADA API (ICCP)", "ISO API (REST)", "API-led (Real-time)", "Medium"),
                ("Renewable", "Report", "LogCurtailmentEvent", "RMS (GE Renewable)", "Plant Historian (OSIsoft PI)", "RMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-RG-01", "Verify curtailment order execution within mandated ramp time (10 min)", "ReceiveCurtailmentOrder", "Curtailment target achieved within ramp window", "High"),
                ("AC-RG-02", "Validate forecast accuracy within \u00b115% for 4-hour horizon", "FetchWeatherForecast", "Weather forecast accuracy meets threshold", "Medium"),
                ("AC-RG-03", "Confirm telemetry latency under 2 seconds from inverter to SCADA", "DispatchCurtailment", "SCADA reflects inverter changes within 2s", "Medium"),
                ("AC-RG-04", "Ensure curtailment events are logged with timestamp, setpoint, and actual", "ReduceInverterOutput", "Complete audit trail for every curtailment event", "Medium"),
            ],
        }),
        ("1.3", {
            "title": "Automatic Generation Control & Dispatch",
            "description": "The AGC system receives load frequency control signals from the ISO, calculates generator setpoints, and dispatches them to participating generators. Operators monitor ACE (Area Control Error) and ensure regulatory compliance.",
            "actors": ["System Operator", "ISO Operator", "Generator Dispatcher"],
            "systems": ["AGC (GE/Alstom)", "EMS (Siemens Spectrum Power)", "ISO RTO System", "SCADA", "Plant DCS"],
            "mermaid": [
                "EMS->>ISO: Receive ACE signal\nACE=+120 MW, bias=1%/0.1Hz",
                "ISO->>AGC: LFC dispatch request\nregulation up, 50 MW, ramp=5 min",
                "AGC->>AGC: Calculate setpoints\nGEN-001: +20 MW, GEN-002: +30 MW",
                "AGC->>SCADA: Dispatch raise commands\nAGC setpoint to each unit",
                "SCADA->>GEN001: Raise output 20 MW\nsetpoint=270 MW, ramp=2 MW/min",
                "SCADA->>GEN002: Raise output 30 MW\nsetpoint=230 MW, ramp=2 MW/min",
                "GEN001->>SCADA: Acknowledged\nramping at 2 MW/min, current=252 MW",
                "GEN002->>SCADA: Acknowledged\nramping at 2 MW/min, current=204 MW",
                "SCADA->>AGC: Unit response received\nGEN001=252 MW, GEN002=204 MW",
                "AGC->>AGC: Monitor response\nramp rate compliance, 2 MW/min target",
                "EMS->>AGC: Updated ACE\nACE=+45 MW, improving",
                "GEN001->>SCADA: At setpoint\n270 MW, steady state",
                "GEN002->>SCADA: At setpoint\n230 MW, steady state",
                "SCADA->>AGC: Both units at setpoint\nACE=+5 MW, within deadband",
                "AGC->>Operator: Regulation complete\nACE=+5 MW, NERC BAL-001 compliant",
                "AGC->>ISO: LFC response confirmation\nregulation up: 50 MW, response time=4.5 min",
            ],
            "integrations": [
                ("AGC", "ACE", "ReceiveACESignal", "EMS (GE/Alstom)", "AGC System", "EMS API (ICCP)", "AGC Internal Bus", "API-led (Real-time)", "High"),
                ("AGC", "Dispatch", "CalculateGeneratorSetpoints", "AGC System", "SCADA (Siemens Spectrum Power)", "AGC Internal Calc", "SCADA API (ICCP)", "API-led (Real-time)", "High"),
                ("AGC", "Setpoint", "DispatchRaiseCommand", "SCADA (Siemens Spectrum Power)", "Plant DCS (ABB 800xA)", "SCADA API (ICCP)", "DCS Modbus TCP", "API-led (Real-time)", "High"),
                ("AGC", "Response", "MonitorRampResponse", "AGC System", "EMS (GE/Alstom)", "AGC Internal", "EMS API (ICCP)", "API-led (Real-time)", "Medium"),
                ("AGC", "Compliance", "VerifyACENERC", "AGC System", "EMS (GE/Alstom)", "AGC Internal", "EMS API (ICCP)", "API-led (Real-time)", "Medium"),
                ("AGC", "Confirmation", "SendLFCResponse", "EMS (GE/Alstom)", "ISO RTO System", "EMS API (ICCP)", "ISO API (ICCP)", "API-led (Real-time)", "High"),
                ("AGC", "Log", "LogDispatchEvent", "AGC System", "Plant Historian (OSIsoft PI)", "AGC API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-AGC-01", "Verify ACE returns to within \u00b110 MW deadband within 10 minutes of LFC request", "ReceiveACESignal", "ACE within deadband within 10 min of dispatch", "High"),
                ("AC-AGC-02", "Validate generator ramp rate compliance with NERC BAL-001 standards", "CalculateGeneratorSetpoints", "Each generator ramps within \u00b10.5 MW/min of target", "High"),
                ("AC-AGC-03", "Confirm ISO communication latency under 5 seconds for dispatch signals", "ReceiveACESignal", "ICCP data transfer completes in under 5s", "Medium"),
                ("AC-AGC-04", "Ensure all AGC events logged with ACE value, setpoint, and unit response", "LogDispatchEvent", "Complete audit trail for NERC compliance", "Medium"),
            ],
        }),
        ("1.4", {
            "title": "Fuel Management & Emissions Monitoring",
            "description": "Fuel management system tracks fuel inventory, quality, and consumption for thermal plants. Emissions monitoring system (CEMS) continuously measures stack emissions and reports data to environmental regulators.",
            "actors": ["Fuel Manager", "Environmental Engineer", "Plant Manager"],
            "systems": ["Fuel Management System", "CEMS (Continuous Emissions Monitoring)", "DCS (ABB 800xA)", "EPA CAMD Portal", "PI Historian"],
            "mermaid": [
                "FuelMgr->>FMS: Check fuel inventory\ngas: 1.2 BCF, oil: 500K bbls, coal: 0",
                "FMS->>DCS: Fuel consumption rate\n12 MMCF/hr, heat rate=7.5 MMBTU/MWh",
                "DCS->>FMS: Daily consumption\ngas used: 288 MMCF, BTU content=1025 BTU/CF",
                "FuelMgr->>FMS: Schedule fuel delivery\nLNG cargo, 3 BCF, delivery=2026-07-10",
                "FMS->>Vendor: Place fuel order\nFOB terminal, 3 BCF, price=$3.50/MMBTU",
                "Vendor->>FMS: Order confirmed\ndelivery window: July 10-12, pipeline transport",
                "CEMS->>Stack: Sample emissions\nCO2, NOx, SO2, O2, flow rate",
                "Stack->>CEMS: Emissions data\nCO2=1250 TPD, NOx=320 lbs/hr, SO2=15 lbs/hr",
                "CEMS->>DCS: Real-time emissions\nCO2 rate=1250 TPD, within permit limit",
                "DCS->>Operator: Emissions advisory\nNOx approaching limit (85% of 400 lbs/hr)",
                "CEMS->>EPA: Hourly emissions report\nCO2, NOx, SO2, diluent, flow",
                "EPA->>CEMS: Report acknowledged\n2026-Q2, compliance status=Green",
                "DCS->>FuelMgr: Heat rate report\n7.5 MMBTU/MWh, efficiency=58.2%",
                "FuelMgr->>FMS: Update fuel forecast\nJuly: 8.9 BCF, budget=$31.2M",
                "PlantMgr->>FMS: Fuel cost report\nYTD fuel cost=$187M, vs budget=$192M, variance=-2.6%",
            ],
            "integrations": [
                ("Fuel", "Inventory", "CheckFuelInventory", "Fuel Management System", "DCS (ABB 800xA)", "FMS API (REST)", "DCS OPC-UA", "API-led (Real-time)", "Simple"),
                ("Fuel", "Consumption", "RecordDailyConsumption", "DCS (ABB 800xA)", "Fuel Management System", "DCS OPC-UA", "FMS API (REST)", "Batch (Scheduled)", "Medium"),
                ("Fuel", "Order", "PlaceFuelOrder", "Fuel Management System", "Vendor Portal", "FMS API (REST)", "Vendor EDI", "API-led (Real-time)", "Medium"),
                ("Emissions", "CEMS", "SampleStackEmissions", "CEMS", "Stack Analyzer", "CEMS Serial (Modbus)", "Analyzer 4-20mA", "API-led (Real-time)", "High"),
                ("Emissions", "DCS", "TransferEmissionsData", "CEMS", "DCS (ABB 800xA)", "CEMS API (Modbus TCP)", "DCS OPC-UA", "API-led (Real-time)", "Medium"),
                ("Emissions", "EPA", "ReportHourlyEmissions", "CEMS", "EPA CAMD Portal", "CEMS API (REST)", "EPA CAMD Web Services (SOAP)", "Batch (Scheduled)", "High"),
                ("Emissions", "Compliance", "LogEmissionsReport", "CEMS", "Plant Historian (OSIsoft PI)", "CEMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-FM-01", "Verify fuel inventory accuracy within \u00b12% of physical measurement", "CheckFuelInventory", "FMS inventory matches tank gauging within 2%", "High"),
                ("AC-FM-02", "Validate CEMS data completeness >95% for EPA reporting", "SampleStackEmissions", "No gaps >1 hour in CEMS data stream", "High"),
                ("AC-FM-03", "Confirm EPA report submission within regulatory deadline (hourly)", "ReportHourlyEmissions", "EPA acknowledges receipt within 1 hour of period end", "High"),
                ("AC-FM-04", "Ensure heat rate calculation accuracy within \u00b11% of turbine heat balance", "RecordDailyConsumption", "Heat rate matches turbine manufacturer curve within 1%", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["Transmission"] = {
    "title": "Transmission Operations & EMS",
    "description": "Real-time monitoring and control of the high-voltage transmission network via Energy Management System (EMS). Includes state estimation, contingency analysis, wide-area monitoring with synchrophasors, and transmission switching/clearance management.",
    "capabilities": ["UT-EMS", "UT-SEC", "UT-WAM", "UT-TSC"],
    "subflows": OrderedDict([
        ("2.1", {
            "title": "EMS Real-time Network Monitoring",
            "description": "System operators monitor the transmission network in real-time via EMS displays showing voltage profiles, line loadings, and system frequency. SCADA data from substations is processed for situational awareness.",
            "actors": ["Transmission Operator", "EMS Engineer", "Reliability Coordinator"],
            "systems": ["EMS (Siemens Spectrum Power / OSI Monarch)", "SCADA RTUs", "PI Historian", "Substation IEDs"],
            "mermaid": [
                "RTU->>SCADA: Transmit analog values\nSUB-MAIN: 138.2 kV, 450 MW, 120 MVAR",
                "SCADA->>EMS: Update topology\nbreaker BRK-2026-001: Closed",
                "EMS->>EMS: State estimation\nconvergence=0.0001, 138 nodes solved",
                "EMS->>Operator: Display overview\nSpringfield: 138 kV / 12.47 kV, loading=55%",
                "EMS->>EMS: Topology processor\nbus topology: 5 substations, 12 lines",
                "SCADA->>EMS: New alarm\nLine L-2026: 95% loading, limit=100%",
                "EMS->>Operator: Line loading alert\nSpringfield-Chicago 345 kV: 95%",
                "Operator->>EMS: Analyze contingency\nN-1 of line L-2026",
                "EMS->>EMS: Contingency analysis\npost-contingent: 112% overload on L-2028",
                "EMS->>Operator: N-1 violation\nremedial action required",
                "Operator->>EMS: Change tap\nTX-2026-001 tap=5, reduce flow",
                "EMS->>SCADA: Execute tap change\nLTC tap position 5\u21923",
                "SCADA->>EMS: Confirmed\nL-2026 loading=88%, L-2028 loading=94%",
                "EMS->>PI: Log snapshot\n2026-07-07T10:00:00, all solved values",
                "Operator->>EMS: Log operator action\ntap change, reason: N-1 violation mitigation",
            ],
            "integrations": [
                ("EMS", "Telemetry", "ReceiveAnalogValues", "RTU (SUB-MAIN-001)", "SCADA (Siemens Spectrum Power)", "RTU DNP3", "SCADA DNP3", "API-led (Real-time)", "High"),
                ("EMS", "StateEstimation", "RunStateEstimation", "EMS (Siemens Spectrum Power)", "EMS (Siemens Spectrum Power)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("EMS", "Alarm", "ProcessLineAlarm", "SCADA (Siemens Spectrum Power)", "EMS (Siemens Spectrum Power)", "SCADA API (ICCP)", "EMS Internal", "Event-driven", "High"),
                ("EMS", "Contingency", "RunContingencyAnalysis", "EMS (Siemens Spectrum Power)", "EMS (Siemens Spectrum Power)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("EMS", "Control", "ExecuteTapChange", "EMS (Siemens Spectrum Power)", "SCADA (Siemens Spectrum Power)", "EMS API (ICCP)", "SCADA DNP3", "API-led (Real-time)", "Medium"),
                ("EMS", "Historian", "LogSnapshot", "EMS (Siemens Spectrum Power)", "Plant Historian (OSIsoft PI)", "EMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
                ("EMS", "Audit", "LogOperatorAction", "EMS (Siemens Spectrum Power)", "Compliance Database", "EMS API (REST)", "SQL JDBC", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-EMS-01", "Validate state estimation convergence within 30 seconds of topology change", "RunStateEstimation", "State estimation converges with residual <0.001 within 30s", "High"),
                ("AC-EMS-02", "Confirm alarm processing latency under 5 seconds from RTU scan to HMI display", "ProcessLineAlarm", "Alarm visible on operator console within 5s of RTU scan", "High"),
                ("AC-EMS-03", "Verify contingency analysis completes within 60 seconds for full network model", "RunContingencyAnalysis", "All N-1 contingencies evaluated within 60s", "Medium"),
                ("AC-EMS-04", "Ensure all operator control actions are logged with user, target, and timestamp", "LogOperatorAction", "Complete audit trail for NERC compliance", "Medium"),
            ],
        }),
        ("2.2", {
            "title": "State Estimation & Contingency Analysis",
            "description": "State estimator processes real-time measurements to compute the best estimate of power system state. Contingency analysis evaluates N-1 reliability criteria and identifies potential violations requiring remedial action.",
            "actors": ["EMS Engineer", "Transmission Operator", "Planning Engineer"],
            "systems": ["EMS State Estimator (OSI Monarch)", "SCADA", "Contingency Analysis Module", "Remedial Action System"],
            "mermaid": [
                "SCADA->>Estimator: Inject measurements\n138 kV buses: voltage, power flow, status",
                "Estimator->>Estimator: Topology processing\nbus/branch model: 138 buses, 245 branches",
                "Estimator->>Estimator: Solve weighted least squares\nobjective=0.00024, 3 iterations",
                "Estimator->>Operator: Display solved state\nbus voltages: 0.98-1.02 pu, all within limits",
                "Estimator->>CA: Pass solved state\nbase case for contingency analysis",
                "CA->>CA: Evaluate N-1 contingencies\nline outages, transformer outages, bus faults",
                "CA->>CA: Identify violations\nLine L-2045: 98% \u2192 112% post L-2046 outage",
                "CA->>Operator: Display contingency results\n5 violations: 2 overloads, 3 voltage",
                "Operator->>CA: Select remedial action\nredispatch GEN-007, 50 MW reduction",
                "CA->>CA: Evaluate remedial action\npost-action: L-2045 loading=98% \u2192 95%",
                "CA->>Operator: Remedial action valid\nall violations mitigated",
                "Operator->>SCADA: Implement redispatch\nGEN-007: reduce 50 MW, ramp=10 min",
                "SCADA->>Operator: Redispatch confirm\nGEN-007: 300 MW \u2192 250 MW",
                "Estimator->>PI: Log solved state\ntimestamp, all bus voltages, flows",
                "Operator->>EMS: Document action\nN-1 violation: L-2045, action: redispatch GEN-007",
            ],
            "integrations": [
                ("EMS", "Estimation", "InjectMeasurements", "SCADA", "EMS State Estimator", "SCADA API (ICCP)", "Estimator API (Internal)", "API-led (Real-time)", "High"),
                ("EMS", "Topology", "ProcessTopology", "EMS State Estimator", "EMS Network Model", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("EMS", "Contingency", "EvaluateN-1Contingencies", "EMS State Estimator", "Contingency Analysis Module", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("EMS", "Violation", "IdentifyViolations", "Contingency Analysis Module", "Operator HMI", "Internal", "HMI API (REST)", "Event-driven", "High"),
                ("EMS", "Action", "SelectRemedialAction", "Operator HMI", "Contingency Analysis Module", "HMI API (REST)", "Internal", "API-led (Real-time)", "Medium"),
                ("EMS", "Dispatch", "ImplementRedispatch", "Operator HMI", "SCADA", "HMI API (REST)", "SCADA API (ICCP)", "API-led (Real-time)", "Medium"),
                ("EMS", "Log", "LogSolvedState", "EMS State Estimator", "Plant Historian (OSIsoft PI)", "EMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-SE-01", "Validate state estimation solves within 5-minute SCADA scan cycle", "InjectMeasurements", "State estimator converges before next SCADA scan", "High"),
                ("AC-SE-02", "Confirm measurement residual <0.001 pu for all bus voltages", "ProcessTopology", "All bus voltage residuals within tolerance", "High"),
                ("AC-SE-03", "Verify contingency analysis evaluates 100% of defined N-1 contingencies", "EvaluateN-1Contingencies", "All contingencies evaluated with results available", "Medium"),
                ("AC-SE-04", "Ensure remedial action effectiveness validated before implementation", "SelectRemedialAction", "CA confirms all violations mitigated post-action", "Medium"),
            ],
        }),
        ("2.3", {
            "title": "Wide Area Monitoring & Synchrophasors",
            "description": "Wide Area Monitoring System (WAMS) collects synchrophasor data from PMUs deployed across the transmission network. Phasor data concentrators (PDCs) time-align and stream data for real-time visualization, oscillation detection, and post-event analysis.",
            "actors": ["System Operator", "Protection Engineer", "Grid Stability Analyst"],
            "systems": ["WAMS (GE PhasorPoint / SEL)", "PDC (Phasor Data Concentrator)", "PMUs (SEL-421 / GE D60)", "EMS", "PI Historian"],
            "mermaid": [
                "PMU_Main->>PDC: Stream phasor data\nV=138.2\u2220-2.4\u00b0, I=1880\u2220-30.5\u00b0, f=60.02 Hz, 30 msg/s",
                "PMU_SubA->>PDC: Stream phasor data\nV=137.8\u2220-4.1\u00b0, I=1200\u2220-28.3\u00b0, f=60.01 Hz, 30 msg/s",
                "PMU_SubB->>PDC: Stream phasor data\nV=136.5\u2220-5.8\u00b0, I=950\u2220-32.1\u00b0, f=60.00 Hz, 30 msg/s",
                "PDC->>PDC: Time-align data\ntime tag=10:00:00.000, 30 PMUs synced",
                "PDC->>WAMS: Stream aligned phasors\n30 PMUs, 90 phasors, 30 fps",
                "WAMS->>Operator: Display wide-area view\nvoltage contour map, 345 kV network",
                "WAMS->>WAMS: Oscillation detection\ntypical mode: 0.3 Hz, damping=8%",
                "WAMS->>Operator: Oscillation alert\nmode: 0.3 Hz, damping=5%, threshold=3%",
                "Operator->>WAMS: Analyze oscillation\nfrequency domain, mode shape",
                "WAMS->>Operator: Mode shape display\narea A vs area B, 0.3 Hz inter-area",
                "Operator->>EMS: Check damping\nrecommend PSS tuning at GEN-007",
                "WAMS->>PDC: Increase rate\n60 msg/s for oscillation analysis",
                "PDC->>WAMS: Streaming at 60 fps\ntime-aligned, all 30 PMUs",
                "WAMS->>PI: Log synchrophasors\n30 PMUs, 90 phasors, 1-min snapshots",
                "WAMS->>Operator: Damping improving\nmode: 0.3 Hz, damping=6%, action effective",
            ],
            "integrations": [
                ("WAMS", "PMU", "StreamPhasorData", "PMU (SEL-421)", "PDC (Phasor Data Concentrator)", "PMU C37.118", "PDC C37.118", "API-led (Real-time)", "High"),
                ("WAMS", "Alignment", "TimeAlignPhasors", "PDC (Phasor Data Concentrator)", "PDC (Phasor Data Concentrator)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("WAMS", "Stream", "StreamAlignedPhasors", "PDC (Phasor Data Concentrator)", "WAMS (GE PhasorPoint)", "PDC C37.118", "WAMS C37.118", "API-led (Real-time)", "High"),
                ("WAMS", "Oscillation", "DetectOscillations", "WAMS (GE PhasorPoint)", "WAMS (GE PhasorPoint)", "Internal", "Internal", "Batch (Real-time)", "Medium"),
                ("WAMS", "Alert", "AlertOperatorOscillation", "WAMS (GE PhasorPoint)", "Operator HMI", "WAMS API (REST)", "HMI API (REST)", "Event-driven", "Medium"),
                ("WAMS", "Historian", "LogSynchrophasors", "WAMS (GE PhasorPoint)", "Plant Historian (OSIsoft PI)", "WAMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Medium"),
                ("WAMS", "EMS", "TransferWAMSData", "WAMS (GE PhasorPoint)", "EMS", "WAMS API (ICCP)", "EMS API (ICCP)", "API-led (Real-time)", "Medium"),
            ],
            "acceptance_criteria": [
                ("AC-WAM-01", "Validate PMU data timestamp accuracy within \u00b150 \u00b5s of UTC via GPS", "StreamPhasorData", "All PMU timestamps synchronized to GPS within tolerance", "High"),
                ("AC-WAM-02", "Confirm PDC time-alignment latency under 10 ms for 30 PMU streams", "TimeAlignPhasors", "Time-aligned data available within 10 ms of PMU frame", "High"),
                ("AC-WAM-03", "Verify oscillation detection identifies modes with damping <10% within 5 cycles", "DetectOscillations", "Oscillation detection triggers within 5 cycles of onset", "Medium"),
                ("AC-WAM-04", "Ensure synchrophasor data archival at minimum 1 snapshot per minute", "LogSynchrophasors", "PI historian contains 1-min snapshots for all 30 PMUs", "Medium"),
            ],
        }),
        ("2.4", {
            "title": "Transmission Switching & Clearance Management",
            "description": "Operators manage transmission switching orders and clearance requests to ensure safe isolation of equipment for maintenance. The clearance management system tracks tags, holds, and switching sequences with interlocking logic.",
            "actors": ["Transmission Operator", "Switching Scheduler", "Field Crew"],
            "systems": ["Switching Management System", "EMS", "SCADA", "Clearance & Tagging System", "Mobile Field App"],
            "mermaid": [
                "Scheduler->>SMS: Create switching order\nSWO-2026-042: isolate Line L-2046 for maintenance",
                "SMS->>Operator: Approve switching order\nscheduled: 2026-07-08T08:00-12:00",
                "Operator->>SMS: Approve order\nSWO-2026-042: approved, safety check passed",
                "Operator->>SCADA: Pre-job check\nL-2046: current=0 MW, breaker status=Closed",
                "SCADA->>Operator: Line status\nL-2046: 345 kV, 0 MW, breaker=Closed",
                "Operator->>Clearance: Request clearance\nisolate L-2046, tag=CREW-ALPHA, work=insulator replacement",
                "Clearance->>Clearance: Create tag\nTAG-2026-042: Danger, Do Not Operate",
                "Clearance->>SCADA: Apply tag\nL-2046: remote blocking active, tag=TAG-2026-042",
                "SCADA->>Operator: Tag applied\nL-2046: remote control blocked",
                "Operator->>SCADA: Open breaker\nBRK-2046: open, L-2046 de-energized",
                "SCADA->>Operator: Breaker confirmed\nBRK-2046: Open, L-2046: 0 kV, 0 MW",
                "Operator->>SMS: Execute switching\nL-2046 isolated, grounds applied",
                "SMS->>Field: Release to work\nclearance active, 15 kV grounds in place",
                "Field->>SMS: Work complete\ninsulators replaced, grounds removed",
                "Operator->>SCADA: Close breaker\nBRK-2046: Close, L-2046 re-energized",
                "SCADA->>Operator: Line restored\nL-2046: 345 kV, 450 MW, in service",
                "Operator->>Clearance: Remove tag\nTAG-2026-042: retired, clearance complete",
                "SMS->>Scheduler: Close switching order\nSWO-2026-042: complete, duration=3.5 hrs",
            ],
            "integrations": [
                ("Switching", "Order", "CreateSwitchingOrder", "Switching Scheduler", "Switching Management System", "Scheduler UI", "SMS API (REST)", "API-led (Real-time)", "Simple"),
                ("Switching", "Approval", "ApproveSwitchingOrder", "Switching Management System", "Operator HMI", "SMS API (REST)", "HMI API (REST)", "API-led (Real-time)", "Medium"),
                ("Switching", "Clearance", "RequestClearance", "Operator HMI", "Clearance & Tagging System", "HMI API (REST)", "Clearance API (REST)", "API-led (Real-time)", "High"),
                ("Switching", "Tag", "ApplyTag", "Clearance & Tagging System", "SCADA", "Clearance API (REST)", "SCADA API (ICCP)", "Event-driven", "High"),
                ("Switching", "Breaker", "OpenBreaker", "Operator HMI", "SCADA", "HMI API (REST)", "SCADA DNP3", "API-led (Real-time)", "High"),
                ("Switching", "Field", "ReleaseToWork", "Switching Management System", "Mobile Field App", "SMS API (REST)", "Field App API (OAuth2)", "API-led (Real-time)", "Medium"),
                ("Switching", "Restore", "RestoreLine", "Operator HMI", "SCADA", "HMI API (REST)", "SCADA DNP3", "API-led (Real-time)", "High"),
                ("Switching", "Close", "CloseSwitchingOrder", "Switching Management System", "Switching Scheduler", "SMS API (REST)", "Scheduler UI", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-TS-01", "Verify tag/clearance blocks remote SCADA control before breaker operation", "ApplyTag", "SCADA remote control blocked when tag is active", "High"),
                ("AC-TS-02", "Confirm switching order approval workflow is complete before field release", "ApproveSwitchingOrder", "Switching order fully approved before field work begins", "High"),
                ("AC-TS-03", "Validate clearance-to-work authorization is communicated to field crew", "ReleaseToWork", "Field crew acknowledges clearance within 5 min", "Medium"),
                ("AC-TS-04", "Ensure all switching events are logged with user, equipment, and timestamp", "CloseSwitchingOrder", "Complete audit trail for NERC compliance", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["Substation"] = {
    "title": "Substation Automation & Protection",
    "description": "Automated control and monitoring of substation equipment via RTUs, IEDs, and IEC 61850 communications. Includes protection relay management, fault recording, and substation security perimeters.",
    "capabilities": ["UT-RTU", "UT-PIM", "UT-IEC", "UT-SSA"],
    "subflows": OrderedDict([
        ("3.1", {
            "title": "RTU & Substation SCADA Control",
            "description": "Remote Terminal Units at substations acquire analog and status data from switchgear, transformers, and breakers. The substation SCADA concentrator aggregates RTU data and communicates with the central EMS via ICCP/DNP3.",
            "actors": ["Substation Technician", "System Operator", "SCADA Engineer"],
            "systems": ["RTU (SEL-3530 / GE D20)", "Substation SCADA Concentrator", "EMS", "IEDs (SEL-421 Relays)"],
            "mermaid": [
                "RTU->>Breaker: Read status\nBRK-MAIN-001: position=Closed, SF6 pressure=72 psi",
                "RTU->>Transformer: Read tap position\nTX-001: tap=5, oil_temp=85\u00b0C, OLTC_count=1245",
                "RTU->>Relay: Read fault records\nSEL-421: fault_count=3, last_fault=2026-07-06T14:22",
                "RTU->>RTU: Update scan table\n48 analogs, 64 status, 12 counters",
                "RTU->>SCADA_Concentrator: Report by exception\nanalog change>0.5%, status change",
                "SCADA_Concentrator->>EMS: DNP3 unsolicited\nSUB-MAIN-001: 138.2 kV, 450 MW, BRK=Closed",
                "EMS->>SCADA_Concentrator: Select-before-operate\nopen BRK-MAIN-001 for switching",
                "SCADA_Concentrator->>RTU: Execute command\nSBO BRK-MAIN-001: select=OK",
                "RTU->>Breaker: Trip command\nBRK-MAIN-001: trip coil energized",
                "Breaker->>RTU: Status change\nBRK-MAIN-001: Open, transition detected",
                "RTU->>SCADA_Concentrator: Status change event\nBRK-MAIN-001: Open, SOE timestamp=14:23:01.234",
                "SCADA_Concentrator->>EMS: DNP3 unsolicited\nBRK-MAIN-001: Open, SOE included",
                "EMS->>Operator: Display update\nSUB-MAIN-001: breaker open, flow=0 MW",
                "RTU->>PI: Stream data\n15-min averages, all 48 analogs",
                "SCADA_Concentrator->>Operator: Alarm\nSUB-MAIN-001: switchgear status changed",
            ],
            "integrations": [
                ("Substation", "Status", "ReadBreakerStatus", "RTU (SEL-3530)", "Breaker Control", "RTU I/O", "Breaker Aux Contact", "API-led (Real-time)", "High"),
                ("Substation", "Analog", "ReadAnalogValues", "RTU (SEL-3530)", "CT/PT", "RTU Analog Input", "CT/PT Secondary", "API-led (Real-time)", "High"),
                ("Substation", "SCADA", "ReportByException", "RTU (SEL-3530)", "Substation SCADA Concentrator", "RTU DNP3", "SCADA DNP3", "API-led (Real-time)", "High"),
                ("Substation", "EMS", "TransmitToEMS", "Substation SCADA Concentrator", "EMS (Siemens Spectrum Power)", "SCADA API (ICCP)", "EMS API (ICCP)", "API-led (Real-time)", "High"),
                ("Substation", "Control", "SBOCommand", "EMS (Siemens Spectrum Power)", "Substation SCADA Concentrator", "EMS API (ICCP)", "SCADA DNP3", "API-led (Real-time)", "High"),
                ("Substation", "Event", "LogSOEEvent", "RTU (SEL-3530)", "Substation SCADA Concentrator", "RTU DNP3", "SCADA DNP3", "Event-driven", "High"),
                ("Substation", "Historian", "StreamAnalogData", "RTU (SEL-3530)", "Plant Historian (OSIsoft PI)", "RTU DNP3", "PI Interface (DNP3)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-RTU-01", "Validate RTU scan rate of 2 seconds for all analog points", "ReadAnalogValues", "All analogs scanned within 2s cycle", "High"),
                ("AC-RTU-02", "Confirm SOE timestamp accuracy within \u00b11 ms of event occurrence", "LogSOEEvent", "SOE timestamps accurate to \u00b11 ms", "High"),
                ("AC-RTU-03", "Verify select-before-operate sequence completes in under 5 seconds", "SBOCommand", "Control operation sequence completes within 5s", "Medium"),
                ("AC-RTU-04", "Ensure data quality flags (good/suspect/override) are preserved in transmission", "ReportByException", "Data quality flags correctly mapped to DNP3 quality field", "Medium"),
            ],
        }),
        ("3.2", {
            "title": "Protection Relay & IED Management",
            "description": "Protection engineers manage relay settings, fault records, and event reports for microprocessor relays. The IED management system handles settings file versioning, group changes, and disturbance record retrieval.",
            "actors": ["Protection Engineer", "Substation Technician", "Fault Analyst"],
            "systems": ["Protection Management System (SEL AcSELerator / GE Enervista)", "Relays (SEL-421, SEL-311, GE D60)", "Fault Recorder System", "Time Sync (GPS / IRIG-B)"],
            "mermaid": [
                "Engineer->>PMS: Retrieve settings\nSEL-421 at SUB-MAIN-001: group 1 active",
                "PMS->>Relay: Read active settings\nSEL-421: Z1=5.2\u03a9, Z2=8.7\u03a9, Z3=12.1\u03a9",
                "Relay->>PMS: Current settings\ngroup 1: 21P, 21G, 50P, 51G, 67P enabled",
                "Engineer->>PMS: Modify settings\nZ1=5.5\u03a9, new line length correction",
                "PMS->>Engineer: Settings validation\nlogic check: pass, coordination check: pass",
                "Engineer->>PMS: Send settings group\nnew group 2: Z1=5.5\u03a9, all coordination verified",
                "PMS->>Relay: Write settings group\nSEL-421: group 2 received, CRC=0xA3F2",
                "Relay->>PMS: Settings stored\nactive group=2, checksum verified",
                "Engineer->>Relay: Trigger fault record\nretrieve last 10 events",
                "Relay->>Engineer: Event records\n10 events, latest=2026-07-06T14:22:15.123",
                "FaultRecorder->>FaultRecorder: Detect disturbance\nLine L-2046: fault type=AG, current=12.5 kA",
                "FaultRecorder->>PMS: Store COMTRADE\nfile=FLT-2026-042.DAT, 1 sec, 128 smp/cyc",
                "PMS->>Engineer: Disturbance available\nCOMTRADE file: current, voltage, relay targets",
                "Engineer->>PMS: Analyze disturbance\nfault location=12.3 km, clearing time=3.2 cycles",
                "Engineer->>Relay: Verify operation\nrelay operated correctly, reclose successful",
            ],
            "integrations": [
                ("Protection", "Settings", "ReadRelaySettings", "Protection Management System", "Relay (SEL-421)", "PMS API (REST)", "Relay Serial (SEL Protocol)", "API-led (Real-time)", "Medium"),
                ("Protection", "Validation", "ValidateRelaySettings", "Protection Management System", "Protection Management System", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("Protection", "Write", "WriteSettingsGroup", "Protection Management System", "Relay (SEL-421)", "PMS API (REST)", "Relay Serial (SEL Protocol)", "API-led (Real-time)", "High"),
                ("Protection", "Events", "RetrieveFaultRecords", "Engineer HMI", "Relay (SEL-421)", "HMI API (REST)", "Relay Serial (SEL Protocol)", "API-led (Real-time)", "Medium"),
                ("Protection", "Disturbance", "StoreCOMTRADE", "Fault Recorder", "Protection Management System", "Fault Recorder API", "PMS API (REST)", "Event-driven", "Medium"),
                ("Protection", "Analysis", "AnalyzeDisturbance", "Protection Management System", "Engineer HMI", "PMS API (REST)", "HMI API (REST)", "Batch (Real-time)", "Simple"),
                ("Protection", "TimeSync", "SyncRelayTime", "Time Sync (GPS)", "Relay (SEL-421)", "GPS IRIG-B", "Relay IRIG-B", "API-led (Real-time)", "High"),
            ],
            "acceptance_criteria": [
                ("AC-PR-01", "Validate relay settings file CRC integrity after write operation", "WriteSettingsGroup", "CRC checksum matches between PMS and relay", "High"),
                ("AC-PR-02", "Confirm settings group change does not affect other protection elements", "ValidateRelaySettings", "All existing protection elements remain enabled/disabled as configured", "High"),
                ("AC-PR-03", "Verify COMTRADE file captures 60 cycles pre-fault and 180 cycles post-fault", "StoreCOMTRADE", "Disturbance record meets duration requirements", "Medium"),
                ("AC-PR-04", "Ensure relay time drift remains under \u00b11 ms relative to GPS", "SyncRelayTime", "Relay time sync status shows IRIG-B locked", "Medium"),
            ],
        }),
        ("3.3", {
            "title": "IEC 61850 Substation Communications",
            "description": "Substation automation devices communicate using IEC 61850 protocols including GOOSE for high-speed peer-to-peer messaging, MMS for client-server monitoring and control, and Sampled Values for instrument transformer data.",
            "actors": ["Substation Automation Engineer", "Protection Engineer", "Network Engineer"],
            "systems": ["IEC 61850 IEDs (SEL, GE, ABB)", "Substation HMI", "SCADA Gateway (IEC 61850 to DNP3)", "Network Switch (Managed)", "Time Sync (PTP/IEEE 1588)"],
            "mermaid": [
                "MergeUnit->>BayController: Sampled Values\nI=1200A, V=138 kV, 80 smp/cyc, dataset=SEC_U_01",
                "BayController->>Relay: GOOSE message\nPTRC_01: trip, quality=Good, timestamp=10:00:00.000",
                "Relay->>Breaker: GOOSE trip\nXCBR_01: trip command, stVal=true",
                "Breaker->>BayController: GOOSE status\nXCBR_01: Pos=Open, quality=Good",
                "BayController->>SCADA_Gateway: MMS report\nLLN0: brk_status, 138 kV, 450 MW",
                "SCADA_Gateway->>EMS: DNP3/DLMS\nconverted from IEC 61850 to DNP3",
                "Engineer->>NS: Configure Goose\nDataSet=DS_Protection, GOOSE_ID=Gcb_Tr_001",
                "NS->>Engineer: Configure Vlan\nVLAN 100, Priority 4, time sync=PTP",
                "Engineer->>MergeUnit: Configure SV\nFc=SV, smpRate=80, dataset=SEC_U_01",
                "MergeUnit->>NS: Stream SV\ndestination MAC: 01-0C-CD-04-00-01",
                "NS->>BayController: Forward SV\nIGMP snooping, VLAN 100, PTP time",
                "BayController->>MergeUnit: Time sync\nPTP master: grandmaster clock stratum 1",
                "Engineer->>HMI: SCADA overview\nGOOSE status: Gcb_Tr_001=OK, SV streams=4",
                "HMI->>Engineer: Network health\nlatency=2 ms, jitter=0.1 ms, no errors",
                "Engineer->>SCADA_Gateway: Test mapping\nMMS to DNP3: 48 analogs, 64 status",
            ],
            "integrations": [
                ("IEC61850", "SV", "StreamSampledValues", "Merge Unit", "Bay Controller", "SV (IEC 61850-9-2)", "SV (IEC 61850-9-2)", "API-led (Real-time)", "High"),
                ("IEC61850", "GOOSE", "TripGOOSEMessage", "Bay Controller", "Relay", "GOOSE (IEC 61850-8-1)", "GOOSE (IEC 61850-8-1)", "Event-driven", "High"),
                ("IEC61850", "MMS", "ReportMMSData", "Bay Controller", "SCADA Gateway", "MMS (IEC 61850-8-1)", "MMS (IEC 61850-8-1)", "API-led (Real-time)", "High"),
                ("IEC61850", "Gateway", "ConvertToDNP3", "SCADA Gateway", "EMS", "Gateway Internal", "DNP3 (IEC 61850 to DNP3)", "API-led (Real-time)", "Medium"),
                ("IEC61850", "Config", "ConfigureGOOSE", "Engineer Workstation", "Network Switch", "Engineering Tool", "Switch CLI/SNMP", "API-led (Real-time)", "Simple"),
                ("IEC61850", "PTP", "SyncPTPTime", "PTP Grandmaster", "Merge Unit", "PTP (IEEE 1588)", "PTP (IEEE 1588)", "API-led (Real-time)", "High"),
                ("IEC61850", "Health", "MonitorNetworkHealth", "Network Switch", "Substation HMI", "SNMP", "HMI API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-IEC-01", "Validate GOOSE message delivery time under 3 ms for protection messages", "TripGOOSEMessage", "GOOSE trip received by relay within 3 ms", "High"),
                ("AC-IEC-02", "Confirm SV stream synchronization within \u00b11 \u00b5s via PTP", "StreamSampledValues", "All SV streams synchronized to PTP grandmaster", "High"),
                ("AC-IEC-03", "Verify MMS report latency under 100 ms from data change to SCADA gateway", "ReportMMSData", "MMMS report buffered report delivered within 100 ms", "Medium"),
                ("AC-IEC-04", "Ensure GOOSE dataset integrity with sequence number continuity", "ConfigureGOOSE", "No missing GOOSE sequence numbers over 24-hour test", "Medium"),
            ],
        }),
        ("3.4", {
            "title": "Substation Security & Access Management",
            "description": "Physical and cyber security management for substations including electronic security perimeters (ESP), access control systems, video surveillance, and NERC CIP compliance for cyber assets.",
            "actors": ["Security Analyst", "Substation Technician", "NERC CIP Compliance Lead"],
            "systems": ["Access Control System (Lenel / Honeywell)", "Video Management System", "Substation HMI", "CIP Compliance Database", "SIEM (Splunk)"],
            "mermaid": [
                "Tech->>Access_Control: Badge in\nSUB-MAIN-001: badge #1042, role=Technician",
                "Access_Control->>Tech: Access granted\ndoor 1: unlocked, entry logged 10:00:00",
                "Camera->>VMS: Record video\nSUB-MAIN-001: entry area, motion detection",
                "VMS->>Tech: Motion alert\nSUB-MAIN-001: parking area, vehicle detected",
                "Tech->>Cyber_Access: Request VPN\nrole=Technician, asset=RELAY-SEL-421",
                "Cyber_Access->>Tech: MFA challenge\nauthenticator push, RSA token accepted",
                "Tech->>Relay: Remote access\nSSH session started, session_id=SES-2026-042",
                "Relay->>SIEM: Log login\nSEL-421: user=tech1042, src_ip=10.0.1.50, success",
                "SIEM->>Analyst: Alert\nSUB-MAIN-001: login outside business hours, 22:00",
                "Analyst->>VMS: Review video\nSUB-MAIN-001: entry=22:00:00, badge=tech1042",
                "Analyst->>Tech: Verify activity\ntechnician confirmed, scheduled overtime",
                "Analyst->>SIEM: Close alert\nfalse positive, legitimate OT activity",
                "Compliance->>CIP_DB: Audit access logs\nSUB-MAIN-001: Q2 2026, all access event",
                "CIP_DB->>Compliance: Report\n1042 access events, 0 violations, 3 alerts all closed",
                "Compliance->>Analyst: CIP evidence ready\nNERC CIP-005, CIP-006, CIP-007 compliant",
            ],
            "integrations": [
                ("Security", "Physical", "BadgeAccess", "Badge Reader", "Access Control System", "Badge Reader Wiegand", "ACS API (REST)", "API-led (Real-time)", "High"),
                ("Security", "Video", "RecordMotionEvent", "Camera (IP)", "Video Management System", "Camera RTSP", "VMS API (ONVIF)", "API-led (Real-time)", "Medium"),
                ("Security", "Cyber", "RequestVPNAccess", "Remote Technician", "Cyber Access Gateway", "VPN Client", "Gateway API (RADIUS)", "API-led (Real-time)", "High"),
                ("Security", "MFA", "ChallengeMFA", "Cyber Access Gateway", "MFA Server (RSA)", "Gateway API (RADIUS)", "MFA API (RADIUS/HTTP)", "API-led (Real-time)", "High"),
                ("Security", "SIEM", "LogAccessEvent", "Relay (SEL-421)", "SIEM (Splunk)", "Syslog", "SIEM API (Syslog)", "Event-driven", "Medium"),
                ("Security", "CIP", "AuditAccessLogs", "Compliance Lead", "CIP Compliance Database", "CIP UI", "CIP DB API (REST)", "Batch (Scheduled)", "Medium"),
                ("Security", "Report", "GenerateCIPReport", "CIP Compliance Database", "Compliance Lead", "CIP DB API (REST)", "CIP UI", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-SEC-01", "Validate badge access response time under 3 seconds from badge swipe to door unlock", "BadgeAccess", "Door unlocks within 3s of badge presentation", "High"),
                ("AC-SEC-02", "Confirm MFA enforcement for all remote cyber access to BES Cyber Assets", "ChallengeMFA", "All remote access requires MFA before session establishment", "High"),
                ("AC-SEC-03", "Verify SIEM receives all access events within 60 seconds of occurrence", "LogAccessEvent", "SIEM shows event timestamp within 60s of actual event", "Medium"),
                ("AC-SEC-04", "Ensure quarterly CIP access log reviews are completed with evidence archived", "AuditAccessLogs", "CIP compliance database contains Q2 2026 review evidence", "Medium"),
            ],
        }),
    ]),
}

SECTION_DATA["Distribution"] = {
    "title": "Distribution Grid & ADMS",
    "description": "Real-time monitoring, control, and optimization of the distribution network via Advanced Distribution Management System (ADMS). Includes DER management, fault location/restoration, and distribution planning with volt/VAR optimization.",
    "capabilities": ["UT-DSC", "UT-DER", "UT-FLR", "UT-DPO"],
    "subflows": OrderedDict([
        ("4.1", {
            "title": "Distribution SCADA & ADMS Operations",
            "description": "Distribution operators monitor feeders, regulators, and capacitor banks via ADMS. The system provides real-time visibility, volt/VAR control, and switching management for the distribution grid.",
            "actors": ["Distribution Operator", "Field Technician", "Distribution Engineer"],
            "systems": ["ADMS (GE Grid Solutions / OSI)", "Distribution SCADA RTUs", "Capacitor Bank Controllers", "Voltage Regulators", "PI Historian"],
            "mermaid": [
                "RTU->>ADMS: Report feeder values\nFDR-MAIN-001: 12.47 kV, 450A, 8.5 MW",
                "ADMS->>ADMS: Update topology\nfeeder: FDR-MAIN-001, 5 sections, 45 switches",
                "ADMS->>Operator: Display overview\ndistrict: Springfield, 12 feeders, loading=62%",
                "ADMS->>Capacitor: Check status\nCAP-001: closed, 4.8 MVAR, local mode",
                "Capacitor->>ADMS: Cap bank status\nCAP-001: closed, 4.8 MVAR, temp=85\u00b0F",
                "ADMS->>Regulator: Read tap\nREG-001: tap=7, voltage=12.47 kV, bandwidth=2%",
                "Regulator->>ADMS: Regulator status\nREG-001: tap=7, 12.47 kV, normal",
                "ADMS->>Operator: Volt/VAR advisory\npf=0.92 lagging, target=0.97, need 2.5 MVAR",
                "Operator->>ADMS: Close cap bank\nCAP-002: close, 2.4 MVAR",
                "ADMS->>Capacitor: Close\nCAP-002: close command, 2.4 MVAR",
                "Capacitor->>ADMS: Closed\nCAP-002: closed, 2.4 MVAR, pf=0.95",
                "ADMS->>Operator: Power factor improved\npf=0.95, voltage=12.5 kV, within limits",
                "ADMS->>Regulator: Adjust tap\nREG-001: tap 7\u21926, lower voltage 1%",
                "Regulator->>ADMS: Tap changed\nREG-001: tap=6, voltage=12.35 kV",
                "ADMS->>Operator: Optimization complete\npf=0.97, voltage=12.4 kV, all targets met",
                "ADMS->>PI: Log distribution state\nall feeders, capacitors, regulators, 15-min snapshots",
            ],
            "integrations": [
                ("Distribution", "Telemetry", "ReportFeederValues", "RTU (Feeder)", "ADMS (GE Grid Solutions)", "RTU DNP3", "ADMS DNP3", "API-led (Real-time)", "High"),
                ("Distribution", "SCADA", "UpdateTopology", "ADMS (GE Grid Solutions)", "ADMS (GE Grid Solutions)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("Distribution", "Capacitor", "MonitorCapacitorBank", "Capacitor Bank Controller", "ADMS (GE Grid Solutions)", "Capacitor DNP3", "ADMS DNP3", "API-led (Real-time)", "Medium"),
                ("Distribution", "Regulator", "ReadRegulatorTap", "Voltage Regulator Control", "ADMS (GE Grid Solutions)", "Regulator DNP3", "ADMS DNP3", "API-led (Real-time)", "Medium"),
                ("Distribution", "VoltVAR", "ExecuteVoltVARControl", "ADMS (GE Grid Solutions)", "Capacitor Bank Controller", "ADMS DNP3", "Capacitor DNP3", "API-led (Real-time)", "Medium"),
                ("Distribution", "Optimize", "OptimizePowerFactor", "ADMS (GE Grid Solutions)", "ADMS (GE Grid Solutions)", "Internal", "Internal", "Batch (Real-time)", "Medium"),
                ("Distribution", "Historian", "LogDistributionState", "ADMS (GE Grid Solutions)", "Plant Historian (OSIsoft PI)", "ADMS API (REST)", "PI API (REST)", "Batch (Scheduled)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-DS-01", "Validate feeder telemetry accuracy within \u00b11% of field meter values", "ReportFeederValues", "ADMS feeder values match field meters within 1%", "High"),
                ("AC-DS-02", "Confirm capacitor bank switching response under 10 seconds from command", "MonitorCapacitorBank", "Capacitor status reflects command within 10s", "Medium"),
                ("AC-DS-03", "Verify volt/VAR optimization converges to target pf within \u00b10.02", "OptimizePowerFactor", "Power factor within 0.02 of target post-optimization", "Medium"),
                ("AC-DS-04", "Ensure all ADMS control actions are logged with operator identity and timestamp", "LogDistributionState", "Complete audit trail for every control action", "Medium"),
            ],
        }),
        ("4.2", {
            "title": "DER Management & Distributed Energy Resources",
            "description": "Distribution operators manage interconnection of customer-owned DERs including solar PV, battery storage, and EV chargers. The DERMS system aggregates capacity, dispatches for peak shaving, and monitors power quality at the grid edge.",
            "actors": ["DER Operator", "DER Customer", "Grid Integration Engineer"],
            "systems": ["DERMS (Generac / Enbala)", "ADMS (GE Grid Solutions)", "Customer DER Inverters", "Meter Data System", "ISO Market Portal"],
            "mermaid": [
                "DER_Customer->>DERMS: Register DER\nsolar: 10 kW, battery: 13.5 kWh, EV: 7.2 kW",
                "DERMS->>DER_Customer: Approve interconnection\nDER-2026-001 to DER-2026-030: registered",
                "DERMS->>Inverters: Poll status\n30 sites: total=300 kW solar, 200 kW battery",
                "Inverters->>DERMS: Fleet status\nsolar=240 kW, battery=150 kW charging, EV=50 kW",
                "ADMS->>DERMS: Dispatch request\npeak shave: reduce 100 kW, 4-7 PM today",
                "DERMS->>DERMS: Calculate allocation\n10 sites x 10 kW battery discharge each",
                "DERMS->>Inverters: Dispatch\nSite 001-010: battery discharge 10 kW each, 4-7 PM",
                "Inverters->>DERMS: Acknowledged\n10 batteries: 10 kW discharge, total=100 kW",
                "DERMS->>ADMS: Dispatch confirm\n100 kW reduction confirmed for 4-7 PM",
                "ADMS->>Operator: DER dispatch active\nfeeder load reduced 100 kW, pf=0.98",
                "DERMS->>Meter: Verify curtailment\ninterval data: 4 PM load vs baseline",
                "Meter->>DERMS: Baseline comparison\n4 PM: actual=850 kW vs baseline=950 kW, reduction=100 kW",
                "DERMS->>ISO: Settlement data\n10 DER sites, 100 kW, 4-7 PM, 300 kWh",
                "ISO->>DERMS: Settlement accepted\n$5,000 DR payment, Q2 2026",
                "DERMS->>DER_Customer: Payment notification\n$500 incentive, peak shave program",
            ],
            "integrations": [
                ("DER", "Register", "RegisterDERSite", "DER Customer Portal", "DERMS (Generac)", "Customer UI", "DERMS API (REST)", "API-led (Real-time)", "Simple"),
                ("DER", "Poll", "PollInverterFleet", "DERMS (Generac)", "DER Inverters", "DERMS API (Modbus TCP)", "Inverter API (SunSpec)", "API-led (Real-time)", "Medium"),
                ("DER", "Dispatch", "ReceiveDispatchRequest", "ADMS (GE Grid Solutions)", "DERMS (Generac)", "ADMS API (ICCP)", "DERMS API (REST)", "API-led (Real-time)", "High"),
                ("DER", "Battery", "DischargeBattery", "DERMS (Generac)", "Battery Inverters", "DERMS API (Modbus TCP)", "Inverter API (SunSpec)", "API-led (Real-time)", "High"),
                ("DER", "Meter", "VerifyLoadReduction", "DERMS (Generac)", "Meter Data System", "DERMS API (REST)", "Meter API (REST)", "Batch (Scheduled)", "Medium"),
                ("DER", "Settlement", "SubmitSettlementData", "DERMS (Generac)", "ISO Market Portal", "DERMS API (REST)", "ISO API (REST)", "Batch (Scheduled)", "Medium"),
                ("DER", "Payment", "NotifyDERPayment", "DERMS (Generac)", "DER Customer Portal", "DERMS API (REST)", "Customer UI", "Event-driven", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-DER-01", "Validate DER dispatch command reaches inverter within 30 seconds", "DischargeBattery", "Inverter acknowledges dispatch within 30s", "High"),
                ("AC-DER-02", "Confirm load reduction measurement accuracy within \u00b15% of baseline interval metering", "VerifyLoadReduction", "Meter data confirms reduction within 5% of DERMS estimate", "Medium"),
                ("AC-DER-03", "Verify DERMS aggregates all registered DERs into dispatch calculation", "ReceiveDispatchRequest", "All 30 registered sites included in dispatch allocation", "High"),
                ("AC-DER-04", "Ensure settlement data submitted to ISO within 1 hour of event end", "SubmitSettlementData", "Settlement submission timestamp within 1 hr of event close", "Medium"),
            ],
        }),
        ("4.3", {
            "title": "Fault Location, Isolation & Restoration (FLISR)",
            "description": "ADMS detects distribution faults via SCADA alarms and AMI voltage complaints, locates the faulted segment using fault current indicators, and automatically isolates the fault while restoring service to unfaulted sections.",
            "actors": ["Distribution Operator", "Outage Coordinator", "Field Crew"],
            "systems": ["ADMS (GE Grid Solutions)", "Fault Current Indicators", "SCADA RTU", "AMI Head-End", "Outage Management System (OMS)"],
            "mermaid": [
                "SCADA->>ADMS: Fault alarm\nFDR-MAIN-001: overcurrent=4.2 kA, phase A",
                "ADMS->>ADMS: Fault detection\nsection 3-4: fault type=AG, impedance=2.3\u03a9",
                "ADMS->>ADMS: FLISR analysis\nsource=SUB-MAIN-001, fault between FCIs #7 and #8",
                "ADMS->>Operator: Fault located\nFDR-MAIN-001, section 3-4: pole #47-#52",
                "Operator->>ADMS: Auto-isolate\nauthorize FLISR for FDR-MAIN-001",
                "ADMS->>SCADA: Open switch\nSW-047: open, section 3 isolated",
                "SCADA->>ADMS: Switch open\nSW-047: open, section 3 de-energized",
                "ADMS->>SCADA: Close tie switch\nSW-TIE: close, backfeed from FDR-BACKUP-001",
                "SCADA->>ADMS: Tie closed\nSW-TIE: closed, section 1-2 and 5-6 restored",
                "ADMS->>Operator: Restoration complete\n850 customers restored via backfeed, 150 customers out",
                "ADMS->>OMS: Create outage\n150 customers, section 3, fault=AG, stuck",
                "OMS->>Crew: Dispatch\nsection 3, pole #47-#52, patrol and repair",
                "Crew->>OMS: En route\nETA: 15 min, location: pole #47",
                "Crew->>OMS: Repairs complete\npole #48: insulator replaced, section 3 ready",
                "Operator->>ADMS: Restore section 3\nclose SW-047, open SW-TIE",
                "ADMS->>Operator: All restored\nFDR-MAIN-001: normal configuration, 0 customers out",
            ],
            "integrations": [
                ("FLISR", "Fault", "DetectFaultAlarm", "SCADA RTU", "ADMS (GE Grid Solutions)", "RTU DNP3", "ADMS DNP3", "Event-driven", "High"),
                ("FLISR", "Analysis", "RunFLISRAnalysis", "ADMS (GE Grid Solutions)", "ADMS (GE Grid Solutions)", "Internal", "Internal", "Batch (Real-time)", "High"),
                ("FLISR", "Isolate", "OpenIsolationSwitch", "ADMS (GE Grid Solutions)", "SCADA RTU", "ADMS DNP3", "RTU DNP3", "API-led (Real-time)", "High"),
                ("FLISR", "Restore", "CloseTieSwitch", "ADMS (GE Grid Solutions)", "SCADA RTU", "ADMS DNP3", "RTU DNP3", "API-led (Real-time)", "High"),
                ("FLISR", "OMS", "CreateOutageEvent", "ADMS (GE Grid Solutions)", "Outage Management System", "ADMS API (REST)", "OMS API (REST)", "Event-driven", "Medium"),
                ("FLISR", "Dispatch", "DispatchCrew", "Outage Management System", "Mobile Field Crew App", "OMS API (REST)", "Field App API (OAuth2)", "API-led (Real-time)", "Medium"),
                ("FLISR", "Restore", "RestoreNormalConfig", "Operator HMI", "ADMS (GE Grid Solutions)", "HMI API (REST)", "ADMS DNP3", "API-led (Real-time)", "High"),
            ],
            "acceptance_criteria": [
                ("AC-FL-01", "Validate fault detection and location within 30 seconds of alarm receipt", "DetectFaultAlarm", "FLISR identifies fault location within 30s of SCADA alarm", "High"),
                ("AC-FL-02", "Confirm automatic isolation and restoration completes under 2 minutes", "RunFLISRAnalysis", "Unfaulted sections restored within 2 min of fault detection", "High"),
                ("AC-FL-03", "Verify OMS outage record created automatically with fault details", "CreateOutageEvent", "OMS record created within 30s of FLISR completion", "Medium"),
                ("AC-FL-04", "Ensure backfeed tie switch rating is not exceeded during restoration", "CloseTieSwitch", "Backfeed loading remains within 90% of tie switch rating", "High"),
            ],
        }),
        ("4.4", {
            "title": "Distribution Planning & Network Optimization",
            "description": "Planning engineers analyze distribution network capacity, load growth, and voltage profiles to plan system upgrades. The optimization module performs volt/VAR control, loss minimization, and capacity forecasting.",
            "actors": ["Distribution Planning Engineer", "System Planner", "GIS Engineer"],
            "systems": ["Distribution Planning System (CYME / Synergi)", "GIS (ArcGIS Utility Network)", "ADMS", "Load Forecasting System", "Asset Management System"],
            "mermaid": [
                "GIS->>Planning: Export network model\n12 kV: 45 feeders, 1200 bus, 45,000 customers",
                "Planning->>Planning: Import model\nnode-breaker topology, conductor data, transformer banks",
                "Load_Forecast->>Planning: Peak forecast\n2027 summer peak: +4.2%, 450 MVA feeder area",
                "Planning->>Planning: Load flow analysis\nbase case: 85% loading, 5 feeders >90%",
                "Planning->>Planning: Contingency analysis\nN-1: feeder tie, 3 violations at peak",
                "Planning->>Engineer: Capacity report\n3 overloaded feeders, 5 low voltage (0.93 pu)",
                "Engineer->>Planning: Mitigation options\nreconductoring, new feeder, cap banks, regs",
                "Planning->>Planning: Option analysis\noption A: reconductor 3 feeders, $2.5M, 5 yr deferral",
                "Planning->>Engineer: Recommendation\noption A: reconductor, 3 feeders, 5-year plan",
                "Engineer->>GIS: Update planning model\nnew conductors, 2027-2028 work plan",
                "GIS->>Engineer: Model updated\nfeeder topology confirmed with new conductors",
                "Planning->>ADMS: New settings\nvolt/VAR schedule: new cap bank setpoints",
                "ADMS->>Planning: Settings accepted\nvoltage limits=0.95-1.05 pu, pf target=0.97",
                "Engineer->>Asset_Mgmt: Budget request\n$2.5M, priority=High, year=2027",
                "Planning->>Planning: Final report\nCapacity Plan 2027-2031: 15 projects, $45M total",
            ],
            "integrations": [
                ("Planning", "Model", "ExportNetworkModel", "GIS (ArcGIS Utility Network)", "Distribution Planning System", "GIS API (REST)", "Planning API (REST)", "Batch (Scheduled)", "Medium"),
                ("Planning", "Forecast", "ImportPeakForecast", "Load Forecasting System", "Distribution Planning System", "Forecast API (REST)", "Planning API (REST)", "Batch (Scheduled)", "Medium"),
                ("Planning", "Flow", "RunLoadFlowAnalysis", "Distribution Planning System", "Distribution Planning System", "Internal", "Internal", "Batch (Real-time)", "Medium"),
                ("Planning", "Options", "AnalyzeMitigationOptions", "Distribution Planning System", "Distribution Planning System", "Internal", "Internal", "Batch (Real-time)", "Medium"),
                ("Planning", "GIS", "UpdatePlanningModel", "Distribution Planning System", "GIS (ArcGIS Utility Network)", "Planning API (REST)", "GIS API (REST)", "Batch (Scheduled)", "Simple"),
                ("Planning", "ADMS", "DeployVoltVARSettings", "Distribution Planning System", "ADMS (GE Grid Solutions)", "Planning API (REST)", "ADMS API (ICCP)", "API-led (Real-time)", "Simple"),
                ("Planning", "Budget", "SubmitBudgetRequest", "Planning Engineer", "Asset Management System", "Planning UI", "Asset API (REST)", "API-led (Real-time)", "Simple"),
            ],
            "acceptance_criteria": [
                ("AC-DP-01", "Validate load flow analysis matches field measurements within \u00b12% for all feeders", "RunLoadFlowAnalysis", "Load flow results within 2% of SCADA readings", "High"),
                ("AC-DP-02", "Confirm planning model GIS topology completeness (100% of assets mapped)", "ExportNetworkModel", "All distribution assets in GIS are present in planning model", "Medium"),
                ("AC-DP-03", "Verify mitigation options include at least feeder reconductor, cap bank, and regulator alternatives", "AnalyzeMitigationOptions", "At least 3 distinct mitigation options provided per violation", "Medium"),
                ("AC-DP-04", "Ensure volt/VAR settings deployment does not cause temporary control disruption", "DeployVoltVARSettings", "No ADMS alarms during settings deployment window", "Medium"),
            ],
        }),
    ]),
}
